const ampEvents = [
  {
    ticket_link: "holdmyticket",
    name: "ALBERT CASTIGLIA",
    location: "FUSION | 708",
    time: "Jan 23rd 7:30pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "DUST CITY OPERA UNPLUGGED",
    location: "Juan Tabo Library",
    time: "Jan 24th 5:00pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "ALBERT CASTIGLIA",
    location: "Tumbleroot Brewery & Distillery",
    time: "Jan 24th 7:30pm",
    age_restriction: true,
    minimum_age: 21,
  },
  {
    ticket_link: "holdmyticket",
    name: "SADNESS, MADNESS, & MAYHEM",
    location: "A Haunted Folk Formal with Dust City Opera",
    time: "Jan 27",
  },
  {
    ticket_link: "holdmyticket",
    name: "ARKANSAUCE",
    location: "FUSION | The Cell",
    time: "Feb 2nd 8:00pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "DAVID WAX MUSEUM & LONE PIÑON",
    location: "Tumbleroot Brewery & Distillery",
    time: "Feb 5th 7:30pm",
    age_restriction: true,
    minimum_age: 21,
  },
  {
    ticket_link: "holdmyticket",
    name: "ROBERT JON AND THE WRECK",
    location: "Tumbleroot Brewery & Distillery",
    time: "Feb 8th 7:30pm",
    age_restriction: true,
    minimum_age: 21,
  },
  {
    ticket_link: "holdmyticket",
    name: "SUN SOUNDS",
    location: "Tony Hillerman Library",
    time: "Feb 13th 5:00pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "MAURO DURANTE & JUSTIN ADAMS",
    location: "FUSION | 708",
    time: "Feb 19th 7:30pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "MAURO DURANTE & JUSTIN ADAMS",
    location: "San Miguel Chapel",
    time: "Feb 20th 7:30pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "GOV'T MULE",
    location: "Thirty Years Strong",
    time: "Feb 21st",
  },
  {
    ticket_link: "holdmyticket",
    name: "DYLAN LEBLANC",
    location: "Paradiso",
    time: "Feb 22nd 7:30pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "LAS MIGAS",
    location: "National Hispanic Cultural Center - Journal Theatre",
    time: "Feb 24th 7:30pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "SUN SOUNDS",
    location: "Lomas Tramway Library",
    time: "Feb 27th 5:00pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "THE PSYCHOLOGY OF SERIAL KILLERS",
    location: "The Lensic",
    time: "Mar 2nd 7:30pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "ALASDAIR FRASER & NATALIE HAAS",
    location: "St Francis Auditorium at the New Mexico Museum of Art",
    time: "Mar 15th 7:30pm",
  },
  {
    ticket_link: "holdmyticket",
    name: "BRIAN CULBERTSON",
    location: "The Trilogy Tour",
    time: "Mar 22nd",
  },
  {
    ticket_link: "holdmyticket",
    name: "MR. JOE JACKSON PRESENTS: JOE JACKSON SOLO AND THE MUSIC OF MAX CHAMPION",
    location: "The Lensic",
    time: "Jun 22nd 8:00pm",
  },
];
