export const events = [
  {
    name: "Betty Benedeadly",
    time: "5:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 2",
  },
  {
    name: "Bad Habit",
    time: "6:00pm",
    venue: "The Hopper Pub & Pizzaria",
    date: "Friday, February 2",
  },
  {
    name: "Lani Nash",
    time: "7:00pm",
    venue: "Albuquerque Distilling",
    date: "Friday, February 2",
  },
  {
    name: "Bluehouse Band",
    time: "7:00pm",
    venue: "Casa Vieja Brewery",
    date: "Friday, February 2",
  },
  {
    name: "Joe Daddy Warner & Friends",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Friday, February 2",
  },
  {
    name: "TOBYMAC's Hits Deep Tour 2024",
    time: "7:00pm",
    venue: "Rio Rancho Events Center",
    date: "Friday, February 2",
  },
  {
    name: "House of Love w/ DJ Kaleido",
    time: "7:00pm",
    venue: "Tractor Brewing Westside",
    date: "Friday, February 2",
  },
  {
    name: "Chile Line Friday Jazz",
    time: "7:00pm",
    venue: "Chile Line Brewery",
    date: "Friday, February 2",
  },
  {
    name: "Benise",
    time: "7:30pm",
    venue: "KiMo Theatre",
    date: "Friday, February 2",
  },
  {
    name: "AMP Concerts Presents Arkansauce",
    time: "8:00pm",
    venue: "FUSION | 708",
    date: "Friday, February 2",
  },
  {
    name: "Pearl Charles",
    time: "8:00pm",
    venue: "El Rey Court",
    date: "Friday, February 2",
  },
  {
    name: "Shoegaze Into the Sun",
    time: "8:00pm",
    venue: "Launchpad",
    date: "Friday, February 2",
  },
  {
    name: "Roadhouse Prophets",
    time: "8:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 2",
  },
  {
    name: "Wifisfuneral",
    time: "8:30pm",
    venue: "Electric Playhouse",
    date: "Friday, February 2",
  },
  {
    name: "Cumbia Night with El Gozao",
    time: "9:00pm",
    venue: "JUNO brewery + cafe + art",
    date: "Friday, February 2",
  },
  {
    name: "Hello Darlin'",
    time: "2:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 3",
  },
  {
    name: "Cupid's Carnival f/ Artrageous & The Pink Flamingoes",
    time: "5:30pm",
    venue: "Santa Ana Star Casino Hotel",
    date: "Saturday, February 3",
  },
  {
    name: "Bob Maus Blues & Soul",
    time: "6:00pm",
    venue: "Inn & Spa at Loretto",
    date: "Saturday, February 3",
  },
  {
    name: "Traveler in Pain 25th Anniversary Show",
    time: "6:30pm",
    venue: "Skidmore’s Holiday Bowl",
    date: "Saturday, February 3",
  },
  {
    name: "Stray Dawgs",
    time: "7:00pm",
    venue: "Tractor Brewing Nob Hill",
    date: "Saturday, February 3",
  },
  {
    name: "Stingrays",
    time: "7:00pm",
    venue: "The Hopper Pub & Pizzaria",
    date: "Saturday, February 3",
  },
  {
    name: "Gold Necklace",
    time: "7:00pm",
    venue: "Launchpad",
    date: "Saturday, February 3",
  },
  {
    name: "Black Smoke Blues Band",
    time: "7:00pm",
    venue: "Casa Vieja Brewery",
    date: "Saturday, February 3",
  },
  {
    name: "Yeah It's Daniel",
    time: "7:00pm",
    venue: "Tractor Brewing Westside",
    date: "Saturday, February 3",
  },
  {
    name: "Bad Habit & The Enablers",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Saturday, February 3",
  },
  {
    name: "Calle 66 - Salsa Band",
    time: "7:30pm",
    venue: "Paradiso",
    date: "Saturday, February 3",
  },
  {
    name: "Vakenn",
    time: "8:00pm",
    venue: "JUNO brewery + cafe + art",
    date: "Saturday, February 3",
  },
  {
    name: "Nouveau Hippies",
    time: "8:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 3",
  },
  {
    name: "Temple of Sound Presents LOVE & SHADOWS",
    time: "8:00pm",
    venue: "KiMo Theatre",
    date: "Saturday, February 3",
  },
  {
    name: "Mija",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Saturday, February 3",
  },
  {
    name: "Joshwa",
    time: "9:30pm",
    venue: "Electric Playhouse",
    date: "Saturday, February 3",
  },
  {
    name: "Slim Belly Blues Band",
    time: "2:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Sunday, February 4",
  },
  {
    name: "Slim Belly Blues Band",
    time: "2:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Sunday, February 4",
  },
  {
    name: "Kaktus Kats Blues Jam",
    time: "2:00pm",
    venue: "Kaktus Brewing Co.",
    date: "Sunday, February 4",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, February 4",
  },
  {
    name: "Ashes of Today",
    time: "4:00pm",
    venue: "The Hopper Pub & Pizzaria",
    date: "Sunday, February 4",
  },
  {
    name: "Old-Time Jam",
    time: "4:00pm",
    venue: "Nuckolls Brewing Co.",
    date: "Sunday, February 4",
  },
  {
    name: "Karaoke With The Tiff",
    time: "5:00pm",
    venue: "Buttercrust Pizza",
    date: "Sunday, February 4",
  },
  {
    name: "Rhyme Craft at the Mineshaft Tavern",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Wednesday, February 7",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, February 8",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, February 8",
  },
  {
    name: "Open Mic Hosted by DeRangers",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Thursday, February 8",
  },
  {
    name: "Bobcat",
    time: "7:00pm",
    venue: "Tractor Brewing Nob Hill",
    date: "Thursday, February 8",
  },
  {
    name: "Thomas Blues J.D. Sipe and Joe Daddy Warner",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Thursday, February 8",
  },
  { name: "Ov Sulfur", time: "7:30pm", venue: "Launchpad", date: "Thursday, February 8" },
  {
    name: "Lori Ottino, Josh Martin & Margaret Burke",
    time: "5:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 9",
  },
  {
    name: "Lenin & McCarthy",
    time: "6:00pm",
    venue: "Albuquerque Distilling",
    date: "Friday, February 9",
  },
  {
    name: "Bill Hearne at La Fonda Hotel",
    time: "6:30pm",
    venue: "La Fonda on the Plaza",
    date: "Friday, February 9",
  },
  {
    name: "The Westernhers",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Friday, February 9",
  },
  {
    name: "Innastate: 10 Year Anniversary Show",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Friday, February 9",
  },
  {
    name: "DJ Caterwaul Spins Out",
    time: "8:00pm",
    venue: "Tractor Brewing Nob Hill",
    date: "Friday, February 9",
  },
  {
    name: "Twin Tribes",
    time: "8:00pm",
    venue: "Sunshine Theater",
    date: "Friday, February 9",
  },
  {
    name: "Dirty Brown Jug Band",
    time: "8:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 9",
  },
  {
    name: "Goth Night & Dark Market: Gothic Valentine's Day Edition",
    time: "8:00pm",
    venue: "Tractor Brewing Wells Park",
    date: "Friday, February 9",
  },
  { name: "Koffin Kats", time: "8:00pm", venue: "Launchpad", date: "Friday, February 9" },
  {
    name: "Twin Tribes After Party",
    time: "11:00pm",
    venue: "Moonlight Lounge",
    date: "Friday, February 9",
  },
  {
    name: "Jim Almand",
    time: "1:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 10",
  },
  {
    name: "Partizani Brass Band 10th Anniversary Mardi Gras/Carnival Extravaganza",
    time: "2:00pm",
    venue: "Canteen Brewhouse",
    date: "Saturday, February 10",
  },
  {
    name: "Bob Maus Blues & Soul",
    time: "6:00pm",
    venue: "Inn & Spa at Loretto",
    date: "Saturday, February 10",
  },
  {
    name: "Duke City Swampcoolers",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Saturday, February 10",
  },
  {
    name: "EQNX Jazz Quintet",
    time: "7:00pm",
    venue: "Tractor Brewing Nob Hill",
    date: "Saturday, February 10",
  },
  {
    name: "Sandbox Music Series",
    time: "7:30pm",
    venue: "Entropy Gallery",
    date: "Saturday, February 10",
  },
  {
    name: "Cabaret Paradiso: A Spectacular Valentine's Moulin Rouge with Frenchy Toast",
    time: "7:30pm",
    venue: "Paradiso",
    date: "Saturday, February 10",
  },
  {
    name: "Silver Sky Blues Band",
    time: "8:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 10",
  },
  {
    name: "One More Time: A Tribute to Daft Punk",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Saturday, February 10",
  },
  {
    name: "Los Blue Ventures",
    time: "8:00pm",
    venue: "Revel Entertainment Center",
    date: "Saturday, February 10",
  },
  {
    name: "Great White/Slaughter",
    time: "8:00pm",
    venue: "Isleta Resort & Casino",
    date: "Saturday, February 10",
  },
  {
    name: "Strange Mix",
    time: "8:00pm",
    venue: "Moonlight Lounge",
    date: "Saturday, February 10",
  },
  {
    name: "Innastate - 10 Year Anniversary",
    time: "8:30pm",
    venue: "Launchpad",
    date: "Saturday, February 10",
  },
  {
    name: "Electric Valentine",
    time: "9:00pm",
    venue: "Historic El Rey Theatre",
    date: "Saturday, February 10",
  },
  {
    name: "Bluegrass & Bagels Jam",
    time: "10:00am",
    venue: "Railyard Park Community Room",
    date: "Sunday, February 11",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, February 11",
  },
  {
    name: "Karaoke With The Tiff",
    time: "5:00pm",
    venue: "Buttercrust Pizza",
    date: "Sunday, February 11",
  },
  { name: "Glixen", time: "9:30pm", venue: "Launchpad", date: "Sunday, February 11" },
  {
    name: "Bill Hearne at La Fonda Hotel",
    time: "6:30pm",
    venue: "La Fonda on the Plaza",
    date: "Monday, February 12",
  },
  {
    name: "JP Saxe: A Grey Area Tour",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Monday, February 12",
  },
  {
    name: "AMP Concerts Presents Sun Sounds",
    time: "5:00pm",
    venue: "Tony Hillerman Library",
    date: "Tuesday, February 13",
  },
  {
    name: "EQNX Jazz Band",
    time: "6:00pm",
    venue: "Ex Novo Brewing",
    date: "Tuesday, February 13",
  },
  {
    name: "Dirtwire: The Four Directions Tour",
    time: "6:00pm",
    venue: "Meow Wolf",
    date: "Tuesday, February 13",
  },
  {
    name: "Mardi Gras Pub Crawl with the Hill Stompers Marching Band",
    time: "6:30pm",
    venue: "Cowgirl",
    date: "Tuesday, February 13",
  },
  {
    name: "Mardi Gras w/ Jim Almand & Felix y los Gatos",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Tuesday, February 13",
  },
  {
    name: "Roseanne Cash",
    time: "7:30pm",
    venue: "KiMo Theatre",
    date: "Tuesday, February 13",
  },
  {
    name: "Valentine's Day w/ Chachalacas",
    time: "6:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Wednesday, February 14",
  },
  {
    name: "Matisyahu: Hold the Fire Tour 2024",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Wednesday, February 14",
  },
  {
    name: "Casa Flamenca opens 2024 Flamenco Concert Season with Artists from Spain",
    time: "7:00pm",
    venue: "San Miguel Chapel",
    date: "Wednesday, February 14",
  },
  {
    name: "Covers by Lovers",
    time: "8:00pm",
    venue: "Launchpad",
    date: "Wednesday, February 14",
  },
  {
    name: "Red McAdam and Marley Hale",
    time: "8:00pm",
    venue: "El Rey Court",
    date: "Wednesday, February 14",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, February 15",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, February 15",
  },
  {
    name: "Grant Turner & Carson Barry",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Thursday, February 15",
  },
  {
    name: "Open Mic Hosted by DeRangers",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Thursday, February 15",
  },
  {
    name: "BeauSoleil avec Michael Doucet",
    time: "7:30pm",
    venue: "Old San Ysidro Church",
    date: "Thursday, February 15",
  },
  { name: "Ballistic Batz", time: "8:30pm", venue: "Launchpad", date: "Thursday, February 15" },
  {
    name: "Queen Bee",
    time: "5:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 16",
  },
  {
    name: "Bluebird Cafe Songwriters' Concert Series",
    time: "6:00pm",
    venue: "Bishop's Lodge",
    date: "Friday, February 16",
  },
  {
    name: "Spiral Pilots",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Friday, February 16",
  },
  {
    name: "Dani-Rae Clark and The Let Downs",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 16",
  },
  { name: "Manila Killa", time: "8:00pm", venue: "Meow Wolf", date: "Friday, February 16" },
  {
    name: "Historias De Amor-Albuquerque",
    time: "8:00pm",
    venue: "Casa Flamenca",
    date: "Friday, February 16",
  },
  {
    name: "Casa Flamenca 2024 Tablao Season Featuring Artists From Spain",
    time: "8:00pm",
    venue: "Casa Flamenca",
    date: "Friday, February 16",
  },
  {
    name: "Youngsville - 'Hometown Relics' Vinyl Release Party",
    time: "8:30pm",
    venue: "Launchpad",
    date: "Friday, February 16",
  },
  {
    name: "Odd Dog",
    time: "2:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 17",
  },
  {
    name: "Bluebird Cafe Songwriters' Concert Series",
    time: "6:00pm",
    venue: "Bishop's Lodge",
    date: "Saturday, February 17",
  },
  {
    name: "Bob Maus Blues & Soul",
    time: "6:00pm",
    venue: "Inn & Spa at Loretto",
    date: "Saturday, February 17",
  },
  {
    name: "Restorative Gong Bath",
    time: "6:00pm",
    venue: "Studio Sway",
    date: "Saturday, February 17",
  },
  {
    name: "Let IT Grow",
    time: "7:00pm",
    venue: "Tortuga Gallery",
    date: "Saturday, February 17",
  },
  { name: "Rock Zone", time: "7:00pm", venue: "The Range Cafe", date: "Saturday, February 17" },
  { name: "Tornillo", time: "8:00pm", venue: "Launchpad", date: "Saturday, February 17" },
  {
    name: "Late Night Radio: Pocket Full of Dreams Tour",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Saturday, February 17",
  },
  {
    name: "Bella Gigante Cabaret Show",
    time: "8:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 17",
  },
  {
    name: "Historias De Amor-Albuquerque",
    time: "8:00pm",
    venue: "Casa Flamenca",
    date: "Saturday, February 17",
  },
  {
    name: "Casa Flamenca 2024 Tablao Season Featuring Artists From Spain",
    time: "8:00pm",
    venue: "Casa Flamenca",
    date: "Saturday, February 17",
  },
  {
    name: "Clark Libbey",
    time: "2:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Sunday, February 18",
  },
  {
    name: "Time to... Dance",
    time: "4:00pm",
    venue: "Paradiso",
    date: "Sunday, February 18",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, February 18",
  },
  {
    name: "Karaoke With The Tiff",
    time: "5:00pm",
    venue: "Buttercrust Pizza",
    date: "Sunday, February 18",
  },
  {
    name: "Stephanie Hatfield",
    time: "7:00pm",
    venue: "El Rey Court",
    date: "Sunday, February 18",
  },
  {
    name: "Historias De Amor-Albuquerque",
    time: "7:00pm",
    venue: "Casa Flamenca",
    date: "Sunday, February 18",
  },
  {
    name: "Casa Flamenca 2024 Tablao Season Featuring Artists From Spain",
    time: "7:00pm",
    venue: "Casa Flamenca",
    date: "Sunday, February 18",
  },
  {
    name: "Justin Adams & Mauro Durante",
    time: "7:30pm",
    venue: "FUSION | 708",
    date: "Monday, February 19",
  },
  { name: "Zulu", time: "7:30pm", venue: "Launchpad", date: "Monday, February 19" },
  {
    name: "The Real Matt Jones",
    time: "6:00pm",
    venue: "Ex Novo Brewing",
    date: "Tuesday, February 20",
  },
  {
    name: "Shawn Hess & Earl Buck",
    time: "7:00pm",
    venue: "El Rey Court",
    date: "Tuesday, February 20",
  },
  { name: "Crypta", time: "8:00pm", venue: "Launchpad", date: "Tuesday, February 20" },
  { name: "SunSquabi", time: "6:00pm", venue: "Meow Wolf", date: "Wednesday, February 21" },
  {
    name: "John Francis & the Poor Clares with Ciarra Fragale",
    time: "8:00pm",
    venue: "El Rey Court",
    date: "Wednesday, February 21",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, February 22",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, February 22",
  },
  {
    name: "Machine Head",
    time: "6:30pm",
    venue: "Sunshine Theater",
    date: "Thursday, February 22",
  },
  { name: "Karina Rykman", time: "7:00pm", venue: "Meow Wolf", date: "Thursday, February 22" },
  { name: "Folk Jam", time: "7:00pm", venue: "La Reina", date: "Thursday, February 22" },
  {
    name: "Open Mic Hosted by DeRangers",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Thursday, February 22",
  },
  {
    name: "Keith Burnstein",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Thursday, February 22",
  },
  {
    name: "Lensic Presents Terence Blanchard, E-Collective, and Turtle Island String Quartet",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Thursday, February 22",
  },
  { name: "Living Colour", time: "8:00pm", venue: "Launchpad", date: "Thursday, February 22" },
  {
    name: "Dusty the Kid & Dirty Laundry",
    time: "5:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 23",
  },
  {
    name: "Tony O & The Greatest Band Ever: Start Making Sense ",
    time: "7:00pm",
    venue: "Launchpad",
    date: "Friday, February 23",
  },
  {
    name: "Terry Winchell & The Fine Line",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Friday, February 23",
  },
  {
    name: "Lensic Presents Judith Hill",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Friday, February 23",
  },
  {
    name: "Stratus Phear",
    time: "7:30pm",
    venue: "Casa Vieja Brewery",
    date: "Friday, February 23",
  },
  { name: "Minnesota", time: "8:00pm", venue: "Meow Wolf", date: "Friday, February 23" },
  {
    name: "Third Annual Apparition Zombie Prom",
    time: "8:00pm",
    venue: "Historic El Rey Theatre",
    date: "Friday, February 23",
  },
  {
    name: "Free Range Buddhas",
    time: "8:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, February 23",
  },
  {
    name: "Iron Chiwawa",
    time: "2:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 24",
  },
  {
    name: "Bob Maus Blues & Soul",
    time: "6:00pm",
    venue: "Inn & Spa at Loretto",
    date: "Saturday, February 24",
  },
  {
    name: "Champagne & Chocolates",
    time: "6:00pm",
    venue: "Rio Chama Steakhouse",
    date: "Saturday, February 24",
  },
  {
    name: "The Roswells",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Saturday, February 24",
  },
  {
    name: "Operation Rewind",
    time: "8:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Saturday, February 24",
  },
  { name: "Evan Dando", time: "8:00pm", venue: "Launchpad", date: "Saturday, February 24" },
  {
    name: "Julian Dossett",
    time: "2:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Sunday, February 25",
  },
  {
    name: "DEIDRE MCCALLA LIVE CONCERT ",
    time: "3:00pm",
    venue: "LA MESA PRESBYTERIAN CHURCH",
    date: "Sunday, February 25",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, February 25",
  },
  {
    name: "Karaoke With The Tiff",
    time: "5:00pm",
    venue: "Buttercrust Pizza",
    date: "Sunday, February 25",
  },
  {
    name: "Kid Bloom: Inner Light Tour 2024",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Sunday, February 25",
  },
  {
    name: "WHATEVS EP release party",
    time: "7:00pm",
    venue: "JUNO",
    date: "Sunday, February 25",
  },
  {
    name: "Ariel Pink",
    time: "8:00pm",
    venue: "Launchpad",
    date: "Sunday, February 25",
  },
  {
    name: "The Green",
    time: "8:00pm",
    venue: "Sunshine Theater",
    date: "Sunday, February 25",
  },
  {
    name: "Oscar Butler",
    time: "6:00pm",
    venue: "Ex Novo Brewing",
    date: "Tuesday, February 27",
  },
  {
    name: "Mindchatter",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Tuesday, February 27",
  },
  {
    name: "Grieves",
    time: "8:00pm",
    venue: "Launchpad",
    date: "Tuesday, February 27",
  },
  {
    name: "JER",
    time: "8:00pm",
    venue: "Launchpad",
    date: "Wednesday, February 28",
  },
  {
    name: "John 5 and the Creatures",
    time: "8:00pm",
    venue: "Sunshine Theater",
    date: "Wednesday, February 28",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, February 29",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, February 29",
  },
  {
    name: "Open Mic Hosted by DeRangers",
    time: "7:00pm",
    venue: "The Range Cafe",
    date: "Thursday, February 29",
  },
  {
    name: "Beats Antique: An Immersive Experience with Zoe Jake's House of Tarot",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Thursday, February 29",
  },
  {
    name: "Open Mic with Stephen",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Thursday, February 29",
  },
  {
    name: "Indigo De Souza",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Friday, March 1",
  },
  {
    name: "Lensic Presents Taj Mahal Quartet and Sona Jobarteh",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Friday, March 1",
  },
  {
    name: "Lensic Presents Taj Mahal Quartet and Sona Jobarteh",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Friday, March 1",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, March 3",
  },
  {
    name: "Old-Time Jam",
    time: "4:00pm",
    venue: "Nuckolls Brewing Co.",
    date: "Sunday, March 3",
  },
  {
    name: "Nick Brower",
    time: "7:00pm",
    venue: "El Rey Court",
    date: "Sunday, March 3",
  },
  {
    name: "Early Eyes & Trash Panda",
    time: "6:00pm",
    venue: "Meow Wolf",
    date: "Tuesday, March 5",
  },
  {
    name: "Skizzy Mars",
    time: "6:00pm",
    venue: "Meow Wolf",
    date: "Wednesday, March 6",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, March 7",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, March 7",
  },
  {
    name: "Songwriter's Circle",
    time: "6:30pm",
    venue: "Queen Bee Music Association",
    date: "Thursday, March 7",
  },
  {
    name: "Strangers From Afar",
    time: "7:00pm",
    venue: "The Mine Shaft Tavern",
    date: "Friday, March 8",
  },
  {
    name: "Real Estate: Infinite Jangle Tour",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Friday, March 8",
  },
  {
    name: "Experience a Lotus Sound Bath at FUSION | 708",
    time: "6:00pm",
    venue: "FUSION | 708",
    date: "Saturday, March 9",
  },
  {
    name: "Bluegrass & Bagels Jam",
    time: "10:00am",
    venue: "Railyard Park Community Room",
    date: "Sunday, March 10",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, March 10",
  },
  {
    name: "Husbands",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Sunday, March 10",
  },
  {
    name: "Petey",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Monday, March 11",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, March 14",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, March 14",
  },
  {
    name: "Bluebird Cafe Songwriters' Concert Series",
    time: "6:00pm",
    venue: "Bishop's Lodge",
    date: "Friday, March 15",
  },
  {
    name: "Bluebird Cafe Songwriters' Concert Series",
    time: "6:00pm",
    venue: "Bishop's Lodge",
    date: "Saturday, March 16",
  },
  {
    name: "Lensic Presents Lúnasa",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Saturday, March 16",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, March 17",
  },
  {
    name: "Deap Vally",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Monday, March 18",
  },
  {
    name: "BAILEN",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Tuesday, March 19",
  },
  {
    name: "Performance Santa Fe presents Kronos Quartet",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Tuesday, March 19",
  },
  {
    name: "Essential Machine  + Village Elder + Gray Star Ghost + Brandon Taylor",
    time: "8:00pm",
    venue: "JUNO brewery + cafe + art",
    date: "Tuesday, March 19",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, March 21",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, March 21",
  },
  {
    name: "Toto: Dogz of Oz Tour",
    time: "8:00pm",
    venue: "Revel Entertainment Center",
    date: "Saturday, March 23",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, March 24",
  },
  {
    name: "Hannah Wicklund",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Monday, March 25",
  },
  {
    name: "Bill Hearne at Cowgirl BBQ",
    time: "4:00pm",
    venue: "Cowgirl",
    date: "Thursday, March 28",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, March 28",
  },
  {
    name: "Folk Jam",
    time: "7:00pm",
    venue: "La Reina",
    date: "Thursday, March 28",
  },
  {
    name: "Kelsy Karter & The Heroines",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Friday, March 29",
  },
  {
    name: "Music on the Mountain",
    time: "4:00pm",
    venue: "Rumor Brewing Co",
    date: "Sunday, March 31",
  },
  {
    name: "Lensic Presents Drum Tao",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Tuesday, April 2",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, April 4",
  },
  {
    name: "Songwriter's Circle",
    time: "6:30pm",
    venue: "Queen Bee Music Association",
    date: "Thursday, April 4",
  },
  {
    name: "Lensic Presents Chris Botti",
    time: "7:30pm",
    venue: "Lensic Performing Arts Center",
    date: "Thursday, April 4",
  },
  {
    name: "Dirtysnatcha",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Friday, April 5",
  },
  {
    name: "Old-Time Jam",
    time: "4:00pm",
    venue: "Nuckolls Brewing Co.",
    date: "Sunday, April 7",
  },
  {
    name: "A. Savage",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Sunday, April 7",
  },
  {
    name: "Chastity Belt",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Monday, April 8",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, April 11",
  },
  {
    name: "Slow Hollows",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Thursday, April 11",
  },
  {
    name: "SubDocta: Santa Fe - Left for Dead Tour",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Friday, April 12",
  },
  {
    name: "Slothrust: Of Course You Did Tour",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Saturday, April 13",
  },
  {
    name: "Bluegrass & Bagels Jam",
    time: "10:00am",
    venue: "Railyard Park Community Room",
    date: "Sunday, April 14",
  },
  {
    name: "Mannequin Pussy",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Monday, April 22",
  },
  {
    name: "Dark Honey Karaoke",
    time: "6:00pm",
    venue: "Gold Street Pizza & Brew",
    date: "Thursday, April 25",
  },
  {
    name: "Folk Jam",
    time: "7:00pm",
    venue: "La Reina",
    date: "Thursday, April 25",
  },
  {
    name: "Sturtz",
    time: "7:00pm",
    venue: "El Rey Court",
    date: "Sunday, April 28",
  },
  {
    name: "Caroline Rose",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Sunday, April 28",
  },
  {
    name: "Songwriter's Circle",
    time: "6:30pm",
    venue: "Queen Bee Music Association",
    date: "Thursday, May 2",
  },
  {
    name: "Bendigo Fletcher",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Saturday, May 4",
  },
  {
    name: "Old-Time Jam",
    time: "4:00pm",
    venue: "Nuckolls Brewing Co.",
    date: "Sunday, May 5",
  },
  {
    name: "Ekkstacy",
    time: "7:00pm",
    venue: "Meow Wolf",
    date: "Thursday, May 9",
  },
  {
    name: "G Flip",
    time: "8:00pm",
    venue: "Meow Wolf",
    date: "Saturday, May 11",
  },
  {
    name: "Bluegrass & Bagels Jam",
    time: "10:00am",
    venue: "Railyard Park Community Room",
    date: "Sunday, May 12",
  },
  {
    name: "Wednesday",
    time: "6:00pm",
    venue: "Meow Wolf",
    date: "Tuesday, May 14",
  },
  {
    name: "Charles Wesley Godwin",
    time: "8:00pm",
    venue: "Revel Entertainment Center",
    date: "Thursday, May 30",
  },
  {
    name: "Old-Time Jam",
    time: "4:00pm",
    venue: "Nuckolls Brewing Co.",
    date: "Sunday, June 2",
  },
  {
    name: "Bluegrass & Bagels Jam",
    time: "10:00am",
    venue: "Railyard Park Community Room",
    date: "Sunday, June 9",
  },
];
