services:
  # Postgres Database
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lmx-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
