packages:
  - "apps/*"
  - "libs/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.56.2
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.10.0
  tailwindcss: ^3.4.11
  typescript: ^5.6.2
  zod: ^3.23.8
  next: ^14.2.11

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
