export const events = [
  {
    performers: [{ name: "Lost 0x" }],
    name: "Lost 0x",
    description: undefined,
    date: "01 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "The Derangers" }],
    name: "Open Mic/Jam hosted by the Derangers",
    description: undefined,
    date: "01 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Prieto, Bea and Boogaloo B" }],
    name: "Y2K Night",
    description:
      "dive into their napster downloads and bring you nostalgic tunes from the era of TRL, nu metal, boy bands, flip phones, post-grunge and proto-crunk. Frost your tips! Wear your JNCOs and Osiris D3s, and other phat attir ...",
    date: "01 FEB",
    time: "7:00 PM - 11:00 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Nikki Manos" }],
    name: "Nikki Manos",
    description: undefined,
    date: "01 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Jared James Nichols" }],
    name: "Jared James Nichols",
    description: undefined,
    date: "01 FEB",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Phora" }],
    name: "Phora Saints & Sinners Tour 2024",
    description: undefined,
    date: "01 FEB",
    time: "8:00 PM",
    venue: "El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "The Hayseed Band" }],
    name: "The Hayseed Band",
    description: undefined,
    date: "01 FEB",
    time: "9:00 PM - 12:00 AM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Betty Benedeadly" }],
    name: "Betty Benedeadly",
    description: undefined,
    date: "02 FEB",
    time: "5:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Chillhouse" }],
    name: "ChillHouse & Hillary Smith",
    description: undefined,
    date: "02 FEB",
    time: "5:30 PM - 8:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Memphis P-Tails" }],
    name: "The Memphis P-Tails",
    description: undefined,
    date: "02 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Buck Meek" }],
    name: "Buck Meek",
    description:
      "For his latest solo album, Buck Meek, lead guitarist of Big Thief, went back to Texas – to the border town of Tornillo 560 miles from his hometown of Wimberley – to record Haunted Mountain. The band – Buck (guitar, vocals), Adam Brisbin (guitar), Austin Vaughn (drums), Ken Woodward (bass), Mat Davidson (pedal steel, vocals), and Dylan Meek (keys) – recorded the eleven songs that make up Haunted Mountain over the course of two weeks at Sonic Ranch studio. The album was produced by Davidson and engineered and mixed by Adrian Olsen. The album follows Meek’s 2018 self-titled debut and […] ...",
    date: "02 FEB",
    time: "7:00 PM - 10:00 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Joe Daddy Warner" }],
    name: "JOE DADDY WARNER & Friends",
    description: undefined,
    date: "02 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Benise" }],
    name: "Benise",
    description:
      "Benise, the Prince of the Spanish Guitar, returns to the historic KiMo Theatre. His show FIESTA! will be a musical journey through Spanish Flamenco, Cuban Salsa, Brazillian Samba, Parisian Waltz, exotic drumming and more. Doors open at 6:30 p.m. ...",
    date: "02 FEB",
    time: "7:30 PM - 9:30 PM",
    venue: "Kimo Theatre",
    address: "423 Central Ave. NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Arkansauce" }],
    name: "Arkansauce",
    description:
      "Arkansauce is a genre-hopping, four-piece string band from northwest Arkansas, bending the rules and blurring the lines between bluegrass, newgrass, folk, Americana, country, blues, and funk. With a loyal following growing every day in the Natural State and along their tour routes, the band is proud to be stepping into a hard-driving sound unique to the Arkansas quartet. An Arkansauce show is riddled with improvisational guitar, banjo, and mandolin leads, paired with powerful harmonies and heart-felt songwriting, all held together by deep foot-stompin’ bass grooves. There’s an undeniably intimate connection between the band and their fans that’s contagious and leaves […] ...",
    date: "02 FEB",
    time: "8:00 PM",
    venue: "Fusion | The Cell",
    address: "700 1st Street NorthwestAlbuquerque, NM, 87102",
  },
  {
    performers: [{ name: "Roadhouse Prophets" }],
    name: "Roadhouse Prophets",
    description: undefined,
    date: "02 FEB",
    time: "8:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Brandon Saiz Band" }],
    name: "Brandon Saiz Band",
    description: "Country Music original and cover band out of New Mexico. ...",
    date: "02 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Hello Darlin" }],
    name: "Hello Darlin",
    description: undefined,
    date: "03 FEB",
    time: "2:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Hicks & Fowler" }],
    name: "Hicks & Fowler",
    description: undefined,
    date: "03 FEB",
    time: "5:30 PM - 8:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Rudy Boy Experiment" }],
    name: "Rudy Boy Experiment",
    description:
      "Southwest Rock and Blues innovators The Rudy Boy Experiment hail from the land of enchantment of Albuquerque New Mexico. The act has become very popular in the western U.S. This 3-piece group features the multi-talented Rudy “Boy” Jaramillo on vocals, as well as lead and rhythm guitar. Rudy Boy has released close to 10 albums over the past decade, with a growing national fanbase anticipating each debut. In 2010, The Rudy Boy Experiment signed a digital distribution deal with DSN Music, to give the group a worldwide platform for their long awaited release Places. The 11 track release features a […] ...",
    date: "03 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Bad Habits & The Enablers" }],
    name: "Bad Habits & The Enablers",
    description: undefined,
    date: "03 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Benise" }],
    name: "BENISE – Fiesta!",
    description:
      "Emmy Award Winning Spanish Guitar and Dance Spectacular!It’s one hot night as Benise, “The Prince of Spanish Guitar,” and his Emmy Award winning production come to town as part of his global tour. Armed with his Spanish guitar, Benise will take the audience on an unprecedented and epic adventure through Spanish Flamenco, Cuban Salsa, Brazilian Samba, Parisian Waltz, exotic drumming, and more!FIESTA! showcases songs from Benise’s 7th PBS Special. Performing classic Rock anthems from Led Zeppelin and AC/DC and fusing them with Spanish guitar and dance to bring a fierce intensity to these new interpretations. In addition, Benise adds his […] ...",
    date: "03 FEB",
    time: "7:30 PM",
    venue: "Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "Gold Necklace" }],
    name: "Gold Necklace",
    description: "with Moondough * Lobby Boxer ...",
    date: "03 FEB",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Vakenn" }],
    name: "Vakenn",
    description: undefined,
    date: "03 FEB",
    time: "8:00 PM - 11:00 PM",
    venue: "Juno Brewery",
    address: "1501 1st St. NW, Albuquerque, NM, United ,States, New Mexico",
  },
  {
    performers: [{ name: "Nouveau Hippies" }],
    name: "Nouveau Hippies",
    description: undefined,
    date: "03 FEB",
    time: "8:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "The Hayseed Band" }],
    name: "The Hayseed Band",
    description: undefined,
    date: "03 FEB",
    time: "9:00 PM - 12:00 AM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Brandon Saiz Band" }],
    name: "Brandon Saiz Band",
    description: "Country Music original and cover band out of New Mexico. ...",
    date: "03 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Slim Belly Blues Band" }],
    name: "Slim Belly Blues Band",
    description: undefined,
    date: "04 FEB",
    time: "2:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Mineral Hill" }],
    name: "Mineral Hill",
    description: undefined,
    date: "04 FEB",
    time: "4:00 PM - 7:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Archer OH" }],
    name: "Archer Oh! * Thursday Marks Fall * Last Peso",
    description: undefined,
    date: "04 FEB",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Old Time Jam Band" }],
    name: "Old Time Jam Band",
    description:
      "Join ABQ’s own The Virginia Creepers every little Monday night, right here at our Nob Hill taproom for an Old-Time jam! Bring your strings and sit in the round – or just listen to this awesome night of Old-Time music. ...",
    date: "05 FEB",
    time: "7:00 PM - 9:00 PM",
    venue: "Tractor Brewing - Knob Hill",
    address: "118 Tulane Dr SE, Albuquerque, NM",
  },
  {
    performers: [{ name: "The Hayseed Band" }],
    name: "The Hayseed Band",
    description: undefined,
    date: "05 FEB",
    time: "9:00 PM - 12:00 AM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Albuquerque Jazz Orchestra" }],
    name: "ABQ Jazz",
    description: undefined,
    date: "06 FEB",
    time: "7:00 PM - 9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Cory Wong" }],
    name: "Cory Wong featuring Monica Martin w/ special guest LA LOM",
    description: undefined,
    date: "06 FEB",
    time: "8:00 PM",
    venue: "El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Portugal The Man" }],
    name: "Portugal. The Man w/ SNACKTIME",
    description: undefined,
    date: "06 FEB",
    time: "8:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Rhyme Craft" }],
    name: "Mine Shaft Tavern",
    description: undefined,
    date: "07 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Brad Mehldau" }],
    name: "Brad Mehldau",
    description:
      "Brad Mehldau seamlessly merges elements of jazz exploration, classical romanticism, and pop magnetism. Renowned for his virtuosic piano skills, this award-winning musician unravels and reimagines melodies from artists as diverse as Radiohead, J.S. Bach, Paul Simon, Nick Drake, and more. Mehldau possesses the keen ear and musical imagination of a composer, effortlessly blending jazz and classical elements in his original compositions and commissioned works. It comes as no surprise that The New York Times has hailed him as “the most influential jazz pianist of the past two decades.” Experience the brilliance of Brad Mehldau as he takes the stage for a captivating […] ...",
    date: "07 FEB",
    time: "7:30 PM",
    venue: "Saint Francis Auditorium",
    address: "107 W Palace Ave, • Santa Fe NM",
  },
  {
    performers: [{ name: "Felix Gato Peralta" }],
    name: "Songwriter Showcase with Felix Peralta and Friends",
    description: undefined,
    date: "08 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Derangers" }],
    name: "Open Mic/Jam hosted by the Derangers",
    description: undefined,
    date: "08 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Elder" }],
    name: "Elder",
    description:
      "Elder is Nicholas DiSalvo, Jack Donovan, Michael Risberg and Georg Edert. Elder is a genre-pushing rock band that melds heavy psychedelic sounds with progressive elements and evocative soundscapes. Formed in a small coastal town in Massachusetts in the mid aughts, the band has reinvented their sound over the course of five albums to grow from a stalwart of the stoner/doom scene into one of the most unique voices in the rock underground. Their long-scale compositions unfold as journeys, running the gamut of styles from the 70’s to the present within a single song with a penchant for “sheer gatefold-era grandeur” (Rolling […] ...",
    date: "08 FEB",
    time: "7:00 PM - 11:00 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Warner" }],
    name: "Thomas Blues, J.D.Sipe, and Joe Daddy Warner",
    description: undefined,
    date: "08 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Ov Sulphur" }],
    name: "Ov Sulfur * Mental Cruelty * Ghost Bath * Extermination Dismemberment",
    description: undefined,
    date: "08 FEB",
    time: "7:30 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Zach Coffey" }],
    name: "Zach Coffey",
    description: undefined,
    date: "08 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Lori Ottino and Joe West" }],
    name: "Lori Ottino, Josh Martin & Margaret Burke",
    description: undefined,
    date: "09 FEB",
    time: "5:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Rodney Bowe2" }],
    name: "The Rodney Bowe Experience",
    description: undefined,
    date: "09 FEB",
    time: "5:30 PM - 8:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Odd Dogs" }],
    name: "Odd Dog",
    description:
      "One of the most versatile bands New Mexico has to offer! Besides performing original music, some of their influences are presented with covers by artists like Grateful Dead, Bob Dylan, Counting Crows, Mark Knopfler, Robert Hunter, Jerry Garcia, Bruce Springsteen, U2, David Byrne, Beatles, Van Morrison, and many more! ...",
    date: "09 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Westernhers" }],
    name: "The Westernhers",
    description: "The Westernhers",
    date: "09 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Dirty Brown Jug Band" }],
    name: "Dirty Brown Jug Band",
    description:
      "Raw, dirty, melodic, sonic watershed. dBjB is an evolution of musical styling, the lovechild of classic country, rock, blues and something completely new to the aural pathway. Dirty Brown Jug Band is bringing something fresh to the party and it goes down smooth. ~Git Yer Jug On~ ...",
    date: "09 FEB",
    time: "8:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Koffin Kats" }],
    name: "The Koffin Kats",
    description: "Koffin Kats * Hans Gruber and the Die Hards",
    date: "09 FEB",
    time: "8:00 PM - 12:00 AM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Twin Tribes" }],
    name: "Twin Tribes with Urban Heat * Vandal Moon",
    description: "",
    date: "09 FEB",
    time: "8:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Austin Van" }],
    name: "Austin Van",
    description:
      "New Mexico singer/songwriter and award-winning artist Austin Van is hitting the Bourbon & Boots stage for two nights this Friday & Saturday! Dust off those boots and join us on the dance floor. ...",
    date: "09 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Zach Coffey" }],
    name: "Zach Coffey",
    description: "",
    date: "09 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Jim Almand" }],
    name: "Jim Almand",
    description: "",
    date: "10 FEB",
    time: "1:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Partizini Brass Band" }],
    name: "Mardi Gras Party with Partizini Brass Band",
    description: "",
    date: "10 FEB",
    time: "2:00 PM - 5:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Trinity Soul" }],
    name: "Trinity Soul",
    description:
      "Trinity Soul pushes sonic boundaries and blurs the lines of “genre”.    This band is known to have a big sound.  Frontman “David” delivers soaring guitar leads and soulful vocals while  “Judah” provides a lush sonic landscape and funky grooves on the keyboards. Laying down the foundation with disciplined chops and impeccable timing is drummer “Jeremiah”. When you go to a Trinity Soul show expect to hear your favorite Rock, Reggae, Funk and Soul music and get ready to dance!   ...",
    date: "10 FEB",
    time: "5:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Tripple X" }],
    name: "Tripple X Band",
    description: undefined,
    date: "10 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Disclaimers" }],
    name: "Disclaimers",
    description: undefined,
    date: "10 FEB",
    time: "6:30 PM - 9:30 PM",
    venue: "Skidmores Holiday Bowl",
    address: "7515 Lomas Blvd NE, Albuquerque, NM, United ,States, New Mexico 87110",
  },
  {
    performers: [{ name: "Duke City Swamp Coolers" }],
    name: "Duke City Swamp Coolers",
    description: undefined,
    date: "10 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Delfeayo Marsalis" }],
    name: "Delfeayo Marsalis’ Uptown Jazz Orchestra",
    description:
      "NEA Jazz Master Delfeayo Marsalis brings the soul of New Orleans to Santa Fe! The Marsalis family are the most celebrated ambassadors of New Orleans’ unique jazz heritage. Following a decorated career as a sideman in bands with jazz legends like Ray Charles, Art Blakey, and Elvin Jones, Delfeayo formed his own band—the Uptown Jazz Orchestra. Playing a mix of original compositions and classic jazz songs, this lively band emphasizes important jazz traditions like riff playing and spontaneous arrangements. Celebrate Mardi Gras in style with the Uptown Jazz Orchestra! This event is part of the 2024 Art + Sol Winter […] ...",
    date: "10 FEB",
    time: "7:30 PM",
    venue: "Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "Silver Sky" }],
    name: "Silver Sky Blues Band",
    description:
      "The Silver Sky Blues Band is a new ensemble performing American traditional music in the veins of blues, rockabilly, and soul featuring band leader Julian Dossett. ...",
    date: "10 FEB",
    time: "8:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Great White/Slaughter" }],
    name: "Great White/Slaughter",
    description: undefined,
    date: "10 FEB",
    time: "8:00 PM - 9:30 PM",
    venue: "Isleta Resort & Casino - The Showroom",
    address: "11000 Broadway Blvd SE, Albuquerque, NM 87105",
  },
  {
    performers: [{ name: "Austin Van" }],
    name: "Austin Van",
    description:
      "New Mexico singer/songwriter and award-winning artist Austin Van is hitting the Bourbon & Boots stage for two nights this Friday & Saturday! Dust off those boots and join us on the dance floor. ...",
    date: "10 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Zach Coffey" }],
    name: "Zach Coffey",
    description: undefined,
    date: "10 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Electric Valentine" }],
    name: "Electric Valentine",
    description: "on the Mezzanine w/ Sweet Tooth Visuals by SCIN.TIL.LATE ...",
    date: "10 FEB",
    time: "9:00 PM",
    venue: "El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Chiaroscuro" }],
    name: "Chiaroscuro",
    description:
      "Brentano Quartet MOZART Quartet in E Major, K. 499 SHOSTAKOVICH Quartet No. 8 in C Minor, Op. 110 MENDELSSOHN Quartet in D Major, Op. 44, No. 1 Shostakovich’s intensely personal String Quartet No. 8, dedicated to the victims of fascism and war, sits in high contrast with two of the most uplifting, ebullient quartets by Mozart and Mendelssohn. ...",
    date: "11 FEB",
    time: "3:00 PM",
    venue: "Saint Francis Auditorium",
    address: "107 W Palace Ave, • Santa Fe NM",
  },
  {
    performers: [{ name: "Teenage Wrist" }],
    name: "Teenage Wrist * Glixen",
    description: undefined,
    date: "11 FEB",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Old Time Jam Band" }],
    name: "Old Time Jam Band",
    description:
      "Join ABQ’s own The Virginia Creepers every little Monday night, right here at our Nob Hill taproom for an Old-Time jam! Bring your strings and sit in the round – or just listen to this awesome night of Old-Time music. ...",
    date: "12 FEB",
    time: "7:00 PM - 9:00 PM",
    venue: "Tractor Brewing - Knob Hill",
    address: "118 Tulane Dr SE, Albuquerque, NM",
  },
  {
    performers: [{ name: "Clark Libbey" }],
    name: "Clark Libbey – Mardi Gras",
    description: "Singer/Songwriter-Albuquerque, NM Americana/Alt-country/Cajun-Zydeco ...",
    date: "13 FEB",
    time: "1:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Jim Almand" }],
    name: "Jim Almand – Mardi Gras",
    description: undefined,
    date: "13 FEB",
    time: "4:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Beer Choir" }],
    name: "Beer Choir",
    description: undefined,
    date: "13 FEB",
    time: "6:00 PM - 8:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Felix Y los Gatos" }],
    name: "Felix Y Los Gatos – Mardi Gras",
    description:
      "Felix Y Los Gatos is one of the best party bands in New Mexico. Nationally Touring. Americana, Blues ...",
    date: "13 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Roseanne Cash" }],
    name: "Rosanne Cash",
    description:
      "Rosanne Cash is a composer and singer-songwriter who has earned 4 Grammy Awards and 14 Grammy nominations, among numerous other accolades for songwriting and sound recordings.  She is also an author, whose 2010 memoir Composed garnered widespread praise from critics and landed on The New York Times bestseller list. In addition, she is a music community catalyst who often brings together giants of American roots music for various events and is a valued voice in documenting modern music history. In 2021, Cash was the first female composer to receive the MacDowell Medal, awarded since 1960 to an artist who has made an outstanding contribution to […] ...",
    date: "13 FEB",
    time: "7:30 PM - 9:00 PM",
    venue: "Kimo Theatre",
    address: "423 Central Ave. NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Coleman Williams" }],
    name: "Coleman Williams * Clyde McGee * Lightnin’ Luke",
    description: undefined,
    date: "13 FEB",
    time: "8:30 PM - 11:30 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Chachalacas" }],
    name: "Chachalacas – Valentine’s Day",
    description: undefined,
    date: "14 FEB",
    time: "6:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Poison Ruin" }],
    name: "Poison Ruïn",
    description:
      "Evoking a rich tapestry of ice-caked forests, peasant revolts, and silent knights, Poison Ruïn stab at the pulsing heart of what it means to live under the permanent midnight of contemporary life. Harvest gazes at the world with a sense of grave seriousness, its stare softened only by the alluring seduction of a dream world’s open-ended possibility. These songs move with a type of uncanny confidence, assembling an array of references to past styles and sensibilities that collapse in on one another, congealing into a truly unique sonic landscape. Poison Ruïn have constructed a fantasy world of a better future. […] ...",
    date: "14 FEB",
    time: "7:00 PM - 11:00 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Duke City Swamp Coolers" }],
    name: "Duke City Swamp Coolers",
    description: undefined,
    date: "15 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Grant Turner" }],
    name: "Grant Turner & Carson Barry",
    description: undefined,
    date: "15 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Derangers" }],
    name: "Open Mic/Jam hosted by the Derangers",
    description: undefined,
    date: "15 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Brandon Saiz Band" }],
    name: "Brandon Saiz Band",
    description: "Country Music original and cover band out of New Mexico. ...",
    date: "15 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Queen Bee" }],
    name: "Queen Bee",
    description: undefined,
    date: "16 FEB",
    time: "5:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Rodney Bowe2" }],
    name: "The Rodney Bowe Experience",
    description: undefined,
    date: "16 FEB",
    time: "5:30 PM - 8:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "7000 Feat" }],
    name: "7000 Feat",
    description: undefined,
    date: "16 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "spiral pilot" }],
    name: "Spiral Pilots",
    description: undefined,
    date: "16 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Dani-Rae Clark & The Let Downs" }],
    name: "Dani-Rae Clark & The Let Downs",
    description: undefined,
    date: "16 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Brandon Saiz Band" }],
    name: "Brandon Saiz Band",
    description: "Country Music original and cover band out of New Mexico. ...",
    date: "16 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Ganzalo" }],
    name: "Gonzalo",
    description: undefined,
    date: "16 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Odd Dog" }],
    name: "Odd Dog",
    description: undefined,
    date: "17 FEB",
    time: "2:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Chillhouse" }],
    name: "ChillHouse & Hillary Smith",
    description: undefined,
    date: "17 FEB",
    time: "5:30 PM - 8:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Iron Chiwawa" }],
    name: "Iron Chiwawa",
    description: undefined,
    date: "17 FEB",
    time: "6:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Cooper Alan" }],
    name: "Cooper Alan",
    description: undefined,
    date: "17 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Rock Zone" }],
    name: "Rock Zone",
    description: undefined,
    date: "17 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Tornillo" }],
    name: "Tornillo * Dharius",
    description: undefined,
    date: "17 FEB",
    time: "8:00 PM - 12:00 AM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Ganzalo" }],
    name: "Gonzalo",
    description: undefined,
    date: "17 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Clark Libbey" }],
    name: "Clark Libbey",
    description: "Singer/Songwriter-Albuquerque, NM Americana/Alt-country/Cajun-Zydeco ...",
    date: "18 FEB",
    time: "2:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "The Glenn Miller Orchestra" }],
    name: "Glenn Miller Orchestra",
    description:
      "With its unique sound, The Glenn Miller Orchestra earned its spot as one of the greatest bands of all time. In the early 1940s, the ensemble produced some of the most popular songs of their day, creating a soundtrack for the Greatest Generation. Now, this celebrated group returns to perform some of their biggest hits including “A String of Pearls,” “In the Mood,” and “Moonlight Serenade.” Swing to the music of this big band! ...",
    date: "18 FEB",
    time: "3:00 PM",
    venue: "Popejoy Hall",
    address: "203 Cornell Dr, Albuquerque, NM 87131",
  },
  {
    performers: [{ name: "Le Chat Lunatique" }],
    name: "Le Chat Lunatique",
    description: undefined,
    date: "18 FEB",
    time: "4:00 PM - 7:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "American Classics" }],
    name: "American Classics",
    description:
      "Recipient of a Borletti-Buitoni Trust Award and an Avery Fisher Career Grant, violinist Alexi Kenney was named “a talent to watch” by The New York Times. He has earned widespread acclaim across the globe and returns to Santa Fe to perform Barber’s Violin Concerto No. 1 for “American Classics.” The program also features Leonard Bernstein’s Chichester Psalms with The Symphony Chorus, “Four Dance Episodes” from Aaron Copland’s Rodeo, and Gala Flagello’s Vitality. Presented as part of the Art + Sol Santa Fe Winter Arts Festival.     ...",
    date: "18 FEB",
    time: "4:00 PM",
    venue: "Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "The Surfrajettes" }],
    name: "The Surfrajettes",
    description:
      "What’s thicker, our eyeliner or our guitar strings? The Surfrajettes are a four-piece instrumental combo from Toronto, ON, Canada. Since forming in late 2015, the band has charmed audiences with their clever mix of psychedelic rock and reverb-drenched surf music, sky-high beehives, go-go boots, and eyeliner as thick as their guitar strings. The band achieved viral online notoriety from their home-made performance videos and their feature by Norman’s Rare Guitars in LA. The debut 45 single “Party Line / Toxic” released late 2018 on Hi-Tide Recordings to immediate success. The band has toured extensively in its support, including performances on […] ...",
    date: "18 FEB",
    time: "7:00 PM - 10:30 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Old Time Jam Band" }],
    name: "Old Time Jam Band",
    description:
      "Join ABQ’s own The Virginia Creepers every little Monday night, right here at our Nob Hill taproom for an Old-Time jam! Bring your strings and sit in the round – or just listen to this awesome night of Old-Time music. ...",
    date: "19 FEB",
    time: "7:00 PM - 9:00 PM",
    venue: "Tractor Brewing - Knob Hill",
    address: "118 Tulane Dr SE, Albuquerque, NM",
  },
  {
    performers: [{ name: "Justin Adams and Mauro Durante" }],
    name: "Justin Adams and Mauro Durante",
    description:
      "AMP Concerts Presents Justin Adams and Mauro Durante at FUSION | 708 Justin Adams, guitarist, producer, and composer, has been a creator of wonders with Robert Plant in the Sensational Space Shifters. His production on landmark albums by Tinariwen and Rachid Taha highlights his feel for North African groove, while his award-winning collaborations with Juldeh Camara linked griot tradition with raw blues spirit. His work with artists such as Jah Wobble and Sinead O’Connor was infused with the spirit of post-punk London, while his solo guitar album Ribbons was cited by Songlines magazine among the top 50 albums of the […] ...",
    date: "19 FEB",
    time: "7:30 PM - 11:00 PM",
    venue: "Fusion | 708",
    address: "708 1st St. NW, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Crypta" }],
    name: "CRYPTA",
    description: undefined,
    date: "20 FEB",
    time: "8:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Govt Mule" }],
    name: "Gov’t Mule – 30 Years Strong",
    description:
      "Get ready, Albuquerque – mark your calendars for Wednesday, February 21, 2024, because Gov’t Mule is bringing the groove to town! Don’t miss this epic night of rock and roll! AMP Concerts Presale begins Wednesday, October 11 at 10am through Friday, October 13, 10am Presale Promo Code: AMPMULE ...",
    date: "21 FEB",
    time: "7:30 PM",
    venue: "Kiva Auditorium",
    address: "401 2nd St NW, Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Silver Sky" }],
    name: "Silver Sky Blues Band",
    description:
      "The Silver Sky Blues Band is a new ensemble performing American traditional music in the veins of blues, rockabilly, and soul featuring band leader Julian Dossett. ...",
    date: "22 FEB",
    time: "6:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Machine Head" }],
    name: "Machine Head – Slaughter The Martour with Fear Factory * Orbit Culture * Gates To Hell",
    description: undefined,
    date: "22 FEB",
    time: "6:30 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Keith Bernstien" }],
    name: "KEITH BURNSTEIN",
    description:
      "Keith Burnstein is a singer-songwriter, pianist, and film composer who pens timeless tunes. His is a new American songbook that draws as much from Tin Pan Alley as it does from modern geniuses like Jeff Tweedy, Amon Tobin, and Mose Allison. “The songs, while instantly familiar, remain very much their own creations” (Secret Sound Shop),  “combining the bedroom intimacy of a singer-songwriter” (Seven Days VT) with the rich harmonic palette of jazz, electronic, and “world” music. ...",
    date: "22 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Derangers" }],
    name: "Open Mic/Jam hosted by the Derangers",
    description: undefined,
    date: "22 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Terence Blanchard" }],
    name: "Terence Blanchard, E-Collective, and Turtle Island String Quartet",
    description:
      "“Blanchard told one scribe, ‘Music and art have the power to change hearts and souls.’ That sums up his social and spiritual mission.” – Dan Oulette Terence Blanchard and his acclaimed collaborators pay tribute to iconic jazz composer Wayne Shorter. Blanchard reimagines songs from across and inspired by Shorter’s adventurous catalog, resulting in what the New Yorker called “a lush and dramatic soundscape that calls to mind Blanchard’s career as a successful film composer.” The group’s 2022 album, Absence, in tribute to Shorter, was nominated for two Grammy Awards—Best Jazz Instrumental Album and Best Jazz Improvised Album. Terence Blanchard has been a consistent […] ...",
    date: "22 FEB",
    time: "7:30 PM",
    venue: "Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "Abe Mac" }],
    name: "Abe Mac Band",
    description: undefined,
    date: "22 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Dusty the Kid" }],
    name: "Dusty the Kid and Dirty Laundry",
    description: undefined,
    date: "23 FEB",
    time: "5:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Trinity Soul" }],
    name: "Trinity Soul",
    description:
      "Trinity Soul pushes sonic boundaries and blurs the lines of “genre”.    This band is known to have a big sound.  Frontman “David” delivers soaring guitar leads and soulful vocals while  “Judah” provides a lush sonic landscape and funky grooves on the keyboards. Laying down the foundation with disciplined chops and impeccable timing is drummer “Jeremiah”. When you go to a Trinity Soul show expect to hear your favorite Rock, Reggae, Funk and Soul music and get ready to dance!   ...",
    date: "23 FEB",
    time: "5:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "The Secret 7 Acoustic Duo" }],
    name: "The Secret 7 Acoustic Duo",
    description: undefined,
    date: "23 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Terrry Winchell & The Fine Line" }],
    name: "Terry Winchell & The Fine Line",
    description: undefined,
    date: "23 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Judith Hill" }],
    name: "Judith Hill",
    description:
      "Judith Hill has been praised by Rolling Stone for her “stellar powerhouse vocals.” Her music is rich in throwback soul, stunning piano balladry, and swaggering psychedelic funk. Having worked with Prince and Michael Jackson and been featured in the acclaimed documentary 20 Feet from Stardom, Hill’s set will both glue you to the back of your seat and have you dancing in the aisles. On her latest LP, Baby, I’m Hollywood, Judith Hill unveils an ambitious, kaleidoscopic document detailing her journey of self-discovery. It’s a vibrant, defiant personal statement and a thorough excursion into the annals of Black music: past, present, and future. Bolstered by […] ...",
    date: "23 FEB",
    time: "7:30 PM",
    venue: "Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "Free Range Buddhas" }],
    name: "Free Range Buddhas",
    description: "",
    date: "23 FEB",
    time: "8:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Abe Mac" }],
    name: "Abe Mac Band",
    description: undefined,
    date: "23 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Black Pearl" }],
    name: "Black Pearl Band",
    description: undefined,
    date: "23 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Iron Chiwawa" }],
    name: "Iron Chiwawa",
    description: undefined,
    date: "24 FEB",
    time: "2:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Park Twenty-One" }],
    name: "Park Twenty-One",
    description: undefined,
    date: "24 FEB",
    time: "5:30 PM - 8:30 PM",
    venue: "Canvas Artistry Restaurant & Art Bar",
    address: "1 Central Ave NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Felix Y los Gatos" }],
    name: "Felix Y Los Gatos",
    description:
      "Felix y Los Gatos is a national touring act with their roots planted firmly in the desert Southwest. With 20+ years of stage experience, the Gatos have an improvisational style that is uniquely their own. “Green Chile Gumbo” Blues, as the band refers to their sound, is a unique blend of Latin, Blues, Tejano, New Orleans Swing, “New Mexico Ranchera”, and rockin’ outlaw country. ...",
    date: "24 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Josh Ward" }],
    name: "Josh Ward",
    description: undefined,
    date: "24 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "The Roswells" }],
    name: "The Roswells",
    description: undefined,
    date: "24 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Renée Elise Goldsberry" }],
    name: "Renée Elise Goldsberry",
    description:
      "Star of stage and screen, Tony Award®-winning actress and singer Renée Elise Goldsberry visits Popejoy Hall! Best known for originating the role of Angelica Schuyler in Hamilton, her Broadway career began as Nala in The Lion King. She later performed as Mimi in Broadway’s closing cast of RENT. Recently, she’s starred on the small screen in She Hulk, Girls5Eva and Altered Carbon. As a solo artist, she wows audiences with her talent and her stage presence garnering rave reviews. In this special solo performance, in addition to some of Renee’s most beloved Broadway classics, she also performs soulful renditions of American Songbook hits that are sure to be recognized by young […] ...",
    date: "24 FEB",
    time: "7:30 PM",
    venue: "Popejoy Hall",
    address: "203 Cornell Dr, Albuquerque, NM 87131",
  },
  {
    performers: [{ name: "OPERATION REWIND" }],
    name: "OPERATION REWIND",
    description: undefined,
    date: "24 FEB",
    time: "8:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Evan Dando" }],
    name: "Evan Dando",
    description: undefined,
    date: "24 FEB",
    time: "8:00 PM - 12:00 AM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Abe Mac" }],
    name: "Abe Mac Band",
    description: undefined,
    date: "24 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Black Pearl" }],
    name: "Black Pearl Band",
    description: undefined,
    date: "24 FEB",
    time: "9:00 PM",
    venue: "First Turn Lounge",
    address: "145 Louisiana Blvd. NE Albuquerque, NM 87108",
  },
  {
    performers: [{ name: "Julian Dossett" }],
    name: "Julian Dossett",
    description: undefined,
    date: "25 FEB",
    time: "2:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Groundbreaking" }],
    name: "Groundbreaking!",
    description:
      "HAYDN Quartet in G Major, Op. 54, No. 1 STRAVINSKY Three Pieces for String Quartet BEETHOVEN Quartet in E Minor, Op. 59, No. 2 Groundbreaking compositions that altered the trajectory of the string quartet. “Poetic, charismatic and virtuosic, this immensely talented string quartet has the rare quality of unforced spontaneity.”—Sunday Telegraph, London ...",
    date: "25 FEB",
    time: "3:00 PM",
    venue: "Saint Francis Auditorium",
    address: "107 W Palace Ave, • Santa Fe NM",
  },
  {
    performers: [{ name: "Hello Darlin" }],
    name: "Hello Darlin and Pawn Drive",
    description:
      "Hello Darlin’ is a 3 piece Albuquerque band playing mostly original Americana music. The band features songwriter Bernie King on vocals and guitar, Julie King plays accordion and washboard and Carl Petersen rounds out the trio on bass. Their shows are a delicious musical stew served up with a mix of blues, bluegrass, folk, rock, and the kitchen sink ...",
    date: "25 FEB",
    time: "4:00 PM - 7:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Juanita" }],
    name: "Juanita",
    description:
      "Juanita is a band from in and around Albuquerque, New Mexico. Featuring Murocco on guitar, Debo Orlofsky on accordion, Terry Booze on bass, and Zoom on drums, Juanita plays desert zydeco blues: roots rockers, blues burners, and zydeco stompers! ...",
    date: "25 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Rock Canyon Taproom",
    address: "364 NM-333, Tijeras, NM 87059",
  },
  {
    performers: [{ name: "Ariel Pink" }],
    name: "Ariel Pink",
    description: undefined,
    date: "25 FEB",
    time: "8:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "The Green" }],
    name: "The Green with Mike Love",
    description: undefined,
    date: "25 FEB",
    time: "8:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Old Time Jam Band" }],
    name: "Old Time Jam Band",
    description:
      "Join ABQ’s own The Virginia Creepers every little Monday night, right here at our Nob Hill taproom for an Old-Time jam! Bring your strings and sit in the round – or just listen to this awesome night of Old-Time music. ...",
    date: "26 FEB",
    time: "7:00 PM - 9:00 PM",
    venue: "Tractor Brewing - Knob Hill",
    address: "118 Tulane Dr SE, Albuquerque, NM",
  },
  {
    performers: [{ name: "Grieves" }],
    name: "Grieves",
    description: undefined,
    date: "27 FEB",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Sona Jobarteh" }],
    name: "Sona Jobarteh",
    description:
      "Sona Jobarteh is the first professional female Kora virtuoso to come from any of the West African Griot dynasties. Her lineage carries a formidable reputation for renowned Kora masters, most notable amongst these are her grandfather Amadu Bansang Jobarteh and her cousin, the legendary Toumani Diabaté. Sona is reputed for her skill as an instrumentalist, her distinctive voice, infectious melodies and her grace onstage, and she has rapidly achieved international success as a top class performer. The demand for Sona Jobarteh’s live performances has rocket in recent years, and 2019 saw her perform at some of the world’s most renowned festivals […] ...",
    date: "28 FEB",
    time: "7:30 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Jer" }],
    name: "JER w/ Devon Kay & The Solutions + Suzie True + Thursday Marks Fall",
    description: undefined,
    date: "28 FEB",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "John 5" }],
    name: "John 5 and The Creatures",
    description: "plus special guests Marty Friedman ...",
    date: "28 FEB",
    time: "8:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Hillary Smith & ChillHouse featuring The City Horns" }],
    name: "Hillary Smith & The ChillHouse",
    description:
      "ChillHouse was created by  guitarist of the legendary, Dallas, Texas-Buster Brown Band, Jim Casey, along with these Albuquerque based and beloved players, bassist, Robert “Milo” Jaramillo, saxophonist, Glenn Kostur and drummer JD Davis. Powerhouse blues originals, throwback soul and all things funky has secured them a loyal fan base in Albuquerque and Santa Fe. ChillHouse is fronted  by Albuquerque’s own award-winning vocalist/songwriter  and 2021 New Mexico Hall of Famer, soul queen, Hillary Smith.     ...",
    date: "29 FEB",
    time: "6:00 PM - 9:00 PM",
    venue: "Canteen Brewhouse",
    address: "2381 Aztec NE, Albuquerque, NM 87107",
  },
  {
    performers: [{ name: "Mine Shaft Tavern" }],
    name: "Open Mic with Stephen Pitts",
    description: undefined,
    date: "29 FEB",
    time: "7:00 PM",
    venue: "Mineshaft Tavern",
    address: "Hwy 14, Madrid NM",
  },
  {
    performers: [{ name: "Derangers" }],
    name: "Open Mic/Jam hosted by the Derangers",
    description: undefined,
    date: "29 FEB",
    time: "7:00 PM",
    venue: "The Range Cafe - Bernalillo",
    address: "925 Camino Del Pueblo, Bernalillo, NM 87004",
  },
  {
    performers: [{ name: "Reverend Horton Heat" }],
    name: "Reverend Horton Heat",
    description:
      "Loaded guns, space heaters, and big skies. Welcome to the lethal littered landscape of Jim Heath’s imagination. True to his high evangelical calling, Jim is a Revelator, both revealing & reinterpreting the country-blues-rock roots of American music. He’s a time-travelling space-cowboy on a endless interstellar musical tour, and we are all the richer & “psychobillier” for getting to tag along. Seeing REVEREND HORTON HEAT live is a transformative experience. Flames come off the guitars. Heat singes your skin. There’s nothing like the primal tribal rock & roll transfiguration of a Reverend Horton Heat show. Jim becomes a slicked-back 1950’s rock […] ...",
    date: "29 FEB",
    time: "7:00 PM - 10:30 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Donavon Frankenreiter" }],
    name: "Donavon Frankenreiter",
    description:
      "Lensic 360 Presents Donavon Frankenreiter For nearly four decades Donavon Frankenreiter has been travelling the globe, first as a professional surfer and now as a musician. Born in Southern California, Donavon spent most of his youth chasing waves, turning pro at the age of 16. These days instead of surf competitions, it’s concert halls that brings Frankenreiter to town, where he entertains audiences with his unique blend of laid-back grooves, philosophical lyrics and soulful delivery. You can find him touring the world with his three-piece band and still catching waves anytime he can. ...",
    date: "29 FEB",
    time: "7:30 PM - 11:00 PM",
    venue: "Fusion | The Cell",
    address: "700 1st Street NorthwestAlbuquerque, NM, 87102",
  },
  {
    performers: [{ name: "Jeremy Studdard" }],
    name: "Jeremy Studdard",
    description: undefined,
    date: "29 FEB",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "The TEN Tenors" }],
    name: "The TEN Tenors",
    description:
      "Ten tenors. Tons of talent. Renowned for their dynamic arrangements of classic and contemporary favorites, this must-see musical ensemble returns to sing their greatest hits. Direct from Australia, the group has wowed audiences around the world. From “Bohemian Rhapsody” to “Nessun Dorma,” The TEN Tenors always perform in perfect harmony. ...",
    date: "01 MAR",
    time: "7:30 PM - 10:00 PM",
    venue: "Popejoy Hall",
    address: "203 Cornell Dr, Albuquerque, NM 87131",
  },
  {
    performers: [{ name: "Taj Mahal Quartet" }],
    name: "Taj Mahal Quartet and Sona Jobarteh",
    description:
      "Taj Mahal is a towering musical figure—a legend who transcended the blues not by leaving them behind, but by revealing their magnificent scope to the world. A 2017 Grammy win for TajMo, Taj’s collaboration with Keb’ Mo’, brought his Grammy tally to three wins and fourteen nominations, and underscored his undiminished relevance more than 50 years after his solo debut. Blues Hall of Fame membership, a Lifetime Achievement Award from the Americana Music Association, and other honors punctuate his résumé. Taj appreciates the accolades, but his motivation lies elsewhere. “I just want to be able to make the music that I’m […] ...",
    date: "01 MAR",
    time: "7:30 PM",
    venue: "Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "Jeremy Studdard" }],
    name: "Jeremy Studdard",
    description: undefined,
    date: "01 MAR",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "KRS one" }],
    name: "KRS-One",
    description:
      "Appearing on the rap scene in 1986 as Boogie Down Productions releasing his first hit single “South Bronx” with his late DJ Scott La Rock, KRS “the one” made it clear that Hip Hop was going to have to take itself a lot more seriously than simply being a music genre. KRS, an acronym for ““Knowledge Reigning Supreme”, has been called the “conscience of Hip Hop” (Rolling Stone), “the greatest live emcee ever” (The Source), the “spokesperson for Hip Hop” (Wall Street Journal), “master teacher” (Zulu Nation) and the “son of Hip Hop” (Kool DJ Herc). With 20 published albums […] ...",
    date: "02 MAR",
    time: "7:00 PM - 12:00 AM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Sleater Kinney" }],
    name: "SLEATER-KINNEY – Little Rope Tour",
    description:
      "Sleater-Kinney, American rock band that arose from the feminist punk rock movement known as “riot grrrl” and was acclaimed for recordings that combined a lean and aggressive sound with passionate socially conscious lyrics. ...",
    date: "02 MAR",
    time: "8:00 PM",
    venue: "El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Jeremy Studdard" }],
    name: "Jeremy Studdard",
    description: undefined,
    date: "02 MAR",
    time: "9:00 PM",
    venue: "Dirty Bourbon Dance Hall & Saloon",
    address: "9800 Montgomery Blvd Albuquerque, NM, 87111",
  },
  {
    performers: [{ name: "Little Stranger" }],
    name: "LITTLE STRANGER & DENM w/ Bikini Trill",
    description: undefined,
    date: "03 MAR",
    time: "7:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Video Age" }],
    name: "Video Age w/ Mind Shrine",
    description:
      "Video Age make breezy and timeless songs that are so ineffable, they can only be the result of a decades-long friendship and songwriting partnership. Across four albums, Ross Farbe and Ray Micarelli have gleefully worn their influences on their sleeve, writing inviting tunes that reference sounds ranging from disco to pop and indie rock. On their latest LP, Away From The Castle, the New Orleans duo have strayed from nostalgia and instead have honed their own unique sense of musicality, making organic songs that sound like themselves with a taste of inspiration from classic singer-songwriters of the 60s and 70s. […] ...",
    date: "03 MAR",
    time: "7:00 PM - 11:00 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Mania the Abba TRibute" }],
    name: "Mania: The Abba Tribute",
    description:
      "ake A Chance On MANIA……and you won’t be disappointed! This year the iconic Swedish pop group, is celebrating the 50th anniversary of their breakthrough hit single “Waterloo” and MANIA can’t wait to share the joy of this huge milestone! Mania the ABBA Tribute has successfully toured every continent in the world and has played over 3,000 live concerts in over 35 countries. Recent highlights included a second run in London’s West End where the show performed for a month in the iconic Shaftesbury Theatre, London in May 2021. The show also enjoyed an 80 date sell-out USA National tour in 2022/2023, Mania continues in its quest […] ...",
    date: "03 MAR",
    time: "7:30 PM - 9:00 PM",
    venue: "Kimo Theatre",
    address: "423 Central Ave. NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "The Ocean" }],
    name: "The Ocean",
    description:
      "with The World Is A Beautiful Place & I Am No Longer Afraid To Die * Shy, Low ...",
    date: "03 MAR",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Old Time Jam Band" }],
    name: "Old Time Jam Band",
    description:
      "Join ABQ’s own The Virginia Creepers every little Monday night, right here at our Nob Hill taproom for an Old-Time jam! Bring your strings and sit in the round – or just listen to this awesome night of Old-Time music. ...",
    date: "04 MAR",
    time: "7:00 PM - 9:00 PM",
    venue: "Tractor Brewing - Knob Hill",
    address: "118 Tulane Dr SE, Albuquerque, NM",
  },
  {
    performers: [{ name: "Health" }],
    name: "HEALTH with Pixel Grip & King Yosef",
    description:
      "Health (often stylized as HEALTH) is an American noise rock/industrial band from Los Angeles, California. The band currently consists of drummer BJ Miller, vocalist and guitarist Jake Duzsik, and bassist and producer John Famiglietti. ...",
    date: "05 MAR",
    time: "8:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Benjamin-Grosvenor" }],
    name: "Benjamin Grosvenor, Piano",
    description:
      "Pianist Benjamin Grosvenor is truly “one in a million” (The Independent). He first achieved prominence in 2004 as the youngest-ever winner of the keyboard section of the BBC’s Young Musician of the Year Competition at age 11. Now a storied performer of international acclaim, he has taken his place as one of today’s most exceptional musicians, whose virtuosic interpretations are underpinned by a unique balance of technical mastery and intense musicality. Benjamin Grosvenor will perform gorgeous selections from Lizst and Chopin, with an enthralling twentieth-century twist from Soviet-Russian composer Sofia Gubaidulina. Sofia Gubaidulina: Chaconne (1962) Chopin: Sonata No. 2 in B-flat minor, […] ...",
    date: "06 MAR",
    time: "7:30 PM",
    venue: "Saint Francis Auditorium",
    address: "107 W Palace Ave, • Santa Fe NM",
  },
  {
    performers: [{ name: "Boogarins" }],
    name: "Boogarins x Levitation Room",
    description:
      "Boogarins Initially a lo-fi project from Goiânia, land of the Sertanejo (Brazil’s country music), Boogarins have become one of the most celebrated Brazilian rock acts internationally: charming audiences around the world with intense performances, immersed in textures and guided by improvisations that transcend the language barrier. The group began its journey in 2013 on the underground stages of their hometown Goiânia, when they released their first EP As Plantas Que Curam. It caught the ear of US label Fat Possum/Other Music who re-released the group’s home-recorded debut later that year, earning positive reviews in the New York Times, Pitchfork, Chicago […] ...",
    date: "08 MAR",
    time: "7:00 PM - 11:30 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Tina Turner" }],
    name: "PROUD TINA: The Ultimate Tribute To Tina Turner",
    description:
      "Get the electrifying concert experience of Tina Turner, brimming with Tina hits from the 60s, 70s, 80s & 90s. The powerful raspy vocals, high-intensity dancing and thrilling stage presence live on stage, plus band, brass section, backing vocalists and dancers, making this the definitive tribute and a fabulous night out! ...",
    date: "08 MAR",
    time: "7:30 PM",
    venue: "Popejoy Hall",
    address: "203 Cornell Dr, Albuquerque, NM 87131",
  },
  {
    performers: [{ name: "WAR" }],
    name: "WAR",
    description: undefined,
    date: "08 MAR",
    time: "8:00 PM - 9:30 PM",
    venue: "Isleta Resort & Casino - The Showroom",
    address: "11000 Broadway Blvd SE, Albuquerque, NM 87105",
  },
  {
    performers: [{ name: "Lotus Sound Bath" }],
    name: "Experience A Lotus Sound Bath with Douglas Cardwell",
    description:
      "Unplug and immerse yourself with a Lotus Sound Bath performed by Douglas Cardwell, designed to relax the body, clear the mind, and uplift the spirit as you navigate towards the light of the approaching spring. Guests will enjoy a unique meditative concert—an instrumental experience that is both auditory and physical—performed by a music professional and certified sound bath practitioner using crystal singing bowls, gongs, cymbals, and other high-vibrational resonant instruments in the spacious and comfortable surroundings of FUSION | 708. As you lie comfortably, waves of sound will release tension throughout the body and soothing melodies will slow the mind […] ...",
    date: "09 MAR",
    time: "6:30 PM - 7:30 PM",
    venue: "Fusion | 708",
    address: "708 1st St. NW, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Kendra Morris" }],
    name: "Kendra Morris",
    description:
      "There’s something undeniably out-of-time about both Kendra Morris and her indelibly cool new album I Am What I’m Waiting For (Karma Chief Records). It combines rough-hewn powerhouse vocals with arrangements that betray both an extensive record collection and a whimsical instinct for joyous noises — think Dusty Springfield fronting Spoon circa Kill The Moonlight or a 60s girl group creative directed by Nick Lowe and PeeWee Herman. It’s vibrant and varied and packed with personality. “How do you put yourself into a record? Torbitt and I wanted to make it feel like you cracked open the ooze in my head,” […] ...",
    date: "09 MAR",
    time: "7:00 PM - 11:30 PM",
    venue: "Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "The Kills" }],
    name: "The Kills – God Games Tour with Heartworms",
    description: undefined,
    date: "11 MAR",
    time: "8:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Night Lovell" }],
    name: "Night Lovell w/ HAARPER & GERM",
    description: undefined,
    date: "12 MAR",
    time: "7:00 PM",
    venue: "Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Flogging Molly" }],
    name: "Flogging Molly – Road To Rebellion Tour",
    description: undefined,
    date: "* Flogging Molly * Amigo The Devil * Gen and the ",
    time: "Degenerates * Road To Rebellion Tour ...",
    venue: "13 MAR",
    address: "8:00 PM",
  },
  {
    performers: [{ name: "Hockey Dad" }],
    name: "Hockey Dad with Mind’s Eye",
    description: undefined,
    date: "15 MAR",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Kansas" }],
    name: "Kansas: Another Fork in the Road – 50th Anniversary Tour",
    description:
      "** NEW DATE ANNOUNCED: The originally scheduled performance at the Kiva Auditorium for Friday, September 22, 2023, is being rescheduled for Saturday, March 16, 2024. Keep your tickets! Tickets for the original date will be honored for the new concert date. For those needing a refund, please contact your original point of purchase. We appreciate your understanding through this difficult time. Carry on. ** KANSAS 50th Anniversary Tour – Another Fork in the Road will showcase music spanning all 50 years of the band’s illustrious history. The tour will showcase two hours of hits, fan favorites, and deep cuts rarely performed live. With a […] ...",
    date: "16 MAR",
    time: "7:00 PM",
    venue: "Kiva Auditorium",
    address: "401 2nd St NW, Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Lunasa" }],
    name: "Lúnasa",
    description:
      "Celebrate St. Patrick’s Day with the hottest Irish acoustic group on the planet, Lúnasa. Returning by popular demand for the second year in a row, this “Irish music dream team” (Folk Roots) sold out their show last season—so get your tickets early and come dressed in green for the best Celtic party you’ll ever have. Named for an ancient Celtic harvest festival in honor of the Irish god Lugh, patron of the arts, Lúnasa is indeed a gathering of some of the top musical talents in Ireland. Its members have helped form the backbone of some of the greatest Irish […] ...",
    date: "16 MAR",
    time: "7:30 PM",
    venue: "Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "Circle Jerks" }],
    name: "Circle Jerks * Descendents with Adolescents",
    description: undefined,
    date: "16 MAR",
    time: "8:00 PM",
    venue: "El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Mariah" }],
    name: "Mariah The Scientist TO BE EATEN ALIVE TOUR",
    description:
      "Mariah the Scientist is an R&B singer-songwriter who first began releasing music in the 2010s. ∙ Atlanta native Mariah Buckles started writing music while studying biology at St. ...",
    date: "20 MAR",
    time: "8:00 PM",
    venue: "El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Eyes set to Kill" }],
    name: "Eyes Set To Kill ‘Reach’ 15 Year Anniversary Tour",
    description: "with Reddstar * Lightworker ...",
    date: "21 MAR",
    time: "8:00 PM - 11:00 PM",
    venue: "Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Tower of Power" }],
    name: "Tower of Power 55 Years of Funk & Soul",
    description: undefined,
    date: " 23 MAR",
    time: "8:00 PM - 9:30 PM",
    venue: " Isleta Resort & Casino - The Showroom",
    address: "11000 Broadway Blvd SE, Albuquerque, NM 87105",
  },
  {
    performers: [{ name: "Zosa" }],
    name: "Zoso The Ultimate Led Zeppelin Experience",
    description: undefined,
    date: "23 MAR",
    time: "8:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Teenage BottleRocket" }],
    name: "Teenage Bottlerocket * Authority Zero * Prairie Dawg",
    description: "8th Annual Brandon Bday Bash Tour ...",
    date: "24 MAR",
    time: "8:00 PM - 11:00 PM",
    venue: " Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Hippy Sabotage" }],
    name: "Hippie Sabotage Enter the Unknown Tour",
    description: undefined,
    date: "25 MAR",
    time: "8:00 PM",
    venue: " El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Brutus" }],
    name: "Brutus",
    description: undefined,
    date: "27 MAR",
    time: "8:00 PM - 11:30 PM",
    venue: " Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Kublai" }],
    name: "Kublai Khan TX with Sunami * Judiciary * Momentum",
    description: undefined,
    date: "27 MAR",
    time: "8:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "A Tribute To Patsy, Loretta, And Dolly" }],
    name: "Trailblazing Women Of Country: A Tribute To Patsy, Loretta, And Dolly",
    description:
      "Patsy Cline, Loretta Lynn, and Dolly Parton revolutionized country music and blazed a trail for future generations of female artists. Through their voices and artistry, they proved that women can be at once beautiful and strong, vulnerable and powerful. Their success earned them each a place in the Country Music Hall of Fame. In this loving tribute, soloist Miko Marks, CMT’s 2022 “Next Woman of Country,” and Nashville-based singer Kristina Train perform the hits of Patsy, Loretta, and Dolly with heart and soul. ...",
    date: "29 MAR",
    time: "7:30 PM",
    venue: " Popejoy Hall",
    address: "203 Cornell Dr, Albuquerque, NM 87131",
  },
  {
    performers: [{ name: "Video Age" }],
    name: "Video Age",
    description: "Video Age make breezy and timeless songs that are so ineffable. ...",
    date: "30 MAR",
    time: "7:00 PM - 11:00 PM",
    venue: " Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "DRUM TAO" }],
    name: "DRUM TAO",
    description:
      "Audience- favorite DRUM TAO returns to Popejoy for another unforgettable performance. With a samurai heart and signature rock and roll aesthetic, these highly-trained musicians meld traditional Japanese drumming and martial arts mastery. Their stunning power and precision will rock you to your core. ...",
    date: "30 MAR",
    time: "7:30 PM",
    venue: " Popejoy Hall",
    address: "203 Cornell Dr, Albuquerque, NM 87131",
  },
  {
    performers: [{ name: "Los Angeles Azules" }],
    name: "Los Angeles Azules: El Amor De Mi Vida USA Tour 2024",
    description:
      "LOS ÁNGELES AZULES REVIVE THE MAGIC OF CUMBIA IN THE UNITED STATES WITH ‘EL AMOR DE MI VIDA USA TOUR 2024’ Los Ángeles Azules, with over four decades of career, have successfully established themselves as an undeniable benchmark in modern cumbia. Hailing from Mexico City, their unmistakable style and enduring energy have allowed them to stay at the forefront of the music scene throughout the years. Los Ángeles Azules are gearing up to take their show to the United States once again with the ‘EL AMOR DE MI VIDA USA TOUR 2024’ with a stop in at Kiva Auditorium in […] ...",
    date: "30 MAR",
    time: "8:00 PM",
    venue: " Kiva Auditorium",
    address: "401 2nd St NW, Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Selena Tribute" }],
    name: "Selena Tribute",
    description: undefined,
    date: " 30 MAR",
    time: "8:00 PM - 9:30 PM",
    venue: " Isleta Resort & Casino - The Showroom",
    address: "11000 Broadway Blvd SE, Albuquerque, NM 87105",
  },
  {
    performers: [{ name: "bar italia" }],
    name: "bar italia",
    description: "bar italia is a London-based band ...",
    date: "01 APR",
    time: "7:00 PM - 10:00 PM",
    venue: " Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "sleepytime Gorilla Museum" }],
    name: "Sleepytime Gorilla Museum",
    description:
      "Sleepytime Gorilla Museum formed in 1999 in Oakland, California, United States. The band was founded by Nils Frykdahl (guitars, flutes, vocals) and Dan Rathbun (bass, log, trombone, lute, vocals) of the band Idiot Flesh, with Carla Kihlstedt (violins, percussion guitar, autoharp, organ, bulbul, vocals) of Tin Hat Trio, 2 Foot Yard and The Book of Knots, after the three worked together in Charming Hostess. Matthias Bossi (drums, glockenspiel, xylophone, vocals) and Michael Mellender (percussion, assorted melodic instruments, vocals) both joined in 2004. Previous members include percussionist Moe! Staiano, founding drummer David Shamrock, and drummer/manager Frank Grau.   The band tour […] ...",
    date: "02 APR",
    time: "7:00 PM - 11:00 PM",
    venue: " Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Drum Tao" }],
    name: "Drum Tao",
    description:
      "Combining highly physical, large-scale drumming with contemporary costumes, precise choreography, and innovative visuals, the performers of Drum Tao deliver an edge-of-your-seat, tour-de-force evening of strength and driving rhythms. Established in 1993, with the dream of creating the best show in the world using Wadaiko (Japanese drums), an instrument that has a very rare and unique variety of sound expressions. Drum Tao set their base in Oita, Japan, and started creating their own music, stage set-ups, and costumes to produce their unique world of entertainment. ...",
    date: "02 APR",
    time: "7:30 PM",
    venue: " Lensic Performing Arts Center",
    address: "211 W. San Francisco Street Santa Fe, New ,Mexico 87501",
  },
  {
    performers: [{ name: "Los Lonely Boys" }],
    name: "Los Lonely Boys",
    description: undefined,
    date: " 05 APR",
    time: "8:00 PM - 9:30 PM",
    venue: " Isleta Resort & Casino - The Showroom",
    address: "11000 Broadway Blvd SE, Albuquerque, NM 87105",
  },
  {
    performers: [{ name: "Tinsley Ellis" }],
    name: "Tinsley Ellis",
    description:
      "Intimate acoustic showcase in celebration of Tinsley’s new album Naked Truth! According to Atlanta-based blues guitarist, singer and songwriter Tinsley Ellis, his new, first-ever solo acoustic album, Naked Truth, is both “a departure and an arrival.” Ellis has been recording and traveling the world for over four decades, delivering his feral, guitar-fueled, original electric blues-rock to ever-growing audiences at concert halls, festivals, and clubs. Naked Truth is steeped in the folk blues traditions of Muddy Waters, Skip James, Son House, Robert Johnson and even Leo Kottke. To the casual fan, this might seem to be a new direction, but for Ellis, […] ...",
    date: "09 APR",
    time: "7:30 PM - 11:00 PM",
    venue: " Fusion | 708",
    address: "708 1st St. NW, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Danny Brown" }],
    name: "Danny Brown Quaranta ’24",
    description: undefined,
    date: "09 APR",
    time: "8:00 PM",
    venue: " El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Conan" }],
    name: "Conan",
    description: undefined,
    date: "12 APR",
    time: "7:00 PM - 10:30 PM",
    venue: " Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Geoff Tate" }],
    name: "Geoff Tate’s Big Rock Show Hits Tour 2024 with Fire and Water",
    description: undefined,
    date: "13 APR",
    time: "8:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Scrap Arts Music" }],
    name: "Scrap Arts Music",
    description:
      "Transformed through art and innovation, everyday scrap and salvage become musical treasure in Scrap Arts Music’s Children of Metropolis. A fast-paced, all-acoustic percussion show with science fiction-style multimedia projections, this fantastic performance takes inspiration from the classic film Metropolis. Five athletic musicians perform with 145 mobile invented instruments, all handmade by group leader and composer, Gregory Kozak to create a one-of-a-kind percussive experience in an unforgettable afternoon of music. ...",
    date: "14 APR",
    time: "3:00 PM",
    venue: " Popejoy Hall",
    address: "203 Cornell Dr, Albuquerque, NM 87131",
  },
  {
    performers: [{ name: "Los Shadows" }],
    name: "Los Shadows & Gio Chamba",
    description: undefined,
    date: "14 APR",
    time: "8:00 PM - 12:00 AM",
    venue: " Launchpad",
    address: "618 Central Ave SW Albuquerque, NM",
  },
  {
    performers: [{ name: "Alestorm" }],
    name: "Alestorm Tour Of The Dead Marauder",
    description: undefined,
    date: "16 APR",
    time: "8:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Maoli" }],
    name: "Maoli – Boots On The Ground Tour with Lindsay James",
    description: undefined,
    date: "17 APR",
    time: "8:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Kai Wachi" }],
    name: "Kai Wachi Presents: Morphosia Tour",
    description:
      "A must-see live experience, Morphosia is a celebration of Kai Wachi’s artistic journey and a testament to his place at the forefront of electronic music. Each show promises to be a unique experience, fusing heart-pounding bass with the emotional depth of his music. ...",
    date: "18 APR",
    time: "9:00 PM",
    venue: " El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Collie Buddz" }],
    name: "Collie Buddz – Take It Easy World Tour with Vibestrong * dj Kaleido",
    description: undefined,
    date: "19 APR",
    time: "8:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Ty Segall" }],
    name: "Ty Segall",
    description:
      "The man in the tree has a guitar, he’s gonna sing. But the sun shining through the branches— are those rays yellow or hazy gray? What day is today? When are you not going to feel this way again? “Hello, Hi”: welcome in to a new room to play the styles and feels that lie under Ty Segall’s fingers, easing fresh air into acoustic space with an assortment of love songs flowering in righteous unconsciousness. Plaintive and wistful, but unafraid. Like rain washing away yesterday, “Hello, Hi” pushes open the door, inviting the new to pass through all the old […] ...",
    date: "20 APR",
    time: "7:00 PM - 11:30 PM",
    venue: " Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Charlie Parr" }],
    name: "Charlie Parr",
    description:
      "In the music of Charlie Parr, there is a sincere conviction and earnest drive to create. The Minnesota-born guitarist, songwriter, and interpreter of traditional music has released 19 albums over two decades and has been known to perform up to 275 shows a year. Parr is a folk troubadour in the truest sense: taking to the road between shows, writing and rewriting songs as he plays, fueled by a belief that music is eternal and cannot be claimed or adequately explained. The bluesman poet pulls closely from the sights and sounds around him, his lyrical craftsmanship built by his influences. […] ...",
    date: "21 APR",
    time: "8:00 PM - 11:00 PM",
    venue: " Fusion | 708",
    address: "708 1st St. NW, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Better lovers" }],
    name: "Better Lovers with Seeyouspacecowboy * Foreign Hands * Greyhave",
    description: undefined,
    date: "22 APR",
    time: "7:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Staying Alive" }],
    name: "Stayin’ Alive",
    description:
      "STAYIN’ ALIVE offers to their audiences the songs and sights of a full Bee Gees playlist, singing blockbusters such as “Night Fever”, “Jive Talkin’”, “How Deep Is Your Love”, “You Should Be Dancing”, “Nights on Broadway” and “Stayin’ Alive”. In addition, they perform softer poetic ballads such as “I Started a Joke”, “Massachusetts”, “Fanny Be Tender”, “Words” and “To Love Somebody” among other great hits.  STAYIN’ ALIVE is the largest and most definitive production of its kind, offering big screen video clips, photos and dazzling imagery. STAYIN’ ALIVE has played intimate settings as a six-piece band and huge venues with a 62-piece orchestra. […] ...",
    date: "23 APR",
    time: "7:30 PM - 10:00 PM",
    venue: " Kimo Theatre",
    address: "423 Central Ave. NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Inzo" }],
    name: "INZO presents VISIONQUEST",
    description:
      "w/ Tape B, Super Ave. x Super Future & Blookah INZO is renowned for his or her strong vigor, distinctive music, and fascinating images. He has a devoted following thanks to the eclectic blend of electronic, dubstep, and experimental genres in his music. He has succeeded in developing a distinctive sound that distinguishes him from other musicians in the genre ...",
    date: "24 APR",
    time: "9:00 PM",
    venue: " El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Swans" }],
    name: "Swans with Kristof Hahn",
    description: undefined,
    date: "25 APR",
    time: "8:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Imminence Live" }],
    name: "Imminence Live in concert: United States 2024",
    description:
      "After appearing in North America for the very first time, making their live debut in the market a complete success story with the entire tour being sold out in 48 hours, venues upgraded not only once, but twice due to enormous demand, and closing in on tickets sales up to 1500 visitors per show, Imminence is already announcing a full US tour during spring 2024, including major festival appearances at Welcome To Rockville and Sonic Temple! Swedish alternative metalcore outfit, Imminence, has during the latest years established their own highly unique brand and pushed the genre beyond extents of anyone’s expectations. With the distinct use of […] ...",
    date: "26 APR",
    time: "7:00 PM - 10:30 PM",
    venue: " Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
  {
    performers: [{ name: "Bruce Cockburn" }],
    name: "Bruce Cockburn",
    description:
      "For 50 years, this Canadian musical legend has been capturing in song the essence of human experience – while fiercely striving to make it better. Presented by Lensic 360. Doors at 6:30 p.m. Show starts at 7:30 p.m. ...",
    date: "30 APR",
    time: "7:30 PM - 10:00 PM",
    venue: " Kimo Theatre",
    address: "423 Central Ave. NW Albuquerque, NM 87102",
  },
  {
    performers: [{ name: "Slowdrive" }],
    name: "slowdive w/ Drab Majesty",
    description: undefined,
    date: "30 APR",
    time: "8:00 PM",
    venue: " El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Born of Osiris" }],
    name: "Born of Osiris * Attila",
    description:
      "* Born Of Osiris * Attila * Traitors * Extortionist * Not Enough Space * The Angels & Villains Born of Osiris is an American progressive metalcore band formed in 2003 in Palatine, Illinois, a suburb of Chicago. The band currently consists of lead vocalist Ronnie Canizaro, lead guitarist Lee McKinney, rhythm guitarist/bassist Nick Rossi, drummer Cameron Losch, and keyboardist/vocalist Joe Buras. ...",
    date: "07 MAY",
    time: "6:00 PM",
    venue: " El Rey Theater",
    address: "622 Central Ave SW Albuquerque, 87102",
  },
  {
    performers: [{ name: "Dayseeker" }],
    name: "Dayseeker with Polaris * Rain City Drive * AVOID.",
    description: undefined,
    date: "22 MAY",
    time: "7:00 PM",
    venue: " Sunshine Theater",
    address: "120 Central Ave, Albuquerque NM 87102",
  },
  {
    performers: [{ name: "Osees" }],
    name: "Crack the coffers, Osees have spawned another frothy LP of head-destroying psych epics to grok and rock out to. You’ll notice the fresh dollop of organ and keyboard prowess courtesy of “Memory of a Cut Off Head” alum and noted key-stabber Tom Dolas…the Quattrone/Rincon drum-corps polyrhythmic pulse continues to astound and pound in equal measure, buttressed by the nimble fingered bottom end of Sir Tim Hellman the Brave and the shred-heaven fret frying of John Dwyer, whilst Lady Brigid Dawson again graces the wax with her harmonic gifts. Aside from the familiar psych-scorch familiar to soggy pit denizens the world […] ...",
    description: undefined,
    date: "13 SEP",
    time: "7:00 PM - 11:00 PM",
    venue: " Sister",
    address: "407 Central Ave NW , Albuquerque, NM",
  },
];
