export const events = [
  {
    name: "Arkansauce",
    venue: "Fusion - The Cell",
    date: "Friday, Feb 2nd 8:00pm",
    age: "All Ages",
    performers: [{ name: "Arkansauce" }],
  },
  {
    name: "David Wax Museum",
    venue: "Tumbleroot Brewery & Distillery",
    date: "Monday, Feb 5th 7:30pm",
    age: "21+ without parent or guardian",
    performers: [{ name: "David Wax Museum" }, { name: "Lone Piñon" }],
  },
  {
    name: "Sun Sounds",
    venue: "Tony Hillerman Library",
    date: "Tuesday, Feb 6th 5:00pm",
    age: "All Ages",
    performers: [{ name: "Sun Sounds" }],
  },
  {
    name: "Robert Jon and the Wreck",
    venue: "Tumbleroot Brewery & Distillery",
    date: "Thursday, Feb 8th 7:30pm",
    age: "21+ without parent or guardian",
    performers: [{ name: "Robert Jon and the Wreck" }, { name: "Hooks & The Huckleberries" }],
  },
  {
    name: "Justin Adams & Mauro Durante",
    venue: "Fusion - 708",
    date: "Monday, Feb 19th 7:30pm",
    age: "All Ages",
    performers: [{ name: "Justin Adams" }, { name: "Mauro Durante" }],
  },
  {
    name: "Justin Adams & Mauro Durante",
    venue: "San Miguel Chapel",
    date: "Tuesday, Feb 20th 7:30pm",
    age: "All Ages",
    performers: [{ name: "Justin Adams" }, { name: "Mauro Durante" }],
  },
  {
    name: "Gov't Mule",
    venue: "Kiva Auditorium",
    date: "Wednesday, Feb 21st 7:30pm",
    age: "All Ages",
    performers: [{ name: "Gov't Mule" }, { name: "Thirty Years Strong" }],
  },
  {
    name: "Dylan LeBlanc",
    venue: "Tumbleroot Brewery & Distillery",
    date: "Thursday, Feb 22nd 7:30pm",
    age: "21+ without parent or guardian",
    performers: [{ name: "Dylan LeBlanc" }],
  },
  {
    name: "Las Migas",
    venue: "National Hispanic Cultural Center - Journal Theatre",
    date: "Saturday, Feb 24th 7:30pm",
    age: "All Ages",
    performers: [{ name: "Las Migas" }],
  },
  {
    name: "Las Migas",
    venue: "The Lensic",
    date: "Sunday, Feb 25th 7:30pm",
    age: "All Ages",
    performers: [{ name: "Las Migas" }],
  },
  {
    name: "Sun Sounds",
    venue: "Lomas Tramway Library",
    date: "Tuesday, Feb 27th 5:00pm",
    age: "All Ages",
    performers: [{ name: "Sun Sounds" }],
  },
  {
    name: "Sona Jobarteh",
    venue: "The Dirty Bourbon",
    date: "Wednesday, Feb 28th 7:30pm",
    age: "21+ Ages",
    performers: [{ name: "Sona Jobarteh" }],
  },
  {
    name: "The Psychology of Serial Killers",
    venue: "The Lensic",
    date: "Saturday, Mar 2nd 7:30pm",
    age: "13+ Ages",
    performers: [{ name: "The Psychology of Serial Killers" }],
  },
  {
    name: "Blue Midnight",
    venue: "Cherry Hills Library",
    date: "Tuesday, Mar 12th 6:00pm",
    age: "All Ages",
    performers: [{ name: "Blue Midnight" }],
  },
  {
    name: "Blue Midnight",
    venue: "Erna Fergusson Library",
    date: "Wednesday, Mar 13th 6:00pm",
    age: "All Ages",
    performers: [{ name: "Blue Midnight" }],
  },
  {
    name: "Alasdair Fraser & Natalie Haas",
    venue: "New Mexico Museum of Art",
    stage: { name: " St Francis Auditorium" },
    date: "Friday, Mar 15th 7:30pm",
    age: "All Ages",
    performers: [{ name: "Alasdair Fraser" }, { name: "Natalie Haas" }],
  },
  {
    name: "Brian Culbertson",
    venue: "National Hispanic Cultural Center - Journal Theatre",
    date: "Friday, Mar 22nd 7:30pm",
    age: "All Ages",
    performers: [{ name: "Brian Culbertson" }, { name: "The Trilogy Tour" }],
  },
  {
    name: "Margo Cilker",
    venue: "Tumbleroot Brewery & Distillery",
    date: "Tuesday, Apr 2nd 7:30pm",
    age: "21+ without parent or guardian",
    performers: [{ name: "Margo Cilker" }],
  },
  {
    name: "Songwriters Circle",
    venue: "Los Griegos Library",
    date: "Thursday, Apr 4th 4:30pm",
    age: "All Ages",
    performers: [
      { name: "Phil Graham" },
      { name: "Naomi Sunderland" },
      { name: "Kristina Jacobsen" },
      { name: "UNM Songwriting Students" },
    ],
  },
  {
    name: "Tinsley Ellis",
    venue: "Fusion - 708",
    date: "Tuesday, Apr 9th 7:30pm",
    age: "All Ages",
    performers: [{ name: "Tinsley Ellis" }, { name: "Naked Truth Tour" }],
  },
  {
    name: "The Wailers",
    venue: "The Lensic",
    date: "Friday, Apr 12th 7:30pm",
    age: "All Ages",
    performers: [{ name: "The Wailers" }],
  },
  {
    name: "The Sadies",
    venue: "Tumbleroot Brewery & Distillery",
    date: "Thursday, May 30th 7:30pm",
    age: "21+ without parent or guardian",
    performers: [{ name: "The Sadies" }],
  },
  {
    name: "Mr. Joe Jackson",
    venue: "The Lensic",
    date: "Saturday, Jun 22nd 8:00pm",
    age: "All Ages",
    performers: [{ name: "Joe Jackson Solo" }, { name: "The Music of Max Champion" }],
  },
  {
    name: "Wailing Souls",
    venue: "Taos Mesa Brewing",
    stage: { name: "Amphitheater (outside)" },
    date: "Thursday, Aug 15th 7:30pm",
    age: "All Ages",
    performers: [{ name: "Wailing Souls" }, { name: "Iriebellion" }],
  },
  {
    name: "Black Uhuru",
    venue: "Santa Fe Brewing Company",
    stage: { name: "The Bridge Patio" },
    date: "Thursday, Sep 12th 7:30pm",
    age: "21+ (Under 21 allowed with parent or guardian)",
    performers: [{ name: "Black Uhuru" }],
  },
];
