import { $Enums } from "../generated";

export const bandNames = [
  "Frozen Violet",
  "Plastic Indigo",
  "Kids of the Rift",
  "Intelligent Ivory",
  "Rustic Concrete",
  "Fantastic Amber",
  "Electronic Cotton",
  "Internal Friction",
  "Static Dogs",
  "Crimson Riot",
  "Digital Olive",
  "Burning Brass",
  "Indigo Giants",
  "Silent Friction",
  "Burning Neon",
  "Generic Teal",
  "Intelligent Fire",
  "Rocky Sky",
  "Future Malice",
  "Northern Copper",
  "Heavy Echoes",
  "Granite Horses",
  "Steel Sugar",
  "Scarlet Riot",
  "Generic Pluto",
  "Electronic Snakes",
  "Wooden Echoes",
  "Future Neon",
  "Rocky Echoes",
  "Internal Riot",
  "The Velvet Echoes",
  "Crimson Horizon",
  "Midnight Bloom",
  "Electric Suns",
  "Whispering Pines",
  "Ironclad Sky",
  "The Wandering Souls",
  "Neon Dreamscape",
  "Phoenix Rising",
  "The Silent Symphony",
  "Echoes of Silence",
  "The Astral Projection",
  "Cosmic Bloom",
  "The Crimson Tide",
  "The Violet Hour",
  "The Emerald Dawn",
  "The Obsidian Tears",
  "The Sapphire Skies",
  "The Golden Echoes",
  "The Diamond Hearts",
  "The Cosmic Echoes",
  "Neon Dreamscape",
  "Velvet Thunder",
  "Midnight Sonata",
  "Whispering Winds",
  "Crystal Cascade",
  "Electric Symphony",
  "Serpentine Serenade",
  "Lunar Lullaby",
  "Crimson Crescendo",
  "Phantom Groove",
  "Ember Embrace",
  "Celestial Chorus",
  "Silken Shadows",
  "Obsidian Oasis",
  "Aurora's Ascent",
  "Zephyr's Zest",
  "Ethereal Echoes",
  "Solar Sojourn",
  "Indigo Infusion",
  "Velvet Vortex",
  "Crimson Cadence",
  "Nocturne Nebula",
  "Whispering Willows",
  "Scarlet Symphony",
  "Emerald Enigma",
  "Sapphire Serenade",
  "Amethyst Aegis",
  "Golden Gaze",
  "Silver Silhouette",
  "Platinum Pulse",
  "Diamond Dazzle",
  "Ruby Rhapsody",
  "Opal Overture",
  "Pearl Panorama",
  "Topaz Tapestry",
  "Jade Jubilee",
  "Onyx Odyssey",
  "Quartz Quartet",
  "Coral Cascade",
  "Amber Ambience",
  "Ivory Illusion",
  "Ebony Echoes",
  "Sunflower Serenade",
  "Lavender Lullaby",
  "Lily's Lament",
  "Rose's Requiem",
  "Violet's Vigil",
  "Daisy's Dawn",
  "Orchid's Oasis",
  "Poppy's Pulse",
  "Carnation's Cadence",
  "Jasmine's Journey",
  "Lilac's Lullaby",
  "Buttercup's Ballad",
  "Tulip's Tango",
  "Hyacinth's Harmony",
  "Bluebell's Bliss",
  "Sunflower's Sojourn",
  "Lavender's Lament",
  "Lily's Lullaby",
  "Rose's Rhapsody",
  "Violet's Voyage",
  "Daisy's Dance",
  "Orchid's Odyssey",
  "Poppy's Panorama",
  "Carnation's Crescendo",
  "Jasmine's Jubilee",
  "Lilac's Legacy",
  "Buttercup's Breeze",
  "Tulip's Tempest",
  "Hyacinth's Haven",
  "Bluebell's Bloom",
  "Midnight Muse",
  "Starlight Sonata",
  "Moonbeam Melody",
  "Twilight Tango",
  "Dawn's Delight",
  "Dusk's Dream",
  "Neon Nocturne",
  "Crimson Cadence",
  "Emerald Enigma",
  "Sapphire Serenade",
];

export const organizerNames = [
  "Live Nation",
  "AEG Presents",
  "Goldenvoice",
  "C3 Presents",
  "Another Planet Entertainment",
  "The Bowery Presents",
  "City Winery",
  "The Fillmore",
  "House of Blues Entertainment",
  "Nederlander Concerts",
  "Soundwave Events",
  "Harmony Productions",
  "Amplify Live",
  "Echo Entertainment",
  "Rhythm & Blues Promotions",
  "The Gig Masters",
  "Stagecraft Productions",
  "Spotlight Entertainment",
  "Encore Events",
  "High Note Productions",
  "Starlight Events",
  "Harmony Productions",
  "Sonic Boom Concerts",
  "Amplify Live",
  "Echo Entertainment",
  "Rhythm & Blues Promotions",
  "The Gig Masters",
  "Stagecraft Productions",
  "Spotlight Entertainment",
  "Encore Events",
  "High Note Productions",
  "Live Wire Entertainment",
  "Sound Stage Productions",
  "The Concert Collective",
  "Music City Events",
  "Festival Fanatics",
  "Showstoppers Inc.",
  "The Entertainment Engine",
  "Groove Nation",
  "Beat Street Productions",
  "Stellar Celebrations",
  "Enchanted Experiences",
  "Vibrant Visions Events",
  "Kaleidoscope Gatherings",
  "Moonbeam Productions",
  "Serendipity Soirees",
  "Whimsical Wonders Events",
  "Starlight Affairs",
  "Ethereal Occasions",
  "Crimson Creations",
  "Aurora Adventures",
  "Zephyr Zephyrs",
  "Ethereal Echoes Events",
  "Solar Celebrations",
  "Indigo Impressions",
  "Velvet Visions",
  "Nocturne Gatherings",
  "Scarlet Soirees",
  "Emerald Experiences",
  "Sapphire Celebrations",
  "Amethyst Affairs",
  "Golden Gatherings",
  "Silver Soirees",
  "Platinum Productions",
  "Diamond Dreams Events",
  "Ruby Revelries",
  "Opal Occasions",
  "Pearl Productions",
  "Topaz Triumphs",
  "Jade Jubilees",
  "Onyx Occasions",
  "Quartz Quests",
  "Coral Creations",
  "Amber Adventures",
  "Ivory Impressions",
  "Ebony Experiences",
  "Sunflower Soirees",
  "Lavender Luxuries",
  "Lily's Celebrations",
  "Rose's Revelries",
  "Violet's Visions",
  "Daisy's Dreams",
  "Orchid's Occasions",
  "Poppy's Productions",
  "Carnation's Creations",
  "Jasmine's Jubilees",
  "Lilac's Luxuries",
  "Buttercup's Bonanzas",
  "Tulip's Triumphs",
  "Hyacinth's Happenings",
  "Bluebell's Bliss Events",
  "Midnight Muse Productions",
  "Starlight Storytellers",
  "Moonbeam Memories",
  "Twilight Tales",
  "Dawn's Delights",
  "Dusk's Dreams Events",
  "Neon Nights Productions",
  "Crimson Celebrations",
  "Emerald Experiences",
  "Sapphire Soirees",
  "Celestial Celebrations",
  "Enchanted Evenings",
  "Vibrant Ventures",
  "Kaleidoscope Kreations",
  "Moonlit Magic",
  "Serene Celebrations",
  "Whimsical Wonders",
  "Starlit Storytellers",
  "Ethereal Events",
  "Crimson Creations Co.",
  "Aurora Adventures Inc.",
  "Zephyr Zest Events",
  "Ethereal Echoes",
  "Solar Spectacles",
  "Indigo Inspirations",
  "Velvet Ventures",
  "Nocturne Narratives",
  "Scarlet Celebrations",
  "Emerald Evenings",
  "Sapphire Spectacles",
  "Amethyst Adventures",
  "Golden Galas",
  "Silver Soirees & Co.",
  "Platinum Parties",
  "Diamond Dreams",
  "Ruby Revels",
  "Opal Occasions & Co.",
  "Pearl Party Planners",
  "Topaz Triumphs Inc.",
  "Jade Jubilees & Co.",
  "Onyx Occasions Inc.",
  "Quartz Quests Events",
  "Coral Celebrations",
  "Amber Affairs",
  "Ivory Inspirations",
  "Ebony Evenings",
  "Sunflower Celebrations",
  "Lavender Luxuries & Co.",
  "Lily's Lavish Events",
  "Rose's Radiant Gatherings",
  "Violet's Visionary Events",
  "Daisy's Dreamy Occasions",
  "Orchid's Opulent Affairs",
  "Poppy's Perfect Parties",
];

export const venueNames = [
  {
    name: "The Blue Note",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Cozy Corner Cafe",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The Blind Pig",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "The Hop Spot Brewery",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "Vineyard Vista",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Stillhouse",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "The Underground",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Grand Theater",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "Artful Expressions Gallery",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "The District",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "Lucky's Casino",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Entertainment Complex",
    type: $Enums.VenueType["COMPLEX"],
  },
  {
    name: "Champion Stadium",
    type: $Enums.VenueType["STADIUM"],
  },
  {
    name: "The Grand Hotel",
    type: $Enums.VenueType["HOTEL"],
  },
  {
    name: "The City Museum",
    type: $Enums.VenueType["MUSEUM"],
  },
  {
    name: "The Community Hub",
    type: $Enums.VenueType["COMMUNITY_CENTER"],
  },
  {
    name: "Central Park",
    type: $Enums.VenueType["PARK"],
  },
  {
    name: "The County Fairgrounds",
    type: $Enums.VenueType["FAIRGROUNDS"],
  },
  {
    name: "The Music Room",
    type: $Enums.VenueType["VENUE"],
  },
  {
    name: "The Eatery",
    type: $Enums.VenueType["RESTAURANT"],
  },
  {
    name: "Coffee & Co.",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The Tipsy Tavern",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "Brewtiful",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "The Wine Cellar",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Distillery District",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "Club Euphoria",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Playhouse",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "The Art House",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "The Square",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "Casino Royale",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Velvet Note",
    type: $Enums.VenueType["VENUE"],
  },
  {
    name: "Sizzle & Sound",
    type: $Enums.VenueType["RESTAURANT"],
  },
  {
    name: "Caffeinated Chords",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The Tipsy Troubadour",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "Hoppy Harmony Brewing",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "Vineyard Vibes",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Still & Stage",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "Pulse Nightclub",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Encore Theater",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "Art & Acoustics Gallery",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "Rhythm & Riverbend",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "The Lucky 7 Lounge",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Sound Stage Complex",
    type: $Enums.VenueType["COMPLEX"],
  },
  {
    name: "Harmony Arena",
    type: $Enums.VenueType["STADIUM"],
  },
  {
    name: "The Serenade Suites",
    type: $Enums.VenueType["HOTEL"],
  },
  {
    name: "Melodies & Masterpieces",
    type: $Enums.VenueType["MUSEUM"],
  },
  {
    name: "Community Chords Center",
    type: $Enums.VenueType["COMMUNITY_CENTER"],
  },
  {
    name: "Symphony in the Park",
    type: $Enums.VenueType["PARK"],
  },
  {
    name: "Fairground Festivities",
    type: $Enums.VenueType["FAIRGROUNDS"],
  },
  {
    name: "The Electric Eel",
    type: $Enums.VenueType["VENUE"],
  },
  {
    name: "Flavor & Flair Bistro",
    type: $Enums.VenueType["RESTAURANT"],
  },
  {
    name: "Java Jive",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The Crooked Crow Bar",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "Brew & Groove",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "Uncorked Melodies",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Copper Kettle Distillery",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "Euphoria",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Spotlight Playhouse",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "Canvas & Cadence",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "Mountain Melodies Amphitheater",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "The High Roller's Hideaway",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Rhythm & Reels Complex",
    type: $Enums.VenueType["COMPLEX"],
  },
  {
    name: "The Grandstand",
    type: $Enums.VenueType["STADIUM"],
  },
  {
    name: "The Rhapsody Resort",
    type: $Enums.VenueType["HOTEL"],
  },
  {
    name: "Art & Echo",
    type: $Enums.VenueType["MUSEUM"],
  },
  {
    name: "Harmony Hall",
    type: $Enums.VenueType["COMMUNITY_CENTER"],
  },
  {
    name: "Riverside Rhythms",
    type: $Enums.VenueType["PARK"],
  },
  {
    name: "County Carnival & Concerts",
    type: $Enums.VenueType["FAIRGROUNDS"],
  },
  {
    name: "The Sound Garden",
    type: $Enums.VenueType["VENUE"],
  },
  {
    name: "Taste & Tunes",
    type: $Enums.VenueType["RESTAURANT"],
  },
  {
    name: "The Buzzing Bean",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The Rusty Nail Tavern",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "Hops & Harmony",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "The Grape & Grain",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Speakeasy Stillhouse",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "The Velvet Rope",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Curtain Call Theater",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "Expressions & Melodies",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "Echo Canyon",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "The Jackpot Junction",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Entertainment Emporium",
    type: $Enums.VenueType["COMPLEX"],
  },
  {
    name: "The Coliseum",
    type: $Enums.VenueType["STADIUM"],
  },
  {
    name: "The Harmony Hotel",
    type: $Enums.VenueType["HOTEL"],
  },
  {
    name: "Cultural Cadence Center",
    type: $Enums.VenueType["MUSEUM"],
  },
  {
    name: "The Gathering Place",
    type: $Enums.VenueType["COMMUNITY_CENTER"],
  },
  {
    name: "Sunset Serenade Park",
    type: $Enums.VenueType["PARK"],
  },
  {
    name: "The State Fair Stage",
    type: $Enums.VenueType["FAIRGROUNDS"],
  },
  {
    name: "The Stage Door",
    type: $Enums.VenueType["VENUE"],
  },
  {
    name: "Savory Sounds",
    type: $Enums.VenueType["RESTAURANT"],
  },
  {
    name: "The Perky Percolator",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The Drunken Drummer",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "The Fermented Funk",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "The Cask & Cork",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Bootlegger's Barrel",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "The Underground",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Footlights Theater",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "Brushstrokes & Basslines",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "The Meadow Music Festival",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "The Royal Flush Casino",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Kaleidoscope Complex",
    type: $Enums.VenueType["COMPLEX"],
  },
  {
    name: "The Bowl",
    type: $Enums.VenueType["STADIUM"],
  },
  {
    name: "The Lyric Lodge",
    type: $Enums.VenueType["HOTEL"],
  },
  {
    name: "Heritage Harmonies",
    type: $Enums.VenueType["MUSEUM"],
  },
  {
    name: "The Neighborhood Nook",
    type: $Enums.VenueType["COMMUNITY_CENTER"],
  },
  {
    name: "Central Park Concerts",
    type: $Enums.VenueType["PARK"],
  },
  {
    name: "The Harvest Hoedown",
    type: $Enums.VenueType["FAIRGROUNDS"],
  },
  {
    name: "The Backstage Bar & Grill",
    type: $Enums.VenueType["VENUE"],
  },
  {
    name: "Spice & Symphony",
    type: $Enums.VenueType["RESTAURANT"],
  },
  {
    name: "The Coffee Cantata",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The Liquid Lounge",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "The Brewhouse Beats",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "The Vintage Vineyard",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Moonshine Manor",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "The Groove Garden",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Grand Opera House",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "Palette & Performance",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "The Desert Nights Festival",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "The Ace in the Hole",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Melodic Maze",
    type: $Enums.VenueType["COMPLEX"],
  },
  {
    name: "The Thunderdome",
    type: $Enums.VenueType["STADIUM"],
  },
  {
    name: "The Aria Inn",
    type: $Enums.VenueType["HOTEL"],
  },
  {
    name: "Artifacts & Anthems",
    type: $Enums.VenueType["MUSEUM"],
  },
  {
    name: "The Heart of the Community",
    type: $Enums.VenueType["COMMUNITY_CENTER"],
  },
  {
    name: "Woodland Warbles",
    type: $Enums.VenueType["PARK"],
  },
  {
    name: "The County Jamboree",
    type: $Enums.VenueType["FAIRGROUNDS"],
  },
  {
    name: "The Amplified Attic",
    type: $Enums.VenueType["VENUE"],
  },
  {
    name: "Fusion Flavors & Fun",
    type: $Enums.VenueType["RESTAURANT"],
  },
  {
    name: "The Mocha Muse",
    type: $Enums.VenueType["CAFE"],
  },
  {
    name: "The High Note Hideaway",
    type: $Enums.VenueType["BAR"],
  },
  {
    name: "The Malted Melody",
    type: $Enums.VenueType["BREWERY"],
  },
  {
    name: "The Corkscrew & Chord",
    type: $Enums.VenueType["WINERY"],
  },
  {
    name: "The Elixir Emporium",
    type: $Enums.VenueType["DISTILLERY"],
  },
  {
    name: "The Neon Nighthawks",
    type: $Enums.VenueType["CLUB"],
  },
  {
    name: "The Vaudeville Venue",
    type: $Enums.VenueType["THEATER"],
  },
  {
    name: "The Artistic Alcove",
    type: $Enums.VenueType["GALLERY"],
  },
  {
    name: "The Lakeside Lyric Lawn",
    type: $Enums.VenueType["AREA"],
  },
  {
    name: "The Riverboat Rhythm Room",
    type: $Enums.VenueType["CASINO"],
  },
  {
    name: "The Polyphonic Playground",
    type: $Enums.VenueType["COMPLEX"],
  },
  {
    name: "The Champion's Circle",
    type: $Enums.VenueType["STADIUM"],
  },
  {
    name: "The Suite Sounds Hotel",
    type: $Enums.VenueType["HOTEL"],
  },
  {
    name: "The Historical Harmonies Hall",
    type: $Enums.VenueType["MUSEUM"],
  },
  {
    name: "The Common Ground",
    type: $Enums.VenueType["COMMUNITY_CENTER"],
  },
  {
    name: "The Meadow's Minstrels",
    type: $Enums.VenueType["PARK"],
  },
];
