import { $Enums } from "@prisma/client";

export const bandNames = [
  "Frozen Violet",
  "Plastic Indigo",
  "Kids of the Rift",
  "Intelligent Ivory",
  "Rustic Concrete",
  "Fantastic Amber",
  "Electronic Cotton",
  "Internal Friction",
  "Static Dogs",
  "Crimson Riot",
  "Digital Olive",
  "Burning Brass",
  "Indigo Giants",
  "Silent Friction",
  "Burning Neon",
  "Generic Teal",
  "Intelligent Fire",
  "Rocky Sky",
  "Future Malice",
  "Northern Copper",
  "Heavy Echoes",
  "Granite Horses",
  "Steel Sugar",
  "Scarlet Riot",
  "Generic Pluto",
  "Electronic Snakes",
  "Wooden Echoes",
  "Future Neon",
  "Rocky Echoes",
  "Internal Riot",
  "The Velvet Echoes",
  "Crimson Horizon",
  "Midnight Bloom",
  "Electric Suns",
  "Whispering Pines",
  "Ironclad Sky",
  "The Wandering Souls",
  "Neon Dreamscape",
  "Phoenix Rising",
  "The Silent Symphony",
  "Echoes of Silence",
  "The Astral Projection",
  "Cosmic Bloom",
  "The Crimson Tide",
  "The Violet Hour",
  "The Emerald Dawn",
  "The Obsidian Tears",
  "The Sapphire Skies",
  "The Golden Echoes",
  "The Diamond Hearts",
];

export const venueNames = [
  { name: "The Blue Note", type: $Enums.VenueType["CLUB"] },
  { name: "The Cozy Corner Cafe", type: $Enums.VenueType["CAFE"] },
  { name: "The Blind Pig", type: $Enums.VenueType["BAR"] },
  { name: "The Hop Spot Brewery", type: $Enums.VenueType["BREWERY"] },
  { name: "Vineyard Vista", type: $Enums.VenueType["WINERY"] },
  { name: "The Stillhouse", type: $Enums.VenueType["DISTILLERY"] },
  { name: "The Underground", type: $Enums.VenueType["CLUB"] },
  { name: "The Grand Theater", type: $Enums.VenueType["THEATER"] },
  { name: "Artful Expressions Gallery", type: $Enums.VenueType["GALLERY"] },
  { name: "The District", type: $Enums.VenueType["AREA"] },
  { name: "Lucky's Casino", type: $Enums.VenueType["CASINO"] },
  { name: "The Entertainment Complex", type: $Enums.VenueType["COMPLEX"] },
  { name: "Champion Stadium", type: $Enums.VenueType["STADIUM"] },
  { name: "The Grand Hotel", type: $Enums.VenueType["HOTEL"] },
  { name: "The City Museum", type: $Enums.VenueType["MUSEUM"] },
  { name: "The Community Hub", type: $Enums.VenueType["COMMUNITY_CENTER"] },
  { name: "Central Park", type: $Enums.VenueType["PARK"] },
  { name: "The County Fairgrounds", type: $Enums.VenueType["FAIRGROUNDS"] },
  { name: "The Music Room", type: $Enums.VenueType["VENUE"] },
  { name: "The Eatery", type: $Enums.VenueType["RESTAURANT"] },
  { name: "Coffee & Co.", type: $Enums.VenueType["CAFE"] },
  { name: "The Tipsy Tavern", type: $Enums.VenueType["BAR"] },
  { name: "Brewtiful", type: $Enums.VenueType["BREWERY"] },
  { name: "The Wine Cellar", type: $Enums.VenueType["WINERY"] },
  { name: "The Distillery District", type: $Enums.VenueType["DISTILLERY"] },
  { name: "Club Euphoria", type: $Enums.VenueType["CLUB"] },
  { name: "The Playhouse", type: $Enums.VenueType["THEATER"] },
  { name: "The Art House", type: $Enums.VenueType["GALLERY"] },
  { name: "The Square", type: $Enums.VenueType["AREA"] },
  { name: "Casino Royale", type: $Enums.VenueType["CASINO"] },
];

export const organizerNames = [
  "Live Nation",
  "AEG Presents",
  "Goldenvoice",
  "C3 Presents",
  "Another Planet Entertainment",
  "The Bowery Presents",
  "City Winery",
  "The Fillmore",
  "House of Blues Entertainment",
  "Nederlander Concerts",
  "Soundwave Events",
  "Harmony Productions",
  "Amplify Live",
  "Echo Entertainment",
  "Rhythm & Blues Promotions",
  "The Gig Masters",
  "Stagecraft Productions",
  "Spotlight Entertainment",
  "Encore Events",
  "High Note Productions",
  "Starlight Events",
  "Harmony Productions",
  "Sonic Boom Concerts",
  "Amplify Live",
  "Echo Entertainment",
  "Rhythm & Blues Promotions",
  "The Gig Masters",
  "Stagecraft Productions",
  "Spotlight Entertainment",
  "Encore Events",
  "High Note Productions",
  "Live Wire Entertainment",
  "Sound Stage Productions",
  "The Concert Collective",
  "Music City Events",
  "Festival Fanatics",
  "Showstoppers Inc.",
  "The Entertainment Engine",
  "Groove Nation",
  "Beat Street Productions",
];
