import { faker } from "@faker-js/faker";
import { $Enums, Prisma } from "@prisma/client";

export const locations = [
  // Regions (2)
  {
    id: "1",
    name: "Northeast",
    slug: faker.helpers.slugify("Northeast".toLowerCase()),
    uniqueName: faker.helpers.slugify("Northeast".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.REGION,
  },
  {
    id: "2",
    name: "Midwest",
    slug: faker.helpers.slugify("Midwest".toLowerCase()),
    uniqueName: faker.helpers.slugify("Midwest".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.REGION,
  },

  // Sub-Regions (6)
  {
    id: "3",
    name: "New England",
    slug: faker.helpers.slugify("New England".toLowerCase()),
    uniqueName: faker.helpers.slugify("New England".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.SUBREGION,
    parentId: "1",
  },
  {
    id: "4",
    name: "Mid-Atlantic",
    slug: faker.helpers.slugify("Mid-Atlantic".toLowerCase()),
    uniqueName: faker.helpers.slugify("Mid-Atlantic".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.SUBREGION,
    parentId: "1",
  },
  {
    id: "5",
    name: "Great Lakes",
    slug: faker.helpers.slugify("Great Lakes".toLowerCase()),
    uniqueName: faker.helpers.slugify("Great Lakes".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.SUBREGION,
    parentId: "2",
  },
  {
    id: "6",
    name: "East North Central",
    slug: faker.helpers.slugify("East North Central".toLowerCase()),
    uniqueName: faker.helpers.slugify("East North Central".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.SUBREGION,
    parentId: "2",
  },
  {
    id: "7",
    name: "West North Central",
    slug: faker.helpers.slugify("West North Central".toLowerCase()),
    uniqueName: faker.helpers.slugify("West North Central".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.SUBREGION,
    parentId: "2",
  },
  {
    id: "8",
    name: "Plains",
    slug: faker.helpers.slugify("Plains".toLowerCase()),
    uniqueName: faker.helpers.slugify("Plains".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.SUBREGION,
    parentId: "2",
  },

  // Areas (12)
  {
    id: "9",
    name: "Boston Metro",
    slug: faker.helpers.slugify("Boston Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Boston Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "3",
  },
  {
    id: "10",
    name: "NYC Metro",
    slug: faker.helpers.slugify("NYC Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("NYC Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "4",
  },
  {
    id: "11",
    name: "Philadelphia Metro",
    slug: faker.helpers.slugify("Philadelphia Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Philadelphia Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "4",
  },
  {
    id: "12",
    name: "Chicago Metro",
    slug: faker.helpers.slugify("Chicago Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Chicago Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "5",
  },
  {
    id: "13",
    name: "Detroit Metro",
    slug: faker.helpers.slugify("Detroit Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Detroit Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "5",
  },
  {
    id: "14",
    name: "Indianapolis Metro",
    slug: faker.helpers.slugify("Indianapolis Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Indianapolis Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "6",
  },
  {
    id: "15",
    name: "Columbus Metro",
    slug: faker.helpers.slugify("Columbus Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Columbus Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "6",
  },
  {
    id: "16",
    name: "Minneapolis-St. Paul",
    slug: faker.helpers.slugify("Minneapolis-St. Paul".toLowerCase()),
    uniqueName: faker.helpers.slugify("Minneapolis-St. Paul".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "7",
  },
  {
    id: "17",
    name: "Kansas City Metro",
    slug: faker.helpers.slugify("Kansas City Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Kansas City Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "7",
  },
  {
    id: "18",
    name: "Omaha Metro",
    slug: faker.helpers.slugify("Omaha Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Omaha Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "8",
  },
  {
    id: "19",
    name: "Oklahoma City Metro",
    slug: faker.helpers.slugify("Oklahoma City Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Oklahoma City Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "8",
  },
  {
    id: "20",
    name: "Wichita Metro",
    slug: faker.helpers.slugify("Wichita Metro".toLowerCase()),
    uniqueName: faker.helpers.slugify("Wichita Metro".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.AREA,
    parentId: "8",
  },

  // Cities (20)
  {
    id: "21",
    name: "Boston",
    slug: faker.helpers.slugify("Boston".toLowerCase()),
    uniqueName: faker.helpers.slugify("Boston".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "9",
  },
  {
    id: "22",
    name: "Cambridge",
    slug: faker.helpers.slugify("Cambridge".toLowerCase()),
    uniqueName: faker.helpers.slugify("Cambridge".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "9",
  },
  {
    id: "23",
    name: "New York City",
    slug: faker.helpers.slugify("New York City".toLowerCase()),
    uniqueName: faker.helpers.slugify("New York City".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "10",
  },
  {
    id: "24",
    name: "Brooklyn",
    slug: faker.helpers.slugify("Brooklyn".toLowerCase()),
    uniqueName: faker.helpers.slugify("Brooklyn".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "10",
  },
  {
    id: "25",
    name: "Philadelphia",
    slug: faker.helpers.slugify("Philadelphia".toLowerCase()),
    uniqueName: faker.helpers.slugify("Philadelphia".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "11",
  },
  {
    id: "26",
    name: "Chicago",
    slug: faker.helpers.slugify("Chicago".toLowerCase()),
    uniqueName: faker.helpers.slugify("Chicago".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "12",
  },
  {
    id: "27",
    name: "Evanston",
    slug: faker.helpers.slugify("Evanston".toLowerCase()),
    uniqueName: faker.helpers.slugify("Evanston".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "12",
  },
  {
    id: "28",
    name: "Detroit",
    slug: faker.helpers.slugify("Detroit".toLowerCase()),
    uniqueName: faker.helpers.slugify("Detroit".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "13",
  },
  {
    id: "29",
    name: "Ann Arbor",
    slug: faker.helpers.slugify("Ann Arbor".toLowerCase()),
    uniqueName: faker.helpers.slugify("Ann Arbor".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "13",
  },
  {
    id: "30",
    name: "Indianapolis",
    slug: faker.helpers.slugify("Indianapolis".toLowerCase()),
    uniqueName: faker.helpers.slugify("Indianapolis".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "14",
  },
  {
    id: "31",
    name: "Carmel",
    slug: faker.helpers.slugify("Carmel".toLowerCase()),
    uniqueName: faker.helpers.slugify("Carmel".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "14",
  },
  {
    id: "32",
    name: "Columbus",
    slug: faker.helpers.slugify("Columbus".toLowerCase()),
    uniqueName: faker.helpers.slugify("Columbus".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "15",
  },
  {
    id: "33",
    name: "Dublin",
    slug: faker.helpers.slugify("Dublin".toLowerCase()),
    uniqueName: faker.helpers.slugify("Dublin".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "15",
  },
  {
    id: "34",
    name: "Minneapolis",
    slug: faker.helpers.slugify("Minneapolis".toLowerCase()),
    uniqueName: faker.helpers.slugify("Minneapolis".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "16",
  },
  {
    id: "35",
    name: "St. Paul",
    slug: faker.helpers.slugify("St. Paul".toLowerCase()),
    uniqueName: faker.helpers.slugify("St. Paul".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "16",
  },
  {
    id: "36",
    name: "Kansas City",
    slug: faker.helpers.slugify("Kansas City".toLowerCase()),
    uniqueName: faker.helpers.slugify("Kansas City".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "17",
  },
  {
    id: "37",
    name: "Overland Park",
    slug: faker.helpers.slugify("Overland Park".toLowerCase()),
    uniqueName: faker.helpers.slugify("Overland Park".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "17",
  },
  {
    id: "38",
    name: "Omaha",
    slug: faker.helpers.slugify("Omaha".toLowerCase()),
    uniqueName: faker.helpers.slugify("Omaha".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "18",
  },
  {
    id: "39",
    name: "Lincoln",
    slug: faker.helpers.slugify("Lincoln".toLowerCase()),
    uniqueName: faker.helpers.slugify("Lincoln".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "18",
  },
  {
    id: "40",
    name: "Oklahoma City",
    slug: faker.helpers.slugify("Oklahoma City".toLowerCase()),
    uniqueName: faker.helpers.slugify("Oklahoma City".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "19",
  },
  {
    id: "41",
    name: "Norman",
    slug: faker.helpers.slugify("Norman".toLowerCase()),
    uniqueName: faker.helpers.slugify("Norman".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.CITY,
    parentId: "19",
  },

  // Neighborhoods (40)
  {
    id: "42",
    name: "Back Bay",
    slug: faker.helpers.slugify("Back Bay".toLowerCase()),
    uniqueName: faker.helpers.slugify("Back Bay".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "21",
  },
  {
    id: "43",
    name: "Harvard Square",
    slug: faker.helpers.slugify("Harvard Square".toLowerCase()),
    uniqueName: faker.helpers.slugify("Harvard Square".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "22",
  },
  {
    id: "44",
    name: "Midtown Manhattan",
    slug: faker.helpers.slugify("Midtown Manhattan".toLowerCase()),
    uniqueName: faker.helpers.slugify("Midtown Manhattan".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "23",
  },
  {
    id: "45",
    name: "Williamsburg",
    slug: faker.helpers.slugify("Williamsburg".toLowerCase()),
    uniqueName: faker.helpers.slugify("Williamsburg".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "24",
  },
  {
    id: "46",
    name: "Fishtown",
    slug: faker.helpers.slugify("Fishtown".toLowerCase()),
    uniqueName: faker.helpers.slugify("Fishtown".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "25",
  },
  {
    id: "47",
    name: "Wicker Park",
    slug: faker.helpers.slugify("Wicker Park".toLowerCase()),
    uniqueName: faker.helpers.slugify("Wicker Park".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "48",
    name: "Lincoln Park",
    slug: faker.helpers.slugify("Lincoln Park".toLowerCase()),
    uniqueName: faker.helpers.slugify("Lincoln Park".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "49",
    name: "Downtown Detroit",
    slug: faker.helpers.slugify("Downtown Detroit".toLowerCase()),
    uniqueName: faker.helpers.slugify("Downtown Detroit".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "28",
  },
  {
    id: "50",
    name: "Midtown Detroit",
    slug: faker.helpers.slugify("Midtown Detroit".toLowerCase()),
    uniqueName: faker.helpers.slugify("Midtown Detroit".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "28",
  },
  {
    id: "51",
    name: "Downtown Indianapolis",
    slug: faker.helpers.slugify("Downtown Indianapolis".toLowerCase()),
    uniqueName: faker.helpers.slugify("Downtown Indianapolis".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "30",
  },
  {
    id: "52",
    name: "Broad Ripple Village",
    slug: faker.helpers.slugify("Broad Ripple Village".toLowerCase()),
    uniqueName: faker.helpers.slugify("Broad Ripple Village".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "30",
  },
  {
    id: "53",
    name: "German Village",
    slug: faker.helpers.slugify("German Village".toLowerCase()),
    uniqueName: faker.helpers.slugify("German Village".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "32",
  },
  {
    id: "54",
    name: "Short North",
    slug: faker.helpers.slugify("Short North".toLowerCase()),
    uniqueName: faker.helpers.slugify("Short North".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "32",
  },
  {
    id: "55",
    name: "Uptown Minneapolis",
    slug: faker.helpers.slugify("Uptown Minneapolis".toLowerCase()),
    uniqueName: faker.helpers.slugify("Uptown Minneapolis".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "34",
  },
  {
    id: "56",
    name: "North Loop",
    slug: faker.helpers.slugify("North Loop".toLowerCase()),
    uniqueName: faker.helpers.slugify("North Loop".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "34",
  },
  {
    id: "57",
    name: "Westport",
    slug: faker.helpers.slugify("Westport".toLowerCase()),
    uniqueName: faker.helpers.slugify("Westport".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "36",
  },
  {
    id: "58",
    name: "Country Club Plaza",
    slug: faker.helpers.slugify("Country Club Plaza".toLowerCase()),
    uniqueName: faker.helpers.slugify("Country Club Plaza".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "36",
  },
  {
    id: "59",
    name: "Old Market",
    slug: faker.helpers.slugify("Old Market".toLowerCase()),
    uniqueName: faker.helpers.slugify("Old Market".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "38",
  },
  {
    id: "60",
    name: "Dundee-Memorial Park",
    slug: faker.helpers.slugify("Dundee-Memorial Park".toLowerCase()),
    uniqueName: faker.helpers.slugify("Dundee-Memorial Park".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "38",
  },
  {
    id: "61",
    name: "Bricktown",
    slug: faker.helpers.slugify("Bricktown".toLowerCase()),
    uniqueName: faker.helpers.slugify("Bricktown".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "40",
  },
  {
    id: "62",
    name: "Paseo Arts District",
    slug: faker.helpers.slugify("Paseo Arts District".toLowerCase()),
    uniqueName: faker.helpers.slugify("Paseo Arts District".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "40",
  },
  {
    id: "63",
    name: "Mid-Cambridge",
    slug: faker.helpers.slugify("Mid-Cambridge".toLowerCase()),
    uniqueName: faker.helpers.slugify("Mid-Cambridge".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "22",
  },
  {
    id: "64",
    name: "Upper West Side",
    slug: faker.helpers.slugify("Upper West Side".toLowerCase()),
    uniqueName: faker.helpers.slugify("Upper West Side".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "23",
  },
  {
    id: "65",
    name: "Greenwich Village",
    slug: faker.helpers.slugify("Greenwich Village".toLowerCase()),
    uniqueName: faker.helpers.slugify("Greenwich Village".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "23",
  },
  {
    id: "66",
    name: "DUMBO",
    slug: faker.helpers.slugify("DUMBO".toLowerCase()),
    uniqueName: faker.helpers.slugify("DUMBO".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "24",
  },
  {
    id: "67",
    name: "Northern Liberties",
    slug: faker.helpers.slugify("Northern Liberties".toLowerCase()),
    uniqueName: faker.helpers.slugify("Northern Liberties".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "25",
  },
  {
    id: "68",
    name: "Logan Square",
    slug: faker.helpers.slugify("Logan Square".toLowerCase()),
    uniqueName: faker.helpers.slugify("Logan Square".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "69",
    name: "Lakeview",
    slug: faker.helpers.slugify("Lakeview".toLowerCase()),
    uniqueName: faker.helpers.slugify("Lakeview".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "70",
    name: "Corktown",
    slug: faker.helpers.slugify("Corktown".toLowerCase()),
    uniqueName: faker.helpers.slugify("Corktown".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "28",
  },
  {
    id: "71",
    name: "Greektown",
    slug: faker.helpers.slugify("Greektown".toLowerCase()),
    uniqueName: faker.helpers.slugify("Greektown".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "28",
  },
  {
    id: "72",
    name: "Fountain Square",
    slug: faker.helpers.slugify("Fountain Square".toLowerCase()),
    uniqueName: faker.helpers.slugify("Fountain Square".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "30",
  },
  {
    id: "73",
    name: "Mass Ave",
    slug: faker.helpers.slugify("Mass Ave".toLowerCase()),
    uniqueName: faker.helpers.slugify("Mass Ave".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "30",
  },
  {
    id: "74",
    name: "Near North Side",
    slug: faker.helpers.slugify("Near North Side".toLowerCase()),
    uniqueName: faker.helpers.slugify("Near North Side".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "75",
    name: "West Loop",
    slug: faker.helpers.slugify("West Loop".toLowerCase()),
    uniqueName: faker.helpers.slugify("West Loop".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "76",
    name: "River North",
    slug: faker.helpers.slugify("River North".toLowerCase()),
    uniqueName: faker.helpers.slugify("River North".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "77",
    name: "Gold Coast",
    slug: faker.helpers.slugify("Gold Coast".toLowerCase()),
    uniqueName: faker.helpers.slugify("Gold Coast".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "78",
    name: "Streeterville",
    slug: faker.helpers.slugify("Streeterville".toLowerCase()),
    uniqueName: faker.helpers.slugify("Streeterville".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "79",
    name: "South Loop",
    slug: faker.helpers.slugify("South Loop".toLowerCase()),
    uniqueName: faker.helpers.slugify("South Loop".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
  {
    id: "80",
    name: "Hyde Park",
    slug: faker.helpers.slugify("Hyde Park".toLowerCase()),
    uniqueName: faker.helpers.slugify("Hyde Park".toLowerCase()),
    latitude: 0,
    longitude: 0,
    type: $Enums.LocationType.NEIGHBORHOOD,
    parentId: "26",
  },
] satisfies Prisma.LocationCreateManyInput[];
