export const instruments = [
  { id: "acoustic-guitar", name: "Acoustic Guitar" },
  { id: "electric-guitar", name: "Electric Guitar" },
  { id: "bass-guitar", name: "Bass Guitar" },
  { id: "acoustic0bass", name: "Acoustic Bass" },
  { id: "drums", name: "Drums" },
  { id: "keyboard-piano", name: "Keyboard / Piano" },
  { id: "synthesizer", name: "Synthesizer" },
  { id: "violin", name: "Violin" },
  { id: "viola", name: "Viola" },
  { id: "cello", name: "Cello" },
  { id: "saxophone", name: "Saxophone" },
  { id: "trumpet", name: "Trumpet" },
  { id: "trombone", name: "Trombone" },
  { id: "flute", name: "Flute" },
  { id: "clarinet", name: "Clarinet" },
  { id: "harmonica", name: "Harmonica" },
  { id: "accordion", name: "Accordion" },
  { id: "mandolin", name: "Mandolin" },
  { id: "banjo", name: "Banjo" },
  { id: "ukulele", name: "Ukulele" },
  { id: "vocals", name: "Vocals" },
  { id: "dj-turntables", name: "DJ Turntables" },
  { id: "drum-machine", name: "Drum Machine" },
  { id: "sampler", name: "Sampler" },
  { id: "percussion", name: "Percussion" },
];
