export const instruments = [
  "Acoustic Guitar",
  "Electric Guitar",
  "Bass Guitar",
  "Acoustic Bass",
  "Drums",
  "Keyboard / Piano",
  "Synthesizer",
  "Violin",
  "Viola",
  "Cello",
  "Saxophone",
  "Trumpet",
  "Trombone",
  "Flute",
  "Clarinet",
  "Harmonica",
  "Accordion",
  "Mandolin",
  "Banjo",
  "Ukulele",
  "Vocals",
  "DJ Turntables",
  "Drum Machine",
  "Sampler",
  "Percussion",
];
