export const instruments = [
  { id: "acoustic-guitar", displayName: "Acoustic Guitar" },
  { id: "electric-guitar", displayName: "Electric Guitar" },
  { id: "bass-guitar", displayName: "Bass Guitar" },
  { id: "acoustic0bass", displayName: "Acoustic Bass" },
  { id: "drums", displayName: "Drums" },
  { id: "keyboard-piano", displayName: "Keyboard / Piano" },
  { id: "synthesizer", displayName: "Synthesizer" },
  { id: "violin", displayName: "Violin" },
  { id: "viola", displayName: "Viola" },
  { id: "cello", displayName: "Cello" },
  { id: "saxophone", displayName: "Saxophone" },
  { id: "trumpet", displayName: "Trumpet" },
  { id: "trombone", displayName: "Trombone" },
  { id: "flute", displayName: "Flute" },
  { id: "clarinet", displayName: "Clarinet" },
  { id: "harmonica", displayName: "Harmonica" },
  { id: "accordion", displayName: "Accordion" },
  { id: "mandolin", displayName: "Mandolin" },
  { id: "banjo", displayName: "Banjo" },
  { id: "ukulele", displayName: "Ukulele" },
  { id: "vocals", displayName: "Vocals" },
  { id: "dj-turntables", displayName: "DJ Turntables" },
  { id: "drum-machine", displayName: "Drum Machine" },
  { id: "sampler", displayName: "Sampler" },
  { id: "percussion", displayName: "Percussion" },
];
