export interface MyEvent {
  id: string;
  name: string;
  slug: string;
  image: string;
  description: string;
  genres: string[];
  keywords: string[];
  timeDoor: string;
  timeStart: string;
  timeStartPrevious: string | null;
  timeEnd: string;
  isPrivate: boolean;
  isFree: boolean;
  isChildFriendly: boolean;
  isHoliday: boolean;
  ageRestriction: boolean;
  minimumAge?: number;
  servesAlcohol: boolean;
  servesFood: boolean;
  requiresRsvp: boolean;
  rsvpLink?: string;
  requiresTicket: boolean;
  ticketLinks: string[];
  venue: string; //id reference
  organizer: string | null; //id reference
  musicians: string[]; //id reference
  bands: string[]; //id reference
}

export const events: MyEvent[] = [
  {
    id: "y5n2cg1osia",
    name: "Mariachi Sol de Mexico Concert",
    slug: "90v0ati3bc4",
    image: "https://picsum.photos/200",
    description:
      "Come see Mariachi Sol de Mexico perform live at The Longhorn Saloon!",
    genres: ["Mariachi", "Traditional Mexican"],
    keywords: ["live music", "Mariachi", "Traditional Mexican"],
    timeDoor: "2025-05-08T19:24:56.466Z",
    timeStart: "2024-11-17T05:05:12.439Z",
    timeStartPrevious: null,
    timeEnd: "2025-05-02T08:13:30.945Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-6"],
  },
  {
    id: "ptfdk0q6jcp",
    name: "The Reverend Johnson Performance",
    slug: "9yqxjr5pt6",
    image: "https://picsum.photos/200",
    description:
      "Come see The Reverend Johnson perform live at The Longhorn Saloon!",
    genres: ["Blues", "Gospel"],
    keywords: ["live music", "Blues", "Gospel"],
    timeDoor: "2025-04-06T19:29:56.872Z",
    timeStart: "2024-09-17T17:33:52.529Z",
    timeStartPrevious: null,
    timeEnd: "2025-04-29T23:51:15.780Z",
    isPrivate: true,
    isFree: true,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-8"],
    bands: [],
  },
  {
    id: "z1tnvbvv2v",
    name: "The Mesa Mavericks Concert",
    slug: "o7ko6olxx9b",
    image: "https://picsum.photos/200",
    description: "Come see The Mesa Mavericks perform live at The Cactus Club!",
    genres: ["Country", "Red Dirt", "Rock"],
    keywords: ["live music", "Country", "Red Dirt", "Rock"],
    timeDoor: "2025-01-07T05:45:34.808Z",
    timeStart: "2024-12-29T15:19:12.282Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-16T10:45:54.177Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: [],
    venue: "ven-1",
    organizer: null,
    musicians: [],
    bands: ["band-3"],
  },
  {
    id: "vm69xpg25ui",
    name: "Luna Rising Performance",
    slug: "i5fj2e6m1m",
    image: "https://picsum.photos/200",
    description: "Come see Luna Rising perform live at The Longhorn Saloon!",
    genres: ["Indie Folk", "Singer-Songwriter"],
    keywords: ["live music", "Indie Folk", "Singer-Songwriter"],
    timeDoor: "2025-05-26T11:34:34.654Z",
    timeStart: "2025-05-12T04:58:00.042Z",
    timeStartPrevious: null,
    timeEnd: "2025-04-28T01:47:00.470Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-9", "mus-16"],
    bands: [],
  },
  {
    id: "tm74zgqdmi",
    name: "The Coyote Creek Ramblers Concert",
    slug: "e9bafpik1x",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at Mesa Verde Winery!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2025-07-19T18:09:31.082Z",
    timeStart: "2025-04-05T05:07:03.795Z",
    timeStartPrevious: null,
    timeEnd: "2024-10-18T09:18:58.487Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "5ze30gjhu32",
    name: "The Cosmic Cowboy Performance",
    slug: "2xqzj3o6lwz",
    image: "https://picsum.photos/200",
    description:
      "Come see The Cosmic Cowboy perform live at The Longhorn Saloon!",
    genres: ["Psychedelic Country", "Space Rock"],
    keywords: ["live music", "Psychedelic Country", "Space Rock"],
    timeDoor: "2025-07-27T00:59:10.044Z",
    timeStart: "2025-07-12T17:08:07.268Z",
    timeStartPrevious: null,
    timeEnd: "2025-01-18T01:02:03.378Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-20", "mus-20"],
    bands: [],
  },
  {
    id: "4a4mfrjxvku",
    name: "The Desert Roses Concert",
    slug: "1oec0id06mo",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Roses perform live at The Longhorn Saloon!",
    genres: ["Folk", "Rock", "Americana"],
    keywords: ["live music", "Folk", "Rock", "Americana"],
    timeDoor: "2024-12-24T10:03:21.411Z",
    timeStart: "2025-04-08T06:31:35.959Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-18T00:34:34.753Z",
    isPrivate: true,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-1"],
  },
  {
    id: "thmku6v3ht",
    name: "The Reverend Johnson Performance",
    slug: "9x8bzbqm5o7",
    image: "https://picsum.photos/200",
    description:
      "Come see The Reverend Johnson perform live at The Longhorn Saloon!",
    genres: ["Blues", "Gospel"],
    keywords: ["live music", "Blues", "Gospel"],
    timeDoor: "2025-08-07T06:28:00.058Z",
    timeStart: "2024-10-18T14:25:23.265Z",
    timeStartPrevious: null,
    timeEnd: "2024-09-16T23:52:18.174Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-8"],
    bands: [],
  },
  {
    id: "dnucds620sv",
    name: "The Coyote Creek Ramblers Concert",
    slug: "phkih0ex39r",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at Rio Grande Theater!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2024-10-27T09:42:24.860Z",
    timeStart: "2025-05-24T08:08:23.496Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-12T20:56:30.936Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "46jbmundcdk",
    name: "The Canyonland Cowboy Performance",
    slug: "8gb648uyufn",
    image: "https://picsum.photos/200",
    description:
      "Come see The Canyonland Cowboy perform live at The Cactus Club!",
    genres: ["Western Swing", "Cowboy"],
    keywords: ["live music", "Western Swing", "Cowboy"],
    timeDoor: "2025-05-08T18:53:12.159Z",
    timeStart: "2025-06-26T00:35:42.398Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-27T00:49:52.403Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: null,
    musicians: ["mus-15"],
    bands: [],
  },
  {
    id: "r28r2ofq1y",
    name: "Mariachi Sol de Mexico Concert",
    slug: "jneg656aiob",
    image: "https://picsum.photos/200",
    description:
      "Come see Mariachi Sol de Mexico perform live at Mesa Verde Winery!",
    genres: ["Mariachi", "Traditional Mexican"],
    keywords: ["live music", "Mariachi", "Traditional Mexican"],
    timeDoor: "2025-04-18T04:38:23.073Z",
    timeStart: "2025-01-05T19:33:32.139Z",
    timeStartPrevious: null,
    timeEnd: "2025-01-28T01:50:01.029Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-6"],
  },
  {
    id: "m32tidswate",
    name: "Billy Joe Reynolds Performance",
    slug: "2n712a5446u",
    image: "https://picsum.photos/200",
    description:
      "Come see Billy Joe Reynolds perform live at Rio Grande Theater!",
    genres: ["Country", "Western Swing"],
    keywords: ["live music", "Country", "Western Swing"],
    timeDoor: "2024-10-13T05:22:40.858Z",
    timeStart: "2025-07-14T13:49:25.231Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-17T15:58:50.135Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-3", "mus-3"],
    bands: [],
  },
  {
    id: "a89ma4b4l0t",
    name: "Los Chicos del Sol Concert",
    slug: "n8bewvouhin",
    image: "https://picsum.photos/200",
    description:
      "Come see Los Chicos del Sol perform live at Rio Grande Theater!",
    genres: ["Tejano", "Cumbia", "Norteño"],
    keywords: ["live music", "Tejano", "Cumbia", "Norteño"],
    timeDoor: "2025-03-29T11:07:56.402Z",
    timeStart: "2024-09-24T20:09:53.046Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-15T14:41:09.882Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: [],
    bands: ["band-2"],
  },
  {
    id: "ujgl2r6oxfi",
    name: "Carlos Imira Performance",
    slug: "g1d9qqizehh",
    image: "https://picsum.photos/200",
    description: "Come see Carlos Imira perform live at The Starlight Cantina!",
    genres: ["Flamenco", "Spanish Guitar"],
    keywords: ["live music", "Flamenco", "Spanish Guitar"],
    timeDoor: "2025-04-30T04:19:21.603Z",
    timeStart: "2025-06-14T12:31:39.385Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-12T13:23:19.307Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: "org-505",
    musicians: ["mus-7"],
    bands: [],
  },
  {
    id: "rx94wtvq3xj",
    name: "The Desert Roses Concert",
    slug: "6ayfaebfx57",
    image: "https://picsum.photos/200",
    description: "Come see The Desert Roses perform live at Mesa Verde Winery!",
    genres: ["Folk", "Rock", "Americana"],
    keywords: ["live music", "Folk", "Rock", "Americana"],
    timeDoor: "2025-06-02T04:09:32.230Z",
    timeStart: "2025-07-02T05:28:04.020Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-04T09:31:04.388Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-1"],
  },
  {
    id: "3hxirzrxres",
    name: "Cody Thunderbird Performance",
    slug: "22t73gindvj",
    image: "https://picsum.photos/200",
    description: "Come see Cody Thunderbird perform live at Mesa Verde Winery!",
    genres: ["Native American Flute", "World"],
    keywords: ["live music", "Native American Flute", "World"],
    timeDoor: "2024-11-14T20:38:28.075Z",
    timeStart: "2025-02-11T23:46:09.885Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-13T04:22:53.771Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: ["mus-5"],
    bands: [],
  },
  {
    id: "p1r6837dcs",
    name: "The Mesa Mavericks Concert",
    slug: "m9wtsmvt0f",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mesa Mavericks perform live at The Starlight Cantina!",
    genres: ["Country", "Red Dirt", "Rock"],
    keywords: ["live music", "Country", "Red Dirt", "Rock"],
    timeDoor: "2025-03-31T07:21:08.474Z",
    timeStart: "2025-07-12T00:16:08.157Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-25T01:44:04.207Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: "org-505",
    musicians: [],
    bands: ["band-3", "band-2"],
  },
  {
    id: "6mp6ztmrdxl",
    name: "Rosa Mendosa Performance",
    slug: "5gnz4ofsue5",
    image: "https://picsum.photos/200",
    description: "Come see Rosa Mendosa perform live at Mesa Verde Winery!",
    genres: ["Folk", "Americana"],
    keywords: ["live music", "Folk", "Americana"],
    timeDoor: "2025-06-16T12:29:45.604Z",
    timeStart: "2024-10-12T01:50:45.992Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-29T09:57:37.813Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: "org-texmex",
    musicians: ["mus-1"],
    bands: [],
  },
  {
    id: "k5eqxvewwlt",
    name: "The High Desert Gypsies Concert",
    slug: "vk1rcr6vhrm",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at The Longhorn Saloon!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2024-12-15T21:46:30.158Z",
    timeStart: "2025-07-08T01:28:59.098Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-11T22:42:41.462Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-7"],
  },
  {
    id: "dysqqr5fm3m",
    name: "La Reina del Acordeón Performance",
    slug: "mvnswssccu",
    image: "https://picsum.photos/200",
    description:
      "Come see La Reina del Acordeón perform live at The Starlight Cantina!",
    genres: ["Conjunto", "Tejano"],
    keywords: ["live music", "Conjunto", "Tejano"],
    timeDoor: "2024-12-01T18:18:53.838Z",
    timeStart: "2025-01-26T01:37:55.887Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-08T19:05:33.464Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-19"],
    bands: [],
  },
  {
    id: "2a624b8vafe",
    name: "Mariachi Sol de Mexico Concert",
    slug: "jiriaqvor0b",
    image: "https://picsum.photos/200",
    description:
      "Come see Mariachi Sol de Mexico perform live at Mesa Verde Winery!",
    genres: ["Mariachi", "Traditional Mexican"],
    keywords: ["live music", "Mariachi", "Traditional Mexican"],
    timeDoor: "2024-10-03T06:10:51.268Z",
    timeStart: "2025-02-27T16:47:59.219Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-04T13:53:08.699Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: "org-505",
    musicians: [],
    bands: ["band-6"],
  },
  {
    id: "6yj9r7mclkf",
    name: "Carlos Imira Performance",
    slug: "adscb4tvxxq",
    image: "https://picsum.photos/200",
    description: "Come see Carlos Imira perform live at The Cactus Club!",
    genres: ["Flamenco", "Spanish Guitar"],
    keywords: ["live music", "Flamenco", "Spanish Guitar"],
    timeDoor: "2025-04-19T10:30:21.670Z",
    timeStart: "2024-12-26T12:25:43.872Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-25T11:48:10.195Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: [],
    venue: "ven-1",
    organizer: null,
    musicians: ["mus-7"],
    bands: [],
  },
  {
    id: "5o3t6yjcm0m",
    name: "The Coyote Creek Ramblers Concert",
    slug: "qd8hriz4l7",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at The Longhorn Saloon!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2025-04-23T17:26:43.634Z",
    timeStart: "2025-01-29T12:04:59.875Z",
    timeStartPrevious: null,
    timeEnd: "2024-10-28T22:57:33.637Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "k9rvryc01xo",
    name: "The Chile Pepper Picker Performance",
    slug: "fl19zkkh127",
    image: "https://picsum.photos/200",
    description:
      "Come see The Chile Pepper Picker perform live at The Starlight Cantina!",
    genres: ["Bluegrass", "New Mexican"],
    keywords: ["live music", "Bluegrass", "New Mexican"],
    timeDoor: "2025-04-14T14:48:00.162Z",
    timeStart: "2025-04-19T11:04:54.976Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-27T03:55:32.631Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-18"],
    bands: [],
  },
  {
    id: "vgqk9r19ol",
    name: "The Desert Roses Concert",
    slug: "thykjqxg9sm",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Roses perform live at The Starlight Cantina!",
    genres: ["Folk", "Rock", "Americana"],
    keywords: ["live music", "Folk", "Rock", "Americana"],
    timeDoor: "2025-04-02T06:28:26.389Z",
    timeStart: "2025-04-04T06:18:33.662Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-23T13:11:18.804Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-1"],
  },
  {
    id: "iv0twmwbqna",
    name: "The Desert Bloom Orchestra Performance",
    slug: "wplz4v2am8a",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Bloom Orchestra perform live at The Cactus Club!",
    genres: ["Classical", "Orchestral"],
    keywords: ["live music", "Classical", "Orchestral"],
    timeDoor: "2025-04-05T20:53:58.158Z",
    timeStart: "2025-08-16T13:29:47.160Z",
    timeStartPrevious: null,
    timeEnd: "2025-01-25T00:38:09.182Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: null,
    musicians: ["mus-17"],
    bands: [],
  },
  {
    id: "6kuzbejgltc",
    name: "Mariachi Sol de Mexico Concert",
    slug: "ld6s6r78awf",
    image: "https://picsum.photos/200",
    description:
      "Come see Mariachi Sol de Mexico perform live at Rio Grande Theater!",
    genres: ["Mariachi", "Traditional Mexican"],
    keywords: ["live music", "Mariachi", "Traditional Mexican"],
    timeDoor: "2025-03-10T13:56:27.757Z",
    timeStart: "2025-07-10T20:13:35.348Z",
    timeStartPrevious: null,
    timeEnd: "2025-01-28T00:01:45.367Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-2",
    organizer: null,
    musicians: [],
    bands: ["band-6"],
  },
  {
    id: "36iiolen9rv",
    name: "The Desert Bloom Orchestra Performance",
    slug: "k9uwa8qxtb",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Bloom Orchestra perform live at Mesa Verde Winery!",
    genres: ["Classical", "Orchestral"],
    keywords: ["live music", "Classical", "Orchestral"],
    timeDoor: "2025-07-06T21:03:39.340Z",
    timeStart: "2025-05-05T04:57:58.913Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-20T17:41:25.056Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: "org-505",
    musicians: ["mus-17"],
    bands: [],
  },
  {
    id: "z9gqtrgtx8h",
    name: "The High Desert Gypsies Concert",
    slug: "ow3r7k4huk",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at The Starlight Cantina!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2024-11-01T09:57:05.234Z",
    timeStart: "2024-11-28T16:59:53.825Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-25T22:58:37.432Z",
    isPrivate: true,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-7", "band-7"],
  },
  {
    id: "k4tl60cbj",
    name: "Luna Rising Performance",
    slug: "i3zyl7smt5",
    image: "https://picsum.photos/200",
    description: "Come see Luna Rising perform live at The Longhorn Saloon!",
    genres: ["Indie Folk", "Singer-Songwriter"],
    keywords: ["live music", "Indie Folk", "Singer-Songwriter"],
    timeDoor: "2025-02-01T03:57:30.683Z",
    timeStart: "2025-07-28T05:39:06.499Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-14T06:23:35.102Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-9"],
    bands: [],
  },
  {
    id: "zdgntw53jwp",
    name: "The Coyote Creek Ramblers Concert",
    slug: "459wosdm76g",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at Mesa Verde Winery!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2025-04-07T05:51:15.236Z",
    timeStart: "2024-09-28T21:31:44.383Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-15T11:54:06.744Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "tfqyvxzmjej",
    name: "The Canyonland Cowboy Performance",
    slug: "p1jq5audot",
    image: "https://picsum.photos/200",
    description:
      "Come see The Canyonland Cowboy perform live at The Starlight Cantina!",
    genres: ["Western Swing", "Cowboy"],
    keywords: ["live music", "Western Swing", "Cowboy"],
    timeDoor: "2024-11-17T13:52:55.884Z",
    timeStart: "2024-12-03T02:54:19.266Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-29T02:29:00.702Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: true,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-15", "mus-16"],
    bands: [],
  },
  {
    id: "d6wetba4qaj",
    name: "The Mesa Mavericks Concert",
    slug: "wawjjwpv8r9",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mesa Mavericks perform live at The Longhorn Saloon!",
    genres: ["Country", "Red Dirt", "Rock"],
    keywords: ["live music", "Country", "Red Dirt", "Rock"],
    timeDoor: "2025-05-07T23:51:53.432Z",
    timeStart: "2025-07-13T05:59:08.260Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-25T13:56:20.643Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-3"],
  },
  {
    id: "wqj0yjdidi",
    name: "Carlos Imira Performance",
    slug: "o7ytznqqduf",
    image: "https://picsum.photos/200",
    description: "Come see Carlos Imira perform live at Rio Grande Theater!",
    genres: ["Flamenco", "Spanish Guitar"],
    keywords: ["live music", "Flamenco", "Spanish Guitar"],
    timeDoor: "2025-04-14T02:29:22.284Z",
    timeStart: "2025-05-01T23:54:17.853Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-26T20:46:01.273Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-7"],
    bands: [],
  },
  {
    id: "ged6jbc2fa",
    name: "The Desert Roses Concert",
    slug: "2dn0rkufued",
    image: "https://picsum.photos/200",
    description: "Come see The Desert Roses perform live at Mesa Verde Winery!",
    genres: ["Folk", "Rock", "Americana"],
    keywords: ["live music", "Folk", "Rock", "Americana"],
    timeDoor: "2025-01-05T09:41:18.220Z",
    timeStart: "2025-02-21T02:09:55.878Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-01T10:14:32.611Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-1"],
  },
  {
    id: "rrt2yuqcpgf",
    name: "Rosa Mendosa Performance",
    slug: "3rmp6j79w6f",
    image: "https://picsum.photos/200",
    description: "Come see Rosa Mendosa perform live at The Longhorn Saloon!",
    genres: ["Folk", "Americana"],
    keywords: ["live music", "Folk", "Americana"],
    timeDoor: "2025-01-05T11:12:18.192Z",
    timeStart: "2025-08-15T08:24:07.273Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-25T16:13:36.142Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-1", "mus-10"],
    bands: [],
  },
  {
    id: "oa9uwanwrz",
    name: "The Mesa Mavericks Concert",
    slug: "8msbgybjmom",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mesa Mavericks perform live at The Longhorn Saloon!",
    genres: ["Country", "Red Dirt", "Rock"],
    keywords: ["live music", "Country", "Red Dirt", "Rock"],
    timeDoor: "2025-03-22T00:10:55.843Z",
    timeStart: "2025-09-05T03:35:02.937Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-11T19:46:03.747Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-3"],
  },
  {
    id: "fpaio2ax54r",
    name: "Spirit Horse Performance",
    slug: "kgxzwvl059b",
    image: "https://picsum.photos/200",
    description: "Come see Spirit Horse perform live at The Cactus Club!",
    genres: ["Native American Rock", "Alternative"],
    keywords: ["live music", "Native American Rock", "Alternative"],
    timeDoor: "2025-02-17T16:06:24.865Z",
    timeStart: "2024-11-19T09:52:33.145Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-29T18:51:04.650Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: true,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: "org-505",
    musicians: ["mus-16"],
    bands: [],
  },
  {
    id: "2vbu1devhsf",
    name: "The Coyote Creek Ramblers Concert",
    slug: "t89k891edw",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at Rio Grande Theater!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2025-03-29T22:22:37.133Z",
    timeStart: "2024-12-28T12:21:30.059Z",
    timeStartPrevious: null,
    timeEnd: "2024-10-27T06:49:10.455Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "4gzycf5fcqr",
    name: "The Desert Bloom Orchestra Performance",
    slug: "33385555bj3",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Bloom Orchestra perform live at Mesa Verde Winery!",
    genres: ["Classical", "Orchestral"],
    keywords: ["live music", "Classical", "Orchestral"],
    timeDoor: "2025-05-05T00:28:59.081Z",
    timeStart: "2024-10-04T08:02:10.479Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-15T01:30:01.414Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: ["mus-17"],
    bands: [],
  },
  {
    id: "3xq724zgamj",
    name: "The Mesa Mavericks Concert",
    slug: "693afjo2gya",
    image: "https://picsum.photos/200",
    description: "Come see The Mesa Mavericks perform live at The Cactus Club!",
    genres: ["Country", "Red Dirt", "Rock"],
    keywords: ["live music", "Country", "Red Dirt", "Rock"],
    timeDoor: "2024-11-29T22:14:32.952Z",
    timeStart: "2024-10-22T19:08:14.542Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-28T19:01:57.574Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: null,
    musicians: [],
    bands: ["band-3"],
  },
  {
    id: "bozs7en0nb5",
    name: "El Trio Romántico Performance",
    slug: "1ca47wh7ew2",
    image: "https://picsum.photos/200",
    description:
      "Come see El Trio Romántico perform live at Rio Grande Theater!",
    genres: ["Bolero", "Ranchera"],
    keywords: ["live music", "Bolero", "Ranchera"],
    timeDoor: "2025-03-05T17:42:34.656Z",
    timeStart: "2024-10-27T17:04:03.407Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-16T12:49:45.295Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-14", "mus-8"],
    bands: [],
  },
  {
    id: "9oeowacbhrw",
    name: "The Coyote Creek Ramblers Concert",
    slug: "lvtaswb4e2",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at Rio Grande Theater!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2024-12-02T10:26:07.233Z",
    timeStart: "2025-02-08T12:43:30.552Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-02T00:19:37.316Z",
    isPrivate: true,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "f782o9yxwmp",
    name: "Cody Thunderbird Performance",
    slug: "hxg8eekk93r",
    image: "https://picsum.photos/200",
    description:
      "Come see Cody Thunderbird perform live at Rio Grande Theater!",
    genres: ["Native American Flute", "World"],
    keywords: ["live music", "Native American Flute", "World"],
    timeDoor: "2025-09-02T17:42:17.793Z",
    timeStart: "2025-02-12T05:25:18.098Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-16T15:38:38.387Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-5"],
    bands: [],
  },
  {
    id: "mpeswc6ybxk",
    name: "The High Desert Gypsies Concert",
    slug: "24hlwohz7qm",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at Mesa Verde Winery!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2025-01-02T05:24:17.233Z",
    timeStart: "2025-06-29T13:41:29.289Z",
    timeStartPrevious: null,
    timeEnd: "2025-05-10T08:33:56.780Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-7"],
  },
  {
    id: "oozabokihv",
    name: "El Trio Romántico Performance",
    slug: "caq79qddlgl",
    image: "https://picsum.photos/200",
    description:
      "Come see El Trio Romántico perform live at Rio Grande Theater!",
    genres: ["Bolero", "Ranchera"],
    keywords: ["live music", "Bolero", "Ranchera"],
    timeDoor: "2025-07-18T12:48:39.963Z",
    timeStart: "2025-01-07T23:13:52.486Z",
    timeStartPrevious: null,
    timeEnd: "2025-01-17T17:05:23.857Z",
    isPrivate: true,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-14"],
    bands: [],
  },
  {
    id: "tcqboo9gbqq",
    name: "The Desert Roses Concert",
    slug: "d5fliwl3ao",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Roses perform live at The Starlight Cantina!",
    genres: ["Folk", "Rock", "Americana"],
    keywords: ["live music", "Folk", "Rock", "Americana"],
    timeDoor: "2025-05-03T12:11:01.009Z",
    timeStart: "2025-01-26T02:32:18.398Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-14T16:26:07.633Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-1"],
  },
  {
    id: "xeoff49h1nh",
    name: "DJ Cactus Jack Performance",
    slug: "3b1bnnkhyad",
    image: "https://picsum.photos/200",
    description:
      "Come see DJ Cactus Jack perform live at The Starlight Cantina!",
    genres: ["Cumbia", "Latin Electronic"],
    keywords: ["live music", "Cumbia", "Latin Electronic"],
    timeDoor: "2025-06-26T12:53:02.372Z",
    timeStart: "2024-12-28T16:25:46.086Z",
    timeStartPrevious: null,
    timeEnd: "2025-04-02T09:56:37.111Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: [],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-10"],
    bands: [],
  },
  {
    id: "63qhpti7o4",
    name: "Los Chicos del Sol Concert",
    slug: "6szj372rh0b",
    image: "https://picsum.photos/200",
    description:
      "Come see Los Chicos del Sol perform live at Mesa Verde Winery!",
    genres: ["Tejano", "Cumbia", "Norteño"],
    keywords: ["live music", "Tejano", "Cumbia", "Norteño"],
    timeDoor: "2025-03-31T13:30:03.483Z",
    timeStart: "2025-01-31T07:10:36.841Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-31T16:45:09.433Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: "org-505",
    musicians: [],
    bands: ["band-2"],
  },
  {
    id: "gr3fl7b1ty6",
    name: "Rosa Mendosa Performance",
    slug: "30lk6gzh5qr",
    image: "https://picsum.photos/200",
    description: "Come see Rosa Mendosa perform live at The Longhorn Saloon!",
    genres: ["Folk", "Americana"],
    keywords: ["live music", "Folk", "Americana"],
    timeDoor: "2024-10-23T15:17:47.539Z",
    timeStart: "2024-12-19T03:45:00.070Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-09T09:32:51.481Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-1"],
    bands: [],
  },
  {
    id: "iiluoi8jhj",
    name: "Mariachi Sol de Mexico Concert",
    slug: "n7kz7mtmyol",
    image: "https://picsum.photos/200",
    description:
      "Come see Mariachi Sol de Mexico perform live at Mesa Verde Winery!",
    genres: ["Mariachi", "Traditional Mexican"],
    keywords: ["live music", "Mariachi", "Traditional Mexican"],
    timeDoor: "2024-12-28T11:42:29.319Z",
    timeStart: "2024-12-14T19:44:15.551Z",
    timeStartPrevious: null,
    timeEnd: "2024-10-25T12:11:36.965Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: true,
    isHoliday: true,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-6"],
  },
  {
    id: "eelismy2pzj",
    name: "The Reverend Johnson Performance",
    slug: "lqof5u6n15c",
    image: "https://picsum.photos/200",
    description:
      "Come see The Reverend Johnson perform live at Rio Grande Theater!",
    genres: ["Blues", "Gospel"],
    keywords: ["live music", "Blues", "Gospel"],
    timeDoor: "2025-06-07T20:40:24.910Z",
    timeStart: "2024-10-25T14:17:52.687Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-30T07:12:27.406Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-8"],
    bands: [],
  },
  {
    id: "7k8znogqpd8",
    name: "The Mesa Mavericks Concert",
    slug: "04hzk25v9pv8",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mesa Mavericks perform live at Rio Grande Theater!",
    genres: ["Country", "Red Dirt", "Rock"],
    keywords: ["live music", "Country", "Red Dirt", "Rock"],
    timeDoor: "2024-09-21T01:15:38.783Z",
    timeStart: "2025-05-10T11:47:42.831Z",
    timeStartPrevious: null,
    timeEnd: "2024-09-28T13:22:57.902Z",
    isPrivate: true,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: "org-505",
    musicians: [],
    bands: ["band-3"],
  },
  {
    id: "78bqe78tgbm",
    name: "Spirit Horse Performance",
    slug: "if8zib1rw5f",
    image: "https://picsum.photos/200",
    description: "Come see Spirit Horse perform live at The Cactus Club!",
    genres: ["Native American Rock", "Alternative"],
    keywords: ["live music", "Native American Rock", "Alternative"],
    timeDoor: "2025-09-12T14:06:36.165Z",
    timeStart: "2024-12-10T22:54:23.512Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-05T02:12:50.747Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-1",
    organizer: "org-505",
    musicians: ["mus-16"],
    bands: [],
  },
  {
    id: "oowogbwn4ia",
    name: "The Desert Roses Concert",
    slug: "yw3srtf0wp",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Roses perform live at The Starlight Cantina!",
    genres: ["Folk", "Rock", "Americana"],
    keywords: ["live music", "Folk", "Rock", "Americana"],
    timeDoor: "2025-08-29T23:24:18.999Z",
    timeStart: "2024-10-11T20:38:37.313Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-10T07:36:10.770Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-3",
    organizer: "org-texmex",
    musicians: [],
    bands: ["band-1"],
  },
  {
    id: "y2cppgb35dq",
    name: "The Dust Bowl Troubadour Performance",
    slug: "sany6nmszu",
    image: "https://picsum.photos/200",
    description:
      "Come see The Dust Bowl Troubadour perform live at The Cactus Club!",
    genres: ["Folk", "Roots"],
    keywords: ["live music", "Folk", "Roots"],
    timeDoor: "2025-02-26T15:16:29.982Z",
    timeStart: "2025-04-22T17:33:48.993Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-19T11:27:46.324Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: null,
    musicians: ["mus-13"],
    bands: [],
  },
  {
    id: "2g1tq1lbpvd",
    name: "The Coyote Creek Ramblers Concert",
    slug: "dwjmtbqadg6",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at The Longhorn Saloon!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2024-10-15T16:58:01.807Z",
    timeStart: "2025-06-09T23:42:05.371Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-06T13:04:43.146Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "rve3na2721f",
    name: "The Desert Bloom Orchestra Performance",
    slug: "sf524m3kick",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Bloom Orchestra perform live at Mesa Verde Winery!",
    genres: ["Classical", "Orchestral"],
    keywords: ["live music", "Classical", "Orchestral"],
    timeDoor: "2024-10-13T03:51:44.084Z",
    timeStart: "2024-11-24T22:39:11.728Z",
    timeStartPrevious: null,
    timeEnd: "2024-10-13T19:46:37.488Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: ["mus-17"],
    bands: [],
  },
  {
    id: "pjh3bfqau7c",
    name: "Navajo Nation Drummers Concert",
    slug: "6c8wa2x2iph",
    image: "https://picsum.photos/200",
    description:
      "Come see Navajo Nation Drummers perform live at The Cactus Club!",
    genres: ["Traditional", "Native American", "World"],
    keywords: ["live music", "Traditional", "Native American", "World"],
    timeDoor: "2025-04-12T09:49:40.256Z",
    timeStart: "2025-08-26T14:15:12.217Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-05T06:47:56.704Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-1",
    organizer: null,
    musicians: [],
    bands: ["band-4"],
  },
  {
    id: "yzmzp5e9tul",
    name: "Sierra Dawn Performance",
    slug: "legh4sjp37f",
    image: "https://picsum.photos/200",
    description: "Come see Sierra Dawn perform live at The Starlight Cantina!",
    genres: ["Bluegrass", "Folk"],
    keywords: ["live music", "Bluegrass", "Folk"],
    timeDoor: "2025-08-19T12:03:43.819Z",
    timeStart: "2025-01-28T11:59:56.488Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-27T06:33:50.749Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-6"],
    bands: [],
  },
  {
    id: "4p9a056zkeb",
    name: "The High Desert Gypsies Concert",
    slug: "1k8ff0wsa6p",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at The Cactus Club!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2025-06-05T23:22:12.633Z",
    timeStart: "2025-04-27T23:11:47.205Z",
    timeStartPrevious: null,
    timeEnd: "2025-04-18T22:38:23.250Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: null,
    musicians: [],
    bands: ["band-7"],
  },
  {
    id: "6ievsuonobf",
    name: "The Canyonland Cowboy Performance",
    slug: "1c5jol0w74o",
    image: "https://picsum.photos/200",
    description:
      "Come see The Canyonland Cowboy perform live at Rio Grande Theater!",
    genres: ["Western Swing", "Cowboy"],
    keywords: ["live music", "Western Swing", "Cowboy"],
    timeDoor: "2025-08-22T01:07:01.047Z",
    timeStart: "2025-02-08T19:36:50.349Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-13T20:08:30.950Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-15"],
    bands: [],
  },
  {
    id: "3td1fa8tvja",
    name: "The Coyote Creek Ramblers Concert",
    slug: "p1z7ydkmzl7",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at Rio Grande Theater!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2024-10-15T02:44:14.005Z",
    timeStart: "2025-06-05T11:17:56.231Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-19T18:26:22.463Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: "org-505",
    musicians: [],
    bands: ["band-5", "band-1"],
  },
  {
    id: "mdzcwlzeux",
    name: "The Mariachi Diva Performance",
    slug: "69l5mbvdaxo",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mariachi Diva perform live at Rio Grande Theater!",
    genres: ["Mariachi", "Feminist"],
    keywords: ["live music", "Mariachi", "Feminist"],
    timeDoor: "2024-12-07T00:02:23.277Z",
    timeStart: "2025-03-11T09:22:58.658Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-31T06:41:14.789Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: "org-texmex",
    musicians: ["mus-12"],
    bands: [],
  },
  {
    id: "5rojh4nxeia",
    name: "Los Chicos del Sol Concert",
    slug: "ozr8em6gf4e",
    image: "https://picsum.photos/200",
    description: "Come see Los Chicos del Sol perform live at The Cactus Club!",
    genres: ["Tejano", "Cumbia", "Norteño"],
    keywords: ["live music", "Tejano", "Cumbia", "Norteño"],
    timeDoor: "2025-07-29T05:18:12.949Z",
    timeStart: "2025-09-07T17:46:56.783Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-25T15:09:20.366Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: "org-505",
    musicians: [],
    bands: ["band-2"],
  },
  {
    id: "cg9b2hg0kmk",
    name: "Javier Hernandez Performance",
    slug: "m1wdztip6tf",
    image: "https://picsum.photos/200",
    description: "Come see Javier Hernandez perform live at The Cactus Club!",
    genres: ["Tejano", "Conjunto"],
    keywords: ["live music", "Tejano", "Conjunto"],
    timeDoor: "2025-06-03T15:43:56.106Z",
    timeStart: "2025-01-31T11:52:54.404Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-24T16:06:24.109Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: "org-505",
    musicians: ["mus-2"],
    bands: [],
  },
  {
    id: "9xob3oryj58",
    name: "The Coyote Creek Ramblers Concert",
    slug: "x1apn5m1nmq",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at The Starlight Cantina!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2024-09-30T03:08:52.169Z",
    timeStart: "2024-11-06T23:36:51.457Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-31T16:26:56.505Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "1p4gtjuoyqz",
    name: "The Reverend Johnson Performance",
    slug: "k2hqtr4jec",
    image: "https://picsum.photos/200",
    description:
      "Come see The Reverend Johnson perform live at Mesa Verde Winery!",
    genres: ["Blues", "Gospel"],
    keywords: ["live music", "Blues", "Gospel"],
    timeDoor: "2025-06-12T13:26:48.185Z",
    timeStart: "2024-10-24T20:31:01.422Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-17T13:37:20.940Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: ["mus-8"],
    bands: [],
  },
  {
    id: "6lqs7sscn4x",
    name: "Mariachi Sol de Mexico Concert",
    slug: "nln4rox1rtp",
    image: "https://picsum.photos/200",
    description:
      "Come see Mariachi Sol de Mexico perform live at The Longhorn Saloon!",
    genres: ["Mariachi", "Traditional Mexican"],
    keywords: ["live music", "Mariachi", "Traditional Mexican"],
    timeDoor: "2024-10-02T05:08:39.797Z",
    timeStart: "2025-04-19T13:58:54.092Z",
    timeStartPrevious: null,
    timeEnd: "2025-04-26T08:41:26.905Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-6"],
  },
  {
    id: "r8ier943uo",
    name: "The Dust Bowl Troubadour Performance",
    slug: "20ttcyuuvuuj",
    image: "https://picsum.photos/200",
    description:
      "Come see The Dust Bowl Troubadour perform live at Mesa Verde Winery!",
    genres: ["Folk", "Roots"],
    keywords: ["live music", "Folk", "Roots"],
    timeDoor: "2025-01-03T00:26:52.469Z",
    timeStart: "2025-02-10T05:24:33.776Z",
    timeStartPrevious: null,
    timeEnd: "2025-04-28T10:44:36.737Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: "org-505",
    musicians: ["mus-13", "mus-6"],
    bands: [],
  },
  {
    id: "h3alfsqzmth",
    name: "The High Desert Gypsies Concert",
    slug: "zp51rm6ncxm",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at The Longhorn Saloon!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2025-01-17T21:27:44.557Z",
    timeStart: "2024-11-08T13:31:21.154Z",
    timeStartPrevious: null,
    timeEnd: "2025-02-06T02:59:52.918Z",
    isPrivate: true,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-7"],
  },
  {
    id: "j9mks77e07",
    name: "Cody Thunderbird Performance",
    slug: "z9avbg2b5o",
    image: "https://picsum.photos/200",
    description:
      "Come see Cody Thunderbird perform live at Rio Grande Theater!",
    genres: ["Native American Flute", "World"],
    keywords: ["live music", "Native American Flute", "World"],
    timeDoor: "2025-05-12T02:36:32.286Z",
    timeStart: "2025-07-05T11:50:19.319Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-15T00:27:51.323Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-5"],
    bands: [],
  },
  {
    id: "jc0dshq88bj",
    name: "The High Desert Gypsies Concert",
    slug: "t79f3nh4ue",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at The Starlight Cantina!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2025-05-22T00:30:48.079Z",
    timeStart: "2024-12-13T21:29:50.311Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-02T20:59:25.402Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-7"],
  },
  {
    id: "j3us4740xfd",
    name: "El Trio Romántico Performance",
    slug: "2151ak2e0f4j",
    image: "https://picsum.photos/200",
    description:
      "Come see El Trio Romántico perform live at The Longhorn Saloon!",
    genres: ["Bolero", "Ranchera"],
    keywords: ["live music", "Bolero", "Ranchera"],
    timeDoor: "2025-07-04T02:57:26.344Z",
    timeStart: "2024-12-29T14:18:43.853Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-31T07:43:54.042Z",
    isPrivate: true,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: "org-505",
    musicians: ["mus-14"],
    bands: [],
  },
  {
    id: "dibvpy11wya",
    name: "The Desert Roses Concert",
    slug: "j6wemzi56eh",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Roses perform live at The Starlight Cantina!",
    genres: ["Folk", "Rock", "Americana"],
    keywords: ["live music", "Folk", "Rock", "Americana"],
    timeDoor: "2024-11-30T04:59:14.305Z",
    timeStart: "2024-10-23T06:42:49.688Z",
    timeStartPrevious: null,
    timeEnd: "2024-09-21T19:37:57.570Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-1"],
  },
  {
    id: "z6nycunrmj",
    name: "The Mariachi Diva Performance",
    slug: "150p3cdewwn",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mariachi Diva perform live at Mesa Verde Winery!",
    genres: ["Mariachi", "Feminist"],
    keywords: ["live music", "Mariachi", "Feminist"],
    timeDoor: "2025-06-16T21:23:07.016Z",
    timeStart: "2025-08-30T04:21:47.061Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-24T16:54:08.544Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: ["mus-12"],
    bands: [],
  },
  {
    id: "hwxvwfwk3ic",
    name: "Navajo Nation Drummers Concert",
    slug: "j0jzob0ihag",
    image: "https://picsum.photos/200",
    description:
      "Come see Navajo Nation Drummers perform live at The Longhorn Saloon!",
    genres: ["Traditional", "Native American", "World"],
    keywords: ["live music", "Traditional", "Native American", "World"],
    timeDoor: "2025-05-14T06:49:11.983Z",
    timeStart: "2025-08-21T12:53:48.829Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-20T21:11:11.209Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-4"],
  },
  {
    id: "wem8hekoyyr",
    name: "Leticia Gutierrez Performance",
    slug: "5kzztchsgks",
    image: "https://picsum.photos/200",
    description:
      "Come see Leticia Gutierrez perform live at The Starlight Cantina!",
    genres: ["Norteño", "Ranchera"],
    keywords: ["live music", "Norteño", "Ranchera"],
    timeDoor: "2024-11-03T03:55:42.971Z",
    timeStart: "2025-06-23T14:36:17.927Z",
    timeStartPrevious: null,
    timeEnd: "2025-04-05T07:42:05.317Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-4"],
    bands: [],
  },
  {
    id: "sbclpn7qvqe",
    name: "Los Chicos del Sol Concert",
    slug: "oslrq7zw10q",
    image: "https://picsum.photos/200",
    description:
      "Come see Los Chicos del Sol perform live at Mesa Verde Winery!",
    genres: ["Tejano", "Cumbia", "Norteño"],
    keywords: ["live music", "Tejano", "Cumbia", "Norteño"],
    timeDoor: "2025-01-31T07:53:29.161Z",
    timeStart: "2025-01-15T12:32:15.474Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-29T13:14:24.139Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-2"],
  },
  {
    id: "1i5oalogxem",
    name: "The Desert Bloom Orchestra Performance",
    slug: "ptadbmskyiq",
    image: "https://picsum.photos/200",
    description:
      "Come see The Desert Bloom Orchestra perform live at Rio Grande Theater!",
    genres: ["Classical", "Orchestral"],
    keywords: ["live music", "Classical", "Orchestral"],
    timeDoor: "2025-06-15T15:09:47.796Z",
    timeStart: "2025-08-18T20:10:24.942Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-05T21:07:30.992Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: null,
    musicians: ["mus-17"],
    bands: [],
  },
  {
    id: "yhjx7tgrb1",
    name: "Mariachi Sol de Mexico Concert",
    slug: "c3rqvuvurj",
    image: "https://picsum.photos/200",
    description:
      "Come see Mariachi Sol de Mexico perform live at Rio Grande Theater!",
    genres: ["Mariachi", "Traditional Mexican"],
    keywords: ["live music", "Mariachi", "Traditional Mexican"],
    timeDoor: "2025-01-26T19:30:03.427Z",
    timeStart: "2024-09-30T05:04:52.271Z",
    timeStartPrevious: null,
    timeEnd: "2025-02-08T00:38:09.699Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: false,
    servesFood: false,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-2",
    organizer: "org-505",
    musicians: [],
    bands: ["band-6"],
  },
  {
    id: "zs4vyp3717e",
    name: "The Red Rock Rapper Performance",
    slug: "nyjlfs6azv",
    image: "https://picsum.photos/200",
    description:
      "Come see The Red Rock Rapper perform live at The Cactus Club!",
    genres: ["Hip Hop", "Conscious Rap"],
    keywords: ["live music", "Hip Hop", "Conscious Rap"],
    timeDoor: "2025-03-09T19:17:26.630Z",
    timeStart: "2025-08-22T15:31:37.968Z",
    timeStartPrevious: null,
    timeEnd: "2024-10-14T13:47:39.674Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: null,
    musicians: ["mus-11", "mus-10"],
    bands: [],
  },
  {
    id: "eg8oxbqk7jq",
    name: "The High Desert Gypsies Concert",
    slug: "3t59bys1oa",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at The Starlight Cantina!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2025-06-09T12:32:13.669Z",
    timeStart: "2025-05-14T02:46:38.373Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-18T03:51:56.894Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: true,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-7", "band-2"],
  },
  {
    id: "t9mdld3rp5",
    name: "The Reverend Johnson Performance",
    slug: "h2i83mc4719",
    image: "https://picsum.photos/200",
    description:
      "Come see The Reverend Johnson perform live at The Starlight Cantina!",
    genres: ["Blues", "Gospel"],
    keywords: ["live music", "Blues", "Gospel"],
    timeDoor: "2025-02-06T23:48:06.284Z",
    timeStart: "2025-04-16T05:04:40.822Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-21T11:14:45.771Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-8"],
    bands: [],
  },
  {
    id: "5ufgipm6rjo",
    name: "The Mesa Mavericks Concert",
    slug: "wbswdgxr7rk",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mesa Mavericks perform live at The Longhorn Saloon!",
    genres: ["Country", "Red Dirt", "Rock"],
    keywords: ["live music", "Country", "Red Dirt", "Rock"],
    timeDoor: "2025-02-05T21:50:50.017Z",
    timeStart: "2024-09-19T18:13:57.475Z",
    timeStartPrevious: null,
    timeEnd: "2024-10-26T03:58:30.287Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: "org-505",
    musicians: [],
    bands: ["band-3"],
  },
  {
    id: "ppfs58to7df",
    name: "The Canyonland Cowboy Performance",
    slug: "netzbgighv",
    image: "https://picsum.photos/200",
    description:
      "Come see The Canyonland Cowboy perform live at The Cactus Club!",
    genres: ["Western Swing", "Cowboy"],
    keywords: ["live music", "Western Swing", "Cowboy"],
    timeDoor: "2025-04-05T08:47:19.623Z",
    timeStart: "2025-08-30T03:24:52.179Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-27T11:21:15.313Z",
    isPrivate: true,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: "org-texmex",
    musicians: ["mus-15", "mus-14"],
    bands: [],
  },
  {
    id: "qed5m7ncpjs",
    name: "The High Desert Gypsies Concert",
    slug: "ks6ahqmxllf",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at Mesa Verde Winery!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2024-10-13T13:27:40.871Z",
    timeStart: "2024-12-12T03:59:31.631Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-21T13:58:11.338Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-7"],
  },
  {
    id: "v8yb26f5wjc",
    name: "DJ Cactus Jack Performance",
    slug: "dvuij5xlsl8",
    image: "https://picsum.photos/200",
    description: "Come see DJ Cactus Jack perform live at The Longhorn Saloon!",
    genres: ["Cumbia", "Latin Electronic"],
    keywords: ["live music", "Cumbia", "Latin Electronic"],
    timeDoor: "2025-05-06T03:01:02.836Z",
    timeStart: "2025-02-23T09:43:02.004Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-10T03:33:15.973Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-10"],
    bands: [],
  },
  {
    id: "fms4x2u3aj5",
    name: "Navajo Nation Drummers Concert",
    slug: "d1o2l1dwa7c",
    image: "https://picsum.photos/200",
    description:
      "Come see Navajo Nation Drummers perform live at The Starlight Cantina!",
    genres: ["Traditional", "Native American", "World"],
    keywords: ["live music", "Traditional", "Native American", "World"],
    timeDoor: "2025-02-19T16:55:42.466Z",
    timeStart: "2025-06-30T12:06:16.940Z",
    timeStartPrevious: null,
    timeEnd: "2024-12-12T20:18:49.055Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: [],
    bands: ["band-4"],
  },
  {
    id: "ftix1zqjvw",
    name: "The Mariachi Diva Performance",
    slug: "hqykmn14u4",
    image: "https://picsum.photos/200",
    description:
      "Come see The Mariachi Diva perform live at The Longhorn Saloon!",
    genres: ["Mariachi", "Feminist"],
    keywords: ["live music", "Mariachi", "Feminist"],
    timeDoor: "2025-05-13T00:22:35.898Z",
    timeStart: "2024-12-21T04:20:47.778Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-08T00:32:57.232Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-12"],
    bands: [],
  },
  {
    id: "qzvyewy2go8",
    name: "The Coyote Creek Ramblers Concert",
    slug: "6s3cwa9vfwj",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at Mesa Verde Winery!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2024-11-14T21:21:24.808Z",
    timeStart: "2024-10-29T19:36:06.790Z",
    timeStartPrevious: null,
    timeEnd: "2025-07-02T11:49:36.492Z",
    isPrivate: true,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "w09743rb9vf",
    name: "Billy Joe Reynolds Performance",
    slug: "cfke3g3pcvk",
    image: "https://picsum.photos/200",
    description:
      "Come see Billy Joe Reynolds perform live at The Longhorn Saloon!",
    genres: ["Country", "Western Swing"],
    keywords: ["live music", "Country", "Western Swing"],
    timeDoor: "2024-11-15T13:21:07.111Z",
    timeStart: "2025-08-14T10:10:58.829Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-30T05:28:10.363Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: ["mus-3", "mus-18"],
    bands: [],
  },
  {
    id: "olpc3hk9apq",
    name: "The High Desert Gypsies Concert",
    slug: "q1ewj0y325",
    image: "https://picsum.photos/200",
    description:
      "Come see The High Desert Gypsies perform live at Mesa Verde Winery!",
    genres: ["Psychedelic Rock", "Desert Rock", "Alternative"],
    keywords: ["live music", "Psychedelic Rock", "Desert Rock", "Alternative"],
    timeDoor: "2025-08-07T22:36:19.457Z",
    timeStart: "2025-03-31T21:26:15.696Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-29T05:24:56.053Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    rsvpLink: "https://www.example.com/rsvp",
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: "org-505",
    musicians: [],
    bands: ["band-7"],
  },
  {
    id: "tg4da1tmdbf",
    name: "Javier Hernandez Performance",
    slug: "jshxtzn6rjd",
    image: "https://picsum.photos/200",
    description: "Come see Javier Hernandez perform live at Mesa Verde Winery!",
    genres: ["Tejano", "Conjunto"],
    keywords: ["live music", "Tejano", "Conjunto"],
    timeDoor: "2024-12-13T23:25:33.396Z",
    timeStart: "2025-05-09T09:12:27.937Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-07T05:07:49.727Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: ["mus-2"],
    bands: [],
  },
  {
    id: "x3my6ijky9",
    name: "Navajo Nation Drummers Concert",
    slug: "5gplc3qtryr",
    image: "https://picsum.photos/200",
    description:
      "Come see Navajo Nation Drummers perform live at The Longhorn Saloon!",
    genres: ["Traditional", "Native American", "World"],
    keywords: ["live music", "Traditional", "Native American", "World"],
    timeDoor: "2025-04-21T16:16:04.011Z",
    timeStart: "2025-03-19T14:54:21.775Z",
    timeStartPrevious: null,
    timeEnd: "2025-08-19T00:33:47.033Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-4"],
  },
  {
    id: "wbi4qruvqw",
    name: "The Dust Bowl Troubadour Performance",
    slug: "1t0h6bny5ok",
    image: "https://picsum.photos/200",
    description:
      "Come see The Dust Bowl Troubadour perform live at The Starlight Cantina!",
    genres: ["Folk", "Roots"],
    keywords: ["live music", "Folk", "Roots"],
    timeDoor: "2024-10-12T19:19:19.441Z",
    timeStart: "2025-05-31T01:16:18.625Z",
    timeStartPrevious: null,
    timeEnd: "2024-11-12T13:43:49.524Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-3",
    organizer: null,
    musicians: ["mus-13"],
    bands: [],
  },
  {
    id: "w8kqsfqmmbk",
    name: "Navajo Nation Drummers Concert",
    slug: "cws8b3h0n5",
    image: "https://picsum.photos/200",
    description:
      "Come see Navajo Nation Drummers perform live at The Longhorn Saloon!",
    genres: ["Traditional", "Native American", "World"],
    keywords: ["live music", "Traditional", "Native American", "World"],
    timeDoor: "2025-01-06T12:02:40.315Z",
    timeStart: "2025-03-17T10:24:04.774Z",
    timeStartPrevious: null,
    timeEnd: "2025-01-17T19:12:15.573Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: true,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: [],
    venue: "ven-5",
    organizer: null,
    musicians: [],
    bands: ["band-4"],
  },
  {
    id: "7hz7on89no5",
    name: "Rosa Mendosa Performance",
    slug: "7r5guipo0rd",
    image: "https://picsum.photos/200",
    description: "Come see Rosa Mendosa perform live at Mesa Verde Winery!",
    genres: ["Folk", "Americana"],
    keywords: ["live music", "Folk", "Americana"],
    timeDoor: "2025-06-17T00:59:37.799Z",
    timeStart: "2024-10-08T16:02:53.256Z",
    timeStartPrevious: null,
    timeEnd: "2025-03-07T07:11:54.776Z",
    isPrivate: false,
    isFree: true,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: false,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: "org-505",
    musicians: ["mus-1", "mus-1"],
    bands: [],
  },
  {
    id: "bcz2aiyivlv",
    name: "The Coyote Creek Ramblers Concert",
    slug: "nw505m7ye7",
    image: "https://picsum.photos/200",
    description:
      "Come see The Coyote Creek Ramblers perform live at The Cactus Club!",
    genres: ["Bluegrass", "Folk", "Americana"],
    keywords: ["live music", "Bluegrass", "Folk", "Americana"],
    timeDoor: "2024-12-11T05:14:29.889Z",
    timeStart: "2025-08-20T11:33:29.650Z",
    timeStartPrevious: null,
    timeEnd: "2025-05-07T20:58:25.004Z",
    isPrivate: true,
    isFree: false,
    isChildFriendly: false,
    isHoliday: true,
    ageRestriction: false,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: false,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-1",
    organizer: null,
    musicians: [],
    bands: ["band-5"],
  },
  {
    id: "12xxzo0fz3os",
    name: "Leticia Gutierrez Performance",
    slug: "z3z4p5jafp7",
    image: "https://picsum.photos/200",
    description:
      "Come see Leticia Gutierrez perform live at Mesa Verde Winery!",
    genres: ["Norteño", "Ranchera"],
    keywords: ["live music", "Norteño", "Ranchera"],
    timeDoor: "2025-02-05T09:16:56.844Z",
    timeStart: "2024-12-08T17:25:28.072Z",
    timeStartPrevious: null,
    timeEnd: "2025-06-19T22:25:04.924Z",
    isPrivate: false,
    isFree: false,
    isChildFriendly: false,
    isHoliday: false,
    ageRestriction: true,
    minimumAge: 21,
    servesAlcohol: true,
    servesFood: true,
    requiresRsvp: true,
    requiresTicket: true,
    ticketLinks: ["https://www.example.com/tickets"],
    venue: "ven-4",
    organizer: null,
    musicians: ["mus-4"],
    bands: [],
  },
];
