import {
  Bookmark,
  CalendarCog,
  CalendarDays,
  Cog,
  Compass,
  Contact,
  Grid2x2,
  Heart,
  Info,
  Network,
  Store,
  Ticket,
  UserCog,
  Users2,
} from "@repo/ui/icons";

export const links = {
  marketing: [
    {
      name: "About",
      href: "/about",
      icon: Info,
      brief: "Learn about our company",
      seo: "About Us - Company Information, Mission, and Values",
    },
    {
      name: "Contact",
      href: "/contact",
      icon: Info,
      brief: "Get in touch with us",
      seo: "Contact Us - Customer Support, Inquiries, and Feedback",
    },
    {
      name: "Features",
      href: "/features",
      icon: Info,
      brief: "Discover our platform's features",
      seo: "Platform Features - Key Benefits and Functionalities",
    },
    {
      name: "Pricing",
      href: "/pricing",
      icon: Info,
      brief: "View our pricing plans",
      seo: "Pricing Plans - Subscription Options and Costs",
    },
    {
      name: "Privacy",
      href: "/privacy",
      icon: Info,
      brief: "Read our privacy policy",
      seo: "Privacy Policy - Data Collection and Usage Practices",
    },
    {
      name: "Support",
      href: "/support",
      icon: Info,
      brief: "Ways to contribute and help us grow",
      seo: "Support Our Mission - Donate, Invest, or Share",
    },
    {
      name: "Terms & Conditions",
      href: "/terms",
      icon: Info,
      brief: "Review our terms and conditions",
      seo: "Terms and Conditions - Legal Agreement and User Guidelines",
    },
  ],
  explore: [
    {
      name: "Explore",
      href: "/explore",
      icon: Compass,
      brief: "Discover events, performers, and venues",
      seo: "Explore Live Music Events, Performers, and Venues Near You",
    },
    {
      name: "Upcoming Events",
      href: "/explore/events",
      icon: CalendarDays,
      brief: "Find upcoming events",
      seo: "Upcoming Live Music Events - Concerts, Festivals, and Shows",
    },
    {
      name: "Performers",
      href: "/explore/performers",
      icon: Users2,
      brief: "Browse performers and artists",
      seo: "Discover Musicians, Bands, and Performers",
    },
    {
      name: "Venues",
      href: "/explore/venues",
      icon: Store,
      brief: "Explore music venues",
      seo: "Find Concert Halls, Clubs, and Music Venues",
    },
    {
      name: "Event Organizers",
      href: "/explore/organizers",
      icon: Network,
      brief: "Connect with event organizers",
      seo: "Event Organizers and Promoters - Find and Connect",
    },
  ],
  manage: [
    {
      name: "Dashboard",
      href: "/manage",
      icon: Grid2x2,
      brief: "Overview of your account",
      seo: "Admin Dashboard - Account Overview and Management",
    },
    {
      name: "Manage Events",
      href: "/manage/events",
      icon: CalendarCog,
      brief: "Create and manage events",
      seo: "Manage Events - Create, Edit, and Publish Events",
    },
    {
      name: "Manage Profile",
      href: "/manage/account",
      icon: UserCog,
      brief: "Edit your profile information",
      seo: "Manage Profile - Edit Account Information and Settings",
    },
    {
      name: "Contacts",
      href: "/manage/contacts",
      icon: Contact,
      brief: "View and manage contacts",
      seo: "Manage Contacts - View and Organize Your Contact List",
    },
  ],
  account: [
    {
      name: "Bookmarked Events",
      href: "/me/events",
      icon: Bookmark,
      brief: "View your saved events",
      seo: "Bookmarked Events - Your Saved and Upcoming Events",
    },
    {
      name: "Favorites",
      href: "/me/favorites",
      icon: Heart,
      brief: "See your favorite performers and venues",
      seo: "Favorite Performers and Venues - Your Top Picks",
    },
    {
      name: "Tickets",
      href: "/me/tickets",
      icon: Ticket,
      brief: "View your purchased tickets",
      seo: "Your Tickets - View and Manage Purchased Tickets",
    },
  ],
  settings: [
    {
      name: "Settings",
      href: "/me",
      icon: Cog,
      brief: "Manage your account settings",
      seo: "Account Settings - Manage Preferences and Notifications",
    },
  ],
} as const;
