services:
  # SSL Certification for dev
  # mkcert:
  #   image: node:alpine
  #   command:
  #     [
  #       'mkdir certs',
  #       '&&',
  #       'cd',
  #       'certs',
  #       '&&',
  #       'mkcert',
  #       'localhost',
  #       '"*.localhost"',
  #       '-install',
  #     ]
  #   volumes:
  #     - ./certs:/etc/letsencrypt

  # Nginx Reverse Proxy
  nginx:
    image: nginx:mainline-alpine
    build:
      context: ./
      dockerfile: ./apps/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
      - auth
      - static
      - websocket
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - mkcert-data:/etc/nginx/certs

  # Postgres Database
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lmx-dev
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Auth service - auth.<app>.com
  auth:
    build:
      context: ./
      dockerfile: ./apps/services/auth/dev.Dockerfile
    ports:
      - '4000:4000' # Adjust port mapping
    depends_on:
      - postgres
    env_file:
      - .env.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # Static Content service - static.<app>.com
  static:
    build:
      context: ./
      dockerfile: ./apps/services/static/dev.Dockerfile
    ports:
      - '3000:3000' # Adjust port mapping
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # Gateways
  # Rest API gateway - api.<app>.com
  api:
    build:
      context: ./
      dockerfile: ./apps/gateways/api/dev.Dockerfile
    ports:
      - '5000:5000' # Adjust port mapping
    env_file:
      - .env.local
    depends_on:
      - auth
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # Websocket gateway - io.<app>.com
  websocket:
    build:
      context: ./
      dockerfile: ./apps/gateways/websocket/dev.Dockerfile
    ports:
      - '5002:5002' # Adjust port mapping
    env_file:
      - .env.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres-data:
  app-code:
